-- a simple file to display a help message:

print("\x1b[2J")
print("\x1b[1;31m")
print("           ILUA HELP ('vi ihelp.lua' to edit this file as required)")
print("           ========================================================")
print("")
print("\x1b[33m")
print("   LEFT ARROW (or CTRL B)  : move cursor left")
print("   RIGHT ARROW (or CTRL F) : move cursor right")
print("   UP ARROW (or CTRL P)    : previous command in history")
print("   DOWN ARROW (or CTRL N)  : next command in history")
print("   HOME (or CTRL A)        : move cursor to start of line")
print("   END (or CTRL E)         : move cursor to end of line")
print("   CTRL U                  : clear entire line")
print("   CTRL K                  : clear from cursor to end of line")
print("   CTRL L                  : clear screen")
print("   CTRL W                  : clear previous word")
print("   CTRL T                  : swap current and previous characters ")
print("   CTRL C                  : exit")
print("   CTRL D                  : at start of line means exit (otherwise delete)")
print("   TAB                     : command completion")
print("")
print("\x1b[0;37m")

