#!/bin/bash -login
#
unset CATALINA_DEFINE
export CATALINA_DEFINE=HYPER

make clean
make -B all NATIVE=TRUE PROPELLER_2=TRUE OUTPUT="../.."

make clean
make -B all COMPACT=TRUE PROPELLER_2=TRUE OUTPUT="../.."

make clean
make -B all LARGE=TRUE PROPELLER_2=TRUE OUTPUT="../.."
