include ../Makefile.inc

all:	 \
	doprintf.s \
	doprntfs.s \
	doscanf.s \
	fgetc.s \
	fputc.s \
	getdec.s \
	getfnum.s \
	gethex.s \
	getldec.s \
	getlfnum.s \
	getlhex.s \
	getludec.s \
	gets.s \
	getudec.s \
	printf.s \
	ppad.s \
	pputc.s \
	pputl.s \
	pputll.s \
	pputls.s \
	pputn.s \
	pputs.s \
	printfs.s \
	putdec.s \
	putfnum.s \
	puthex.s \
	putldec.s \
	putlfnum.s \
	putlhex.s \
	putludec.s \
	putstr.s \
	putudec.s \
	safegets.s \
	scanf.s \
	scanfgl.s \
	scanfgll.s \
	siodev.h \
	sprintf.s \
	Makefile \
	sscanf.s

clean:
	-rm -f *.s
