#!/bin/bash -login
echo ""
echo " NOTE: This script must be run in an MSYS MINGW32 shell"
echo ""
make clean -f Makefile.mgw LCCDIR=$LCCDIR
make all -f Makefile.mgw LCCDIR=$LCCDIR
make install -f Makefile.mgw LCCDIR=$LCCDIR

