#!/bin/bash
awka -i parallelize_functions.h -f $1.awk> $1.c
gcc -m32 -g -fno-stack-protector -I. -c parallelize_functions.c
gcc -m32 -g -fno-stack-protector -I. -o $1 $1.c parallelize_functions.o awka-0.7.5/lib/libawka.a

