/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>
#include <parallelize_functions.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;
a_VAR *line_no_awk = NULL;
a_VAR *pragma_awk = NULL;
a_VAR *n_awk = NULL;
a_VAR *name_awk = NULL;
a_VAR *worker_awk = NULL;
a_VAR *factory_awk = NULL;
a_VAR *foreman_awk = NULL;
a_VAR *stack_awk = NULL;
a_VAR *lock_awk = NULL;
a_VAR *cogs_awk = NULL;
a_VAR *threads_awk = NULL;
a_VAR *ticks_awk = NULL;
a_VAR *local_awk = NULL;
a_VAR *output_awk = NULL;
a_VAR *when_awk = NULL;
a_VAR *w_awk = NULL;
a_VAR *vars_awk = NULL;
a_VAR *collecting_awk = NULL;
a_VAR *collecting_name_awk = NULL;
a_VAR *exclusive_awk = NULL;
a_VAR *excl_opt_awk = NULL;
a_VAR *management_awk = NULL;
a_VAR *reported_awk = NULL;
a_VAR *new_mgmt_awk = NULL;
a_VAR *j_awk = NULL;
a_VAR *k_awk = NULL;

struct gvar_struct *_gvar;

a_VAR **_lvar;
a_VAR *_litd0_awka=NULL, *_litd1_awka=NULL, *_litd2_awka=NULL, *_litd3_awka=NULL, *_litd4_awka=NULL, *_litd5_awka=NULL, *_litd6_awka=NULL;
a_VAR *_lits0_awka=NULL, *_lits1_awka=NULL, *_lits2_awka=NULL, *_lits3_awka=NULL, *_lits4_awka=NULL, *_lits5_awka=NULL, *_lits6_awka=NULL, *_lits7_awka=NULL, *_lits8_awka=NULL, *_lits9_awka=NULL, *_lits10_awka=NULL, *_lits11_awka=NULL, *_lits12_awka=NULL, *_lits13_awka=NULL, *_lits14_awka=NULL, *_lits15_awka=NULL, *_lits16_awka=NULL, *_lits17_awka=NULL, *_lits18_awka=NULL, *_lits19_awka=NULL, *_lits20_awka=NULL, *_lits21_awka=NULL, *_lits22_awka=NULL, *_lits23_awka=NULL, *_lits24_awka=NULL, *_lits25_awka=NULL, *_lits26_awka=NULL, *_lits27_awka=NULL, *_lits28_awka=NULL, *_lits29_awka=NULL, *_lits30_awka=NULL, *_lits31_awka=NULL, *_lits32_awka=NULL, *_lits33_awka=NULL, *_lits34_awka=NULL, *_lits35_awka=NULL, *_lits36_awka=NULL, *_lits37_awka=NULL, *_lits38_awka=NULL, *_lits39_awka=NULL, *_lits40_awka=NULL, *_lits41_awka=NULL, *_lits42_awka=NULL, *_lits43_awka=NULL, *_lits44_awka=NULL, *_lits45_awka=NULL, *_lits46_awka=NULL, *_lits47_awka=NULL, *_lits48_awka=NULL, *_lits49_awka=NULL, *_lits50_awka=NULL, *_lits51_awka=NULL, *_lits52_awka=NULL, *_lits53_awka=NULL, *_lits54_awka=NULL, *_lits55_awka=NULL, *_lits56_awka=NULL;
a_VAR *_litr0_awka=NULL, *_litr1_awka=NULL, *_litr2_awka=NULL, *_litr3_awka=NULL, *_litr4_awka=NULL, *_litr5_awka=NULL, *_litr6_awka=NULL, *_litr7_awka=NULL, *_litr8_awka=NULL, *_litr9_awka=NULL, *_litr10_awka=NULL, *_litr11_awka=NULL, *_litr12_awka=NULL, *_litr13_awka=NULL, *_litr14_awka=NULL, *_litr15_awka=NULL, *_litr16_awka=NULL;
a_VAR * memory_management_fn(a_VARARG *);
a_VAR * get_pragma_options_fn(a_VARARG *);
a_VAR * match_paren_fn(a_VARARG *);
a_VAR * my_right_fn(a_VARARG *);
a_VAR * trim_parentheses_fn(a_VARARG *);
a_VAR * malformed_option_fn(a_VARARG *);
a_VAR * remove_chars_fn(a_VARARG *);
a_VAR * token_fn(a_VARARG *);
void BEGIN();
void MAIN();
void END();

void
BEGIN()
{
  awka_vardblset(line_no_awk, 0);
  initialize_pragma_fn(awka_arg0(a_TEMP));

}


void
END()
{
  finalize_pragma_fn(awka_arg0(a_TEMP));

}


void
MAIN()
{
  int i, _curfile;
  if (*(awka_gets(a_bivar[a_FILENAME])) == '\0')
    awka_strcpy(a_bivar[a_FILENAME], "");
  i = setjmp(context);
  while (awka_getline(a_TEMP, awka_dol0(0), awka_gets(a_bivar[a_FILENAME]), FALSE, TRUE)->dval > 0 && awka_setNF())
  {
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
      awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits1_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      awka_strcpy(name_awk, "_worker");
      if (((awka_var2dblcmp(n_awk, 0) == 0)) || !strcmp(awka_gets(worker_awk), ""))
      {
        awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
        awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits1_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
        goto __291;
      }
      if (!strcmp(awka_gets(factory_awk), ""))
      {
        awka_strcpy(factory_awk, "_factory");
      }
      if (!strcmp(awka_gets(foreman_awk), ""))
      {
        awka_strcpy(foreman_awk, "_foreman");
      }
      if (!strcmp(awka_gets(stack_awk), ""))
      {
        awka_strcpy(stack_awk, "200");
      }
      if (!strcmp(awka_gets(lock_awk), ""))
      {
        awka_strcpy(lock_awk, "_kernel_lock");
      }
      if (!strcmp(awka_gets(cogs_awk), ""))
      {
        awka_strcpy(cogs_awk, "ANY_COG");
      }
      if (!strcmp(awka_gets(threads_awk), ""))
      {
        awka_strcpy(threads_awk, "10");
      }
      if (!strcmp(awka_gets(ticks_awk), ""))
      {
        awka_strcpy(ticks_awk, "100");
      }
      memory_management_fn(awka_arg0(a_TEMP));
      if (!(awka_vartrue(known_factory_fn(awka_arg1(a_TEMP, factory_awk)))))
      {
        define_factory_fn(awka_vararg(a_TEMP, factory_awk, foreman_awk, stack_awk, lock_awk, cogs_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      }
      define_worker_fn(awka_vararg(a_TEMP, name_awk, worker_awk, local_awk, output_awk, when_awk, stack_awk, factory_awk, threads_awk, ticks_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits12_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      __291:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if (((awka_var2dblcmp(n_awk, 0) == 0)) || !strcmp(name_awk->ptr, ""))
      {
        awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
        awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits13_awka, a_bivar[a_FILENAME], line_no_awk, w_awk, NULL));
        goto __551;
      }
      awka_varcpy(worker_awk, vars_awk);
      if (!strcmp(factory_awk->ptr, ""))
      {
        awka_strcpy(factory_awk, "_factory");
      }
      if (!strcmp(foreman_awk->ptr, ""))
      {
        awka_strcpy(foreman_awk, "_foreman");
      }
      if (!strcmp(stack_awk->ptr, ""))
      {
        awka_strcpy(stack_awk, "200");
      }
      if (!strcmp(lock_awk->ptr, ""))
      {
        awka_strcpy(lock_awk, "_kernel_lock");
      }
      if (!strcmp(cogs_awk->ptr, ""))
      {
        awka_strcpy(cogs_awk, "ANY_COG");
      }
      if (!strcmp(threads_awk->ptr, ""))
      {
        awka_strcpy(threads_awk, "10");
      }
      if (!strcmp(ticks_awk->ptr, ""))
      {
        awka_strcpy(ticks_awk, "100");
      }
      memory_management_fn(awka_arg0(a_TEMP));
      if (!(awka_vartrue(known_factory_fn(awka_arg1(a_TEMP, factory_awk)))))
      {
        define_factory_fn(awka_vararg(a_TEMP, factory_awk, foreman_awk, stack_awk, lock_awk, cogs_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      }
      define_worker_fn(awka_vararg(a_TEMP, name_awk, worker_awk, local_awk, output_awk, when_awk, stack_awk, factory_awk, threads_awk, ticks_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits12_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      __551:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_strcpy(awka_doln(3, 1), "");
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(factory_awk, "_factory");
        goto __639;
      }
      if (!strcmp(factory_awk->ptr, ""))
      {
        if (!strcmp(name_awk->ptr, ""))
        {
          awka_strcpy(factory_awk, "_factory");
          goto __639;
        }
        awka_strcpy(factory_awk, name_awk->ptr);
        __639:;
      }
      if (!strcmp(foreman_awk->ptr, ""))
      {
        awka_strcpy(foreman_awk, "_foreman");
      }
      if (!strcmp(stack_awk->ptr, ""))
      {
        awka_strcpy(stack_awk, "50");
      }
      if (!strcmp(lock_awk->ptr, ""))
      {
        awka_strcpy(lock_awk, "_kernel_lock");
      }
      if (!strcmp(cogs_awk->ptr, ""))
      {
        awka_strcpy(cogs_awk, "ANY_COG");
      }
      memory_management_fn(awka_arg0(a_TEMP));
      define_factory_fn(awka_vararg(a_TEMP, factory_awk, foreman_awk, stack_awk, lock_awk, cogs_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits15_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_strcpy(awka_doln(3, 1), "");
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_worker");
        goto __825;
      }
      if (!strcmp(awka_gets(worker_awk), ""))
      {
        if (!strcmp(name_awk->ptr, ""))
        {
          awka_strcpy(name_awk, "_worker");
        }
        goto __825;
      }
      awka_varcpy(name_awk, worker_awk);
      __825:;
      if (awka_vartrue(collecting_awk))
      {
        awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
        awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits16_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
        goto __861;
      }
      awka_vardblset(collecting_awk, 1);
      __861:;
      memory_management_fn(awka_arg0(a_TEMP));
      if (awka_vartrue(known_worker_fn(awka_arg1(a_TEMP, name_awk))))
      {
        awka_strcpy(collecting_name_awk, name_awk->ptr);
        goto __906;
      }
      awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
      awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits17_awka, a_bivar[a_FILENAME], line_no_awk, name_awk, NULL));
      __906:;
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits18_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_strcpy(awka_doln(3, 1), "");
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_worker");
        goto __1018;
      }
      if (!strcmp(awka_gets(worker_awk), ""))
      {
        if (!strcmp(name_awk->ptr, ""))
        {
          awka_strcpy(name_awk, "_worker");
        }
        goto __1018;
      }
      awka_varcpy(name_awk, worker_awk);
      __1018:;
      memory_management_fn(awka_arg0(a_TEMP));
      if (awka_vartrue(exclusive_awk))
      {
        awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
        awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits19_awka, a_bivar[a_FILENAME], line_no_awk, name_awk, NULL));
      }
      awka_vardblset(collecting_awk, 0);
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits20_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_strcpy(awka_doln(3, 1), "");
      awka_strcpy(excl_opt_awk, "");
      if (!strcmp(awka_gets(awka_doln(4, 0)), "lock"))
      {
        awka_strcpy(awka_doln(4, 1), "");
        awka_strcpy(excl_opt_awk, "lock");
        goto __1163;
      }
      if (!strcmp(awka_gets(awka_doln(4, 0)), "extern"))
      {
        awka_strcpy(awka_doln(4, 1), "");
        awka_strcpy(excl_opt_awk, "extern");
        __1163:;
      }
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_region");
        goto __1218;
      }
      if (!strcmp(awka_gets(worker_awk), ""))
      {
        if (!strcmp(name_awk->ptr, ""))
        {
          awka_strcpy(name_awk, "_region");
        }
        goto __1218;
      }
      awka_varcpy(name_awk, worker_awk);
      __1218:;
      memory_management_fn(awka_arg0(a_TEMP));
      if (awka_vartrue(exclusive_awk))
      {
        awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
        awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits24_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
        goto __1258;
      }
      awka_vardblset(exclusive_awk, 1);
      __1258:;
      if (!(awka_vartrue(known_exclusion_fn(awka_arg1(a_TEMP, name_awk)))))
      {
        define_exclusion_fn(awka_vararg(a_TEMP, name_awk, a_bivar[a_FILENAME], line_no_awk, excl_opt_awk, NULL));
      }
      if (awka_vartrue(collecting_awk))
      {
        add_line_to_worker_fn(awka_vararg(a_TEMP, collecting_name_awk, _lits25_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
        add_line_to_worker_fn(awka_vararg(a_TEMP, collecting_name_awk, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
        goto __1332;
      }
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits25_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      __1332:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_strcpy(awka_doln(3, 1), "");
      awka_strcpy(excl_opt_awk, "");
      if (!strcmp(awka_gets(awka_doln(4, 0)), "lock"))
      {
        awka_strcpy(awka_doln(4, 1), "");
        awka_strcpy(excl_opt_awk, "lock");
        goto __1413;
      }
      if (!strcmp(awka_gets(awka_doln(4, 0)), "extern"))
      {
        awka_strcpy(awka_doln(4, 1), "");
        awka_strcpy(excl_opt_awk, "extern");
        __1413:;
      }
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_region");
        goto __1468;
      }
      if (!strcmp(awka_gets(worker_awk), ""))
      {
        if (!strcmp(name_awk->ptr, ""))
        {
          awka_strcpy(name_awk, "_region");
        }
        goto __1468;
      }
      awka_varcpy(name_awk, worker_awk);
      __1468:;
      memory_management_fn(awka_arg0(a_TEMP));
      awka_vardblset(exclusive_awk, 0);
      if (!(awka_vartrue(known_exclusion_fn(awka_arg1(a_TEMP, name_awk)))))
      {
        define_exclusion_fn(awka_vararg(a_TEMP, name_awk, a_bivar[a_FILENAME], line_no_awk, excl_opt_awk, NULL));
      }
      if (awka_vartrue(collecting_awk))
      {
        add_line_to_worker_fn(awka_vararg(a_TEMP, collecting_name_awk, _lits26_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
        add_line_to_worker_fn(awka_vararg(a_TEMP, collecting_name_awk, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
        goto __1552;
      }
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits26_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      __1552:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_varcpy(awka_doln(3, 1), my_right_fn(awka_arg2(a_TEMP, awka_doln(3, 0), _litd2_awka)));
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_worker");
        goto __1646;
      }
      if (!strcmp(awka_gets(worker_awk), ""))
      {
        if (!strcmp(name_awk->ptr, ""))
        {
          awka_strcpy(name_awk, "_worker");
        }
        goto __1646;
      }
      awka_varcpy(name_awk, worker_awk);
      __1646:;
      memory_management_fn(awka_arg0(a_TEMP));
      if (!(awka_vartrue(known_worker_fn(awka_arg1(a_TEMP, name_awk)))))
      {
        awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
        awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits17_awka, a_bivar[a_FILENAME], line_no_awk, name_awk, NULL));
      }
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits27_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      if (!strcmp(awka_gets(vars_awk), ""))
      {
        add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
        goto __1735;
      }
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, awka_strconcat3(a_TEMP, name_awk, _lits28_awka, vars_awk), a_bivar[a_FILENAME], line_no_awk, NULL));
      __1735:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_strcpy(awka_doln(3, 1), "");
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_factory");
        goto __1823;
      }
      if (!strcmp(factory_awk->ptr, ""))
      {
        if (!strcmp(name_awk->ptr, ""))
        {
          awka_strcpy(name_awk, "_factory");
        }
        goto __1823;
      }
      awka_strcpy(name_awk, factory_awk->ptr);
      __1823:;
      memory_management_fn(awka_arg0(a_TEMP));
      if (!(awka_vartrue(known_factory_fn(awka_arg1(a_TEMP, name_awk)))))
      {
        awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
        awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits29_awka, a_bivar[a_FILENAME], line_no_awk, name_awk, NULL));
      }
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits30_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr10_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_strcpy(awka_doln(3, 1), "");
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_factory");
        goto __1973;
      }
      if (!strcmp(factory_awk->ptr, ""))
      {
        if (!strcmp(name_awk->ptr, ""))
        {
          awka_strcpy(name_awk, "_factory");
        }
        goto __1973;
      }
      awka_strcpy(name_awk, factory_awk->ptr);
      __1973:;
      memory_management_fn(awka_arg0(a_TEMP));
      if (!(awka_vartrue(known_factory_fn(awka_arg1(a_TEMP, name_awk)))))
      {
        awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
        awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits29_awka, a_bivar[a_FILENAME], line_no_awk, name_awk, NULL));
      }
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits31_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr11_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_varcpy(awka_doln(3, 1), my_right_fn(awka_arg2(a_TEMP, awka_doln(3, 0), _litd2_awka)));
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_kernel_lock");
        goto __2144;
      }
      if (!strcmp(name_awk->ptr, ""))
      {
        if (strcmp(lock_awk->ptr, ""))
        {
          awka_strcpy(name_awk, lock_awk->ptr);
          goto __2144;
        }
        if (strcmp(awka_gets(vars_awk), ""))
        {
          awka_varcpy(name_awk, vars_awk);
          goto __2144;
        }
        awka_strcpy(name_awk, "_kernel_lock");
        __2144:;
      }
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits32_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr12_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_strcpy(awka_doln(3, 1), "");
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_kernel_lock");
        goto __2241;
      }
      if (!strcmp(name_awk->ptr, ""))
      {
        awka_strcpy(name_awk, "_kernel_lock");
        __2241:;
      }
      memory_management_fn(awka_arg0(a_TEMP));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits33_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr13_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_strcpy(awka_doln(1, 1), "");
      awka_strcpy(awka_doln(2, 1), "");
      awka_strcpy(awka_doln(3, 1), "");
      awka_varcpy(n_awk, get_pragma_options_fn(awka_arg1(a_TEMP, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_dol0(0))))));
      if ((awka_var2dblcmp(n_awk, 0) == 0))
      {
        awka_strcpy(name_awk, "_kernel_lock");
        goto __2342;
      }
      if (!strcmp(name_awk->ptr, ""))
      {
        awka_strcpy(name_awk, "_kernel_lock");
        __2342:;
      }
      memory_management_fn(awka_arg0(a_TEMP));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, _lits34_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, name_awk, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr14_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
      awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits35_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr15_awka, NULL)))
    {
      awka_poi(line_no_awk);
      awka_varcpy(pragma_awk, awka_dol0(0));
      awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
      awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits36_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      goto nextrec;
    }
    awka_poi(line_no_awk);
    if (awka_vartrue(collecting_awk))
    {
      add_line_to_worker_fn(awka_vararg(a_TEMP, collecting_name_awk, awka_dol0(0), a_bivar[a_FILENAME], line_no_awk, NULL));
      goto __2483;
    }
    add_line_to_worker_fn(awka_vararg(a_TEMP, _lits11_awka, awka_dol0(0), a_bivar[a_FILENAME], line_no_awk, NULL));
    __2483:;
    nextrec:;
  }
}


a_VAR *
memory_management_fn( a_VARARG *va )
{
  a_VAR *_ret = NULL;
  static int _fn_idx = -1;
  if (_fn_idx == -1)
    _fn_idx = _awka_registerfn("memory_management",0);
  _ret = _awka_addfncall(_fn_idx);
  if (strcmp(awka_gets(management_awk), ""))
  {
    if ((!strcmp(awka_gets(management_awk), "static")) || !strcmp(awka_gets(management_awk), "dynamic"))
    {
      set_memory_management_fn(awka_arg1(a_TEMP, management_awk));
      goto __66;
    }
    if (!(awka_vartrue(reported_awk)))
    {
      awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
      awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits39_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
      awka_vardblset(reported_awk, 1);
      __66:;
  } }
  _awka_retfn(_fn_idx);
  return _ret;

}


a_VAR *
get_pragma_options_fn( a_VARARG *va )
{
  a_VAR *_ret = NULL;
  static int _fn_idx = -1;
  int _i;
  a_VAR *_lvar[3];

  static int _type[3] = {1, 1, 1};
  if (_fn_idx == -1)
    _fn_idx = _awka_registerfn("get_pragma_options",3);
  _ret = _awka_addfncall(_fn_idx);
  for (_i=0; _i<3; _i++)
  {
    if (va->used <= _i)
      _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
    else
    {
      switch(va->var[_i]->type)
      {
        case a_VARARR:
        _lvar[_i] = va->var[_i];
        break;

        default:
        _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
        if (!_type[_i] && !va->var[_i]->temp)
          awka_lcopy(_lvar[_i], va->var[_i]);
        else
          awka_varcpy(_lvar[_i], va->var[_i]);
      }
    }
  }

  awka_vardblset(_lvar[1], 0);
  awka_strcpy(threads_awk, "");
  awka_strcpy(ticks_awk, "");
  awka_strcpy(factory_awk, "");
  awka_strcpy(foreman_awk, "");
  awka_strcpy(local_awk, "");
  awka_strcpy(output_awk, "");
  awka_strcpy(worker_awk, "");
  awka_strcpy(stack_awk, "");
  awka_strcpy(cogs_awk, "");
  awka_strcpy(lock_awk, "");
  awka_strcpy(name_awk, "");
  awka_strcpy(vars_awk, "");
  awka_strcpy(when_awk, "");
  while (awka_length(_lvar[0]) > awka_getd(_litd0_awka))
  {
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits40_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd3_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __171;
        }
        awka_varcpy(threads_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(threads_awk, trim_parentheses_fn(awka_arg1(a_TEMP, threads_awk)));
        __171:;
        goto __180;
      }
      malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
      _awka_retfn(_fn_idx);
      return _ret;
      __180:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits42_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd4_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __317;
        }
        awka_varcpy(new_mgmt_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(new_mgmt_awk, trim_parentheses_fn(awka_arg1(a_TEMP, new_mgmt_awk)));
        if (!strcmp(awka_gets(management_awk), ""))
        {
          awka_varcpy(management_awk, new_mgmt_awk);
          goto __317;
        }
        if (awka_varcmp(management_awk, new_mgmt_awk))
        {
          awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
          awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits43_awka, a_bivar[a_FILENAME], line_no_awk, NULL));
          __317:;
        }
        goto __326;
      }
      malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
      _awka_retfn(_fn_idx);
      return _ret;
      __326:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits44_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd5_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __417;
        }
        awka_varcpy(when_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(when_awk, trim_parentheses_fn(awka_arg1(a_TEMP, when_awk)));
        __417:;
        goto __426;
      }
      malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
      _awka_retfn(_fn_idx);
      return _ret;
      __426:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits45_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd6_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __517;
        }
        awka_varcpy(ticks_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(ticks_awk, trim_parentheses_fn(awka_arg1(a_TEMP, ticks_awk)));
        __517:;
        goto __526;
      }
      malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
      _awka_retfn(_fn_idx);
      return _ret;
      __526:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits46_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd3_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __617;
        }
        awka_varcpy(factory_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(factory_awk, trim_parentheses_fn(awka_arg1(a_TEMP, factory_awk)));
        __617:;
        goto __625;
      }
      awka_strcpy(factory_awk, "");
      __625:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits47_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd3_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __716;
        }
        awka_varcpy(foreman_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(foreman_awk, trim_parentheses_fn(awka_arg1(a_TEMP, foreman_awk)));
        __716:;
        goto __724;
      }
      awka_strcpy(foreman_awk, "");
      __724:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits48_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd6_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __824;
        }
        awka_varcpy(local_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(local_awk, trim_parentheses_fn(awka_arg1(a_TEMP, local_awk)));
        awka_sub(a_TEMP, TRUE, FALSE, _litr16_awka, awka_ro_str2var(";"), local_awk);
        __824:;
        goto __833;
      }
      malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
      _awka_retfn(_fn_idx);
      return _ret;
      __833:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits49_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd4_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __933;
        }
        awka_varcpy(output_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(output_awk, trim_parentheses_fn(awka_arg1(a_TEMP, output_awk)));
        awka_sub(a_TEMP, TRUE, FALSE, _litr16_awka, awka_ro_str2var(";"), output_awk);
        __933:;
        goto __942;
      }
      malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
      _awka_retfn(_fn_idx);
      return _ret;
      __942:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits50_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd4_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __1074;
        }
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 2) == 0))
        {
          awka_strcpy(worker_awk, "void");
          awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
          goto __1074;
        }
        awka_varcpy(worker_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(worker_awk, trim_parentheses_fn(awka_arg1(a_TEMP, worker_awk)));
        awka_sub(a_TEMP, TRUE, FALSE, _litr16_awka, awka_ro_str2var(";"), worker_awk);
        __1074:;
        goto __1082;
      }
      awka_strcpy(worker_awk, "");
      __1082:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits21_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd2_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __1173;
        }
        awka_varcpy(lock_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(lock_awk, trim_parentheses_fn(awka_arg1(a_TEMP, lock_awk)));
        __1173:;
        goto __1181;
      }
      awka_strcpy(lock_awk, "");
      __1181:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits52_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd6_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __1272;
        }
        awka_varcpy(stack_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(stack_awk, trim_parentheses_fn(awka_arg1(a_TEMP, stack_awk)));
        __1272:;
        goto __1281;
      }
      malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
      _awka_retfn(_fn_idx);
      return _ret;
      __1281:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    if (awka_vartrue(token_fn(awka_arg2(a_TEMP, _lvar[0], _lits53_awka))))
    {
      awka_varcpy(_lvar[0], remove_chars_fn(awka_arg2(a_TEMP, _lvar[0], _litd2_awka)));
      if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
      {
        if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
        {
          malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
          _awka_retfn(_fn_idx);
          return _ret;
          goto __1372;
        }
        awka_varcpy(cogs_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
        awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
        awka_varcpy(cogs_awk, trim_parentheses_fn(awka_arg1(a_TEMP, cogs_awk)));
        __1372:;
        goto __1381;
      }
      malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
      _awka_retfn(_fn_idx);
      return _ret;
      __1381:;
      awka_poi(_lvar[1]);
      goto __1610;
    }
    awka_vardblset(_lvar[2], awka_index(_lvar[0], _lits41_awka));
    awka_vardblset(j_awk, awka_index(_lvar[0], _lits28_awka));
    if ((((_lvar[2]->dval > 0) &&  j_awk->dval > 0)) && j_awk->dval < _lvar[2]->dval)
    {
      awka_vardblset(k_awk, j_awk->dval);
      while (k_awk->dval < _lvar[2]->dval)
      {
        if (strcmp(awka_gets(awka_substr(a_TEMP, _lvar[0], k_awk->dval, 1)), " "))
        {
          awka_vardblset(_lvar[2], (k_awk->dval - 1));
          break;
        }
        awka_poi(k_awk);
      }
    }
    if (_lvar[2]->dval == 0)
    {
      awka_vardblset(_lvar[2], awka_length(_lvar[0]));
      goto __1500;
    }
    awka_pod(_lvar[2]);
    __1500:;
    if (_lvar[2]->dval > 0)
    {
      awka_varcpy(name_awk, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_left(a_TEMP, _lvar[0], _lvar[2]))));
      awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
    }
    if (!strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "("))
    {
      if ((awka_var2dblcmp(awka_varcpy(_lvar[2], match_paren_fn(awka_arg1(a_TEMP, _lvar[0]))), 0) == 0))
      {
        malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
        _awka_retfn(_fn_idx);
        return _ret;
        goto __1606;
      }
      awka_varcpy(vars_awk, awka_left(a_TEMP, _lvar[0], _lvar[2]));
      awka_varcpy(_lvar[0], my_right_fn(awka_arg2(a_TEMP, _lvar[0], _lvar[2])));
      awka_varcpy(vars_awk, trim_parentheses_fn(awka_arg1(a_TEMP, vars_awk)));
      awka_sub(a_TEMP, TRUE, FALSE, _litr16_awka, awka_ro_str2var(";"), vars_awk);
      __1606:;
    }
    awka_poi(_lvar[1]);
    __1610:;
  }
  awka_varcpy(_ret, _lvar[1]);
  _awka_retfn(_fn_idx);
  return _ret;
  _awka_retfn(_fn_idx);
  return _ret;

}


a_VAR *
match_paren_fn( a_VARARG *va )
{
  a_VAR *_ret = NULL;
  static int _fn_idx = -1;
  int _i;
  a_VAR *_lvar[6];

  static int _type[6] = {0, 1, 1, 1, 1, 1};
  if (_fn_idx == -1)
    _fn_idx = _awka_registerfn("match_paren",6);
  _ret = _awka_addfncall(_fn_idx);
  for (_i=0; _i<6; _i++)
  {
    if (va->used <= _i)
      _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
    else
    {
      switch(va->var[_i]->type)
      {
        case a_VARARR:
        _lvar[_i] = va->var[_i];
        break;

        default:
        _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
        if (!_type[_i] && !va->var[_i]->temp)
          awka_lcopy(_lvar[_i], va->var[_i]);
        else
          awka_varcpy(_lvar[_i], va->var[_i]);
      }
    }
  }

  awka_vardblset(_lvar[1], awka_length(_lvar[0]));
  if (_lvar[1]->dval < 2)
  {
    awka_varcpy(_ret, _litd0_awka);
    _awka_retfn(_fn_idx);
    return _ret;
  }
  awka_vardblset(_lvar[3], awka_index(_lvar[0], _lits41_awka));
  if (_lvar[3]->dval == 0)
  {
    awka_varcpy(_ret, _litd0_awka);
    _awka_retfn(_fn_idx);
    return _ret;
  }
  awka_vardblset(_lvar[2], 1);
  awka_vardblset(_lvar[5], (_lvar[3]->dval + 1));
  while (_lvar[5]->dval <= _lvar[1]->dval)
  {
    if (!strcmp(awka_substr(a_TEMP, _lvar[0], _lvar[5]->dval, 1)->ptr, "("))
    {
      awka_poi(_lvar[2]);
      goto __113;
    }
    if (!strcmp(awka_substr(a_TEMP, _lvar[0], _lvar[5]->dval, 1)->ptr, ")"))
    {
      awka_pod(_lvar[2]);
      awka_vardblset(_lvar[4], _lvar[5]->dval);
      if (_lvar[2]->dval == 0)
      {
        awka_varcpy(_ret, _lvar[4]);
        _awka_retfn(_fn_idx);
        return _ret;
        __113:;
    } }
    awka_poi(_lvar[5]);
  }
  awka_varcpy(_ret, _litd0_awka);
  _awka_retfn(_fn_idx);
  return _ret;
  _awka_retfn(_fn_idx);
  return _ret;

}


a_VAR *
my_right_fn( a_VARARG *va )
{
  a_VAR *_ret = NULL;
  static int _fn_idx = -1;
  int _i;
  a_VAR *_lvar[2];

  static int _type[2] = {1, 0};
  if (_fn_idx == -1)
    _fn_idx = _awka_registerfn("my_right",2);
  _ret = _awka_addfncall(_fn_idx);
  for (_i=0; _i<2; _i++)
  {
    if (va->used <= _i)
      _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
    else
    {
      switch(va->var[_i]->type)
      {
        case a_VARARR:
        _lvar[_i] = va->var[_i];
        break;

        default:
        _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
        if (!_type[_i] && !va->var[_i]->temp)
          awka_lcopy(_lvar[_i], va->var[_i]);
        else
          awka_varcpy(_lvar[_i], va->var[_i]);
      }
    }
  }

  if (awka_length(_lvar[0]) == _lvar[1]->dval)
  {
    awka_strcpy(_lvar[0], "");
    goto __40;
  }
  awka_varcpy(_lvar[0], awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_right(a_TEMP, _lvar[0], awka_tmp_dbl2var((awka_length(_lvar[0]) - (awka_getd(_lvar[1]))))))));
  __40:;
  awka_varcpy(_ret, _lvar[0]);
  _awka_retfn(_fn_idx);
  return _ret;
  _awka_retfn(_fn_idx);
  return _ret;

}


a_VAR *
trim_parentheses_fn( a_VARARG *va )
{
  a_VAR *_ret = NULL;
  static int _fn_idx = -1;
  int _i;
  a_VAR *_lvar[1];

  static int _type[1] = {0};
  if (_fn_idx == -1)
    _fn_idx = _awka_registerfn("trim_parentheses",1);
  _ret = _awka_addfncall(_fn_idx);
  for (_i=0; _i<1; _i++)
  {
    if (va->used <= _i)
      _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
    else
    {
      switch(va->var[_i]->type)
      {
        case a_VARARR:
        _lvar[_i] = va->var[_i];
        break;

        default:
        _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
        if (!_type[_i] && !va->var[_i]->temp)
          awka_lcopy(_lvar[_i], va->var[_i]);
        else
          awka_varcpy(_lvar[_i], va->var[_i]);
      }
    }
  }

  if ((strcmp(awka_gets(awka_left(a_TEMP, _lvar[0], _litd1_awka)), "(")) || strcmp(awka_gets(awka_right(a_TEMP, _lvar[0], _litd1_awka)), ")"))
  {
    malformed_option_fn(awka_arg1(a_TEMP, _lvar[0]));
  }
  awka_varcpy(_ret, awka_substr(a_TEMP, _lvar[0], 2, (awka_length(_lvar[0]) - (2))));
  _awka_retfn(_fn_idx);
  return _ret;
  _awka_retfn(_fn_idx);
  return _ret;

}


a_VAR *
malformed_option_fn( a_VARARG *va )
{
  a_VAR *_ret = NULL;
  static int _fn_idx = -1;
  int _i;
  a_VAR *_lvar[1];

  static int _type[1] = {0};
  if (_fn_idx == -1)
    _fn_idx = _awka_registerfn("malformed_option",1);
  _ret = _awka_addfncall(_fn_idx);
  for (_i=0; _i<1; _i++)
  {
    if (va->used <= _i)
      _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
    else
    {
      switch(va->var[_i]->type)
      {
        case a_VARARR:
        _lvar[_i] = va->var[_i];
        break;

        default:
        _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
        if (!_type[_i] && !va->var[_i]->temp)
          awka_lcopy(_lvar[_i], va->var[_i]);
        else
          awka_varcpy(_lvar[_i], va->var[_i]);
      }
    }
  }

  awka_print("/dev/stderr", 0, 0, awka_arg1(a_TEMP, pragma_awk));
  awka_printf("/dev/stderr", 0, 0, awka_vararg(a_TEMP, _lits55_awka, a_bivar[a_FILENAME], line_no_awk, _lvar[0], NULL));
  _awka_retfn(_fn_idx);
  return _ret;

}


a_VAR *
remove_chars_fn( a_VARARG *va )
{
  a_VAR *_ret = NULL;
  static int _fn_idx = -1;
  int _i;
  a_VAR *_lvar[2];

  static int _type[2] = {0, 0};
  if (_fn_idx == -1)
    _fn_idx = _awka_registerfn("remove_chars",2);
  _ret = _awka_addfncall(_fn_idx);
  for (_i=0; _i<2; _i++)
  {
    if (va->used <= _i)
      _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
    else
    {
      switch(va->var[_i]->type)
      {
        case a_VARARR:
        _lvar[_i] = va->var[_i];
        break;

        default:
        _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
        if (!_type[_i] && !va->var[_i]->temp)
          awka_lcopy(_lvar[_i], va->var[_i]);
        else
          awka_varcpy(_lvar[_i], va->var[_i]);
      }
    }
  }

  if (awka_length(_lvar[0]) <= awka_getd(_lvar[1]))
  {
    awka_varcpy(_ret, _lits2_awka);
    _awka_retfn(_fn_idx);
    return _ret;
    goto __34;
  }
  awka_varcpy(_ret, awka_trim(a_TEMP, awka_arg1(a_TEMP, awka_right(a_TEMP, _lvar[0], awka_tmp_dbl2var((awka_length(_lvar[0]) - (awka_getd(_lvar[1]))))))));
  _awka_retfn(_fn_idx);
  return _ret;
  __34:;
  _awka_retfn(_fn_idx);
  return _ret;

}


a_VAR *
token_fn( a_VARARG *va )
{
  a_VAR *_ret = NULL;
  static int _fn_idx = -1;
  int _i;
  a_VAR *_lvar[2];

  static int _type[2] = {0, 0};
  if (_fn_idx == -1)
    _fn_idx = _awka_registerfn("token",2);
  _ret = _awka_addfncall(_fn_idx);
  for (_i=0; _i<2; _i++)
  {
    if (va->used <= _i)
      _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
    else
    {
      switch(va->var[_i]->type)
      {
        case a_VARARR:
        _lvar[_i] = va->var[_i];
        break;

        default:
        _lvar[_i] = awka_fn_varinit(_fn_idx, _i, _type[_i]);
        if (!_type[_i] && !va->var[_i]->temp)
          awka_lcopy(_lvar[_i], va->var[_i]);
        else
          awka_varcpy(_lvar[_i], va->var[_i]);
      }
    }
  }

  if ((!awka_varcmp(awka_left(a_TEMP, _lvar[0], awka_tmp_dbl2var(awka_length(_lvar[1]))), _lvar[1])) && ((((((awka_length(_lvar[0]) == awka_length(_lvar[1])) ||  !strcmp(awka_substr(a_TEMP, _lvar[0], (awka_length(_lvar[1]) + (1)), 1)->ptr, " "))) ||  !strcmp(awka_substr(a_TEMP, _lvar[0], (awka_length(_lvar[1]) + (1)), 1)->ptr, "	"))) ||  !strcmp(awka_substr(a_TEMP, _lvar[0], (awka_length(_lvar[1]) + (1)), 1)->ptr, "(")))
  {
    awka_varcpy(_ret, _litd1_awka);
    _awka_retfn(_fn_idx);
    return _ret;
  }
  awka_varcpy(_ret, _litd0_awka);
  _awka_retfn(_fn_idx);
  return _ret;
  _awka_retfn(_fn_idx);
  return _ret;

}



int
main(int argc, char *argv[])
{
  _max_base_gc = 5;
  _max_fn_gc = 5;

  awka_varinit(line_no_awk);
  awka_varinit(pragma_awk);
  awka_varinit(n_awk);
  awka_varinit(name_awk);
  awka_varinit(worker_awk);
  awka_varinit(factory_awk);
  awka_varinit(foreman_awk);
  awka_varinit(stack_awk);
  awka_varinit(lock_awk);
  awka_varinit(cogs_awk);
  awka_varinit(threads_awk);
  awka_varinit(ticks_awk);
  awka_varinit(local_awk);
  awka_varinit(output_awk);
  awka_varinit(when_awk);
  awka_varinit(w_awk);
  awka_varinit(vars_awk);
  awka_varinit(collecting_awk);
  awka_varinit(collecting_name_awk);
  awka_varinit(exclusive_awk);
  awka_varinit(excl_opt_awk);
  awka_varinit(management_awk);
  awka_varinit(reported_awk);
  awka_varinit(new_mgmt_awk);
  awka_varinit(j_awk);
  awka_varinit(k_awk);

  awka_varinit(_litd0_awka); awka_setd(_litd0_awka) = 0;
  awka_varinit(_litd1_awka); awka_setd(_litd1_awka) = 1;
  awka_varinit(_litd2_awka); awka_setd(_litd2_awka) = 4;
  awka_varinit(_litd3_awka); awka_setd(_litd3_awka) = 7;
  awka_varinit(_litd4_awka); awka_setd(_litd4_awka) = 6;
  awka_varinit(_litd5_awka); awka_setd(_litd5_awka) = 2;
  awka_varinit(_litd6_awka); awka_setd(_litd6_awka) = 5;
  awka_varinit(_lits0_awka); awka_strcpy(_lits0_awka, "/dev/stderr");
  awka_varinit(_lits1_awka); awka_strcpy(_lits1_awka, "%s:%d: propeller pragma does not specify input variables\n");
  awka_varinit(_lits2_awka); awka_strcpy(_lits2_awka, "");
  awka_varinit(_lits3_awka); awka_strcpy(_lits3_awka, "_worker");
  awka_varinit(_lits4_awka); awka_strcpy(_lits4_awka, "_factory");
  awka_varinit(_lits5_awka); awka_strcpy(_lits5_awka, "_foreman");
  awka_varinit(_lits6_awka); awka_strcpy(_lits6_awka, "200");
  awka_varinit(_lits7_awka); awka_strcpy(_lits7_awka, "_kernel_lock");
  awka_varinit(_lits8_awka); awka_strcpy(_lits8_awka, "ANY_COG");
  awka_varinit(_lits9_awka); awka_strcpy(_lits9_awka, "10");
  awka_varinit(_lits10_awka); awka_strcpy(_lits10_awka, "100");
  awka_varinit(_lits11_awka); awka_strcpy(_lits11_awka, "__main");
  awka_varinit(_lits12_awka); awka_strcpy(_lits12_awka, "##worker##");
  awka_varinit(_lits13_awka); awka_strcpy(_lits13_awka, "%s:%d: propeller pragma does not specify a worker '%s'\n");
  awka_varinit(_lits14_awka); awka_strcpy(_lits14_awka, "50");
  awka_varinit(_lits15_awka); awka_strcpy(_lits15_awka, "##factory##");
  awka_varinit(_lits16_awka); awka_strcpy(_lits16_awka, "%s:%d: propeller pragma begin cannot be nested\n");
  awka_varinit(_lits17_awka); awka_strcpy(_lits17_awka, "%s:%d: propeller pragma specifies unknown worker '%s'\n");
  awka_varinit(_lits18_awka); awka_strcpy(_lits18_awka, "##begin##");
  awka_varinit(_lits19_awka); awka_strcpy(_lits19_awka, "%s:%d: propeller pragma end appears before shared '%s'\n");
  awka_varinit(_lits20_awka); awka_strcpy(_lits20_awka, "##end##");
  awka_varinit(_lits21_awka); awka_strcpy(_lits21_awka, "lock");
  awka_varinit(_lits22_awka); awka_strcpy(_lits22_awka, "extern");
  awka_varinit(_lits23_awka); awka_strcpy(_lits23_awka, "_region");
  awka_varinit(_lits24_awka); awka_strcpy(_lits24_awka, "%s:%d: propeller pragma exclusive cannot be nested\n");
  awka_varinit(_lits25_awka); awka_strcpy(_lits25_awka, "##exclusive##");
  awka_varinit(_lits26_awka); awka_strcpy(_lits26_awka, "##shared##");
  awka_varinit(_lits27_awka); awka_strcpy(_lits27_awka, "##wait##");
  awka_varinit(_lits28_awka); awka_strcpy(_lits28_awka, " ");
  awka_varinit(_lits29_awka); awka_strcpy(_lits29_awka, "%s:%d: propeller pragma specifies unknown factory '%s'\n");
  awka_varinit(_lits30_awka); awka_strcpy(_lits30_awka, "##start##");
  awka_varinit(_lits31_awka); awka_strcpy(_lits31_awka, "##stop##");
  awka_varinit(_lits32_awka); awka_strcpy(_lits32_awka, "##lock##");
  awka_varinit(_lits33_awka); awka_strcpy(_lits33_awka, "##extern##");
  awka_varinit(_lits34_awka); awka_strcpy(_lits34_awka, "##kernel##");
  awka_varinit(_lits35_awka); awka_strcpy(_lits35_awka, "%s:%d: warning: propeller pragma not recognized\n");
  awka_varinit(_lits36_awka); awka_strcpy(_lits36_awka, "%s:%d: warning: non-propeller pragma ignored\n");
  awka_varinit(_lits37_awka); awka_strcpy(_lits37_awka, "static");
  awka_varinit(_lits38_awka); awka_strcpy(_lits38_awka, "dynamic");
  awka_varinit(_lits39_awka); awka_strcpy(_lits39_awka, "%s:%d: propeller pragma specifies invalid memory management\n");
  awka_varinit(_lits40_awka); awka_strcpy(_lits40_awka, "threads");
  awka_varinit(_lits41_awka); awka_strcpy(_lits41_awka, "(");
  awka_varinit(_lits42_awka); awka_strcpy(_lits42_awka, "memory");
  awka_varinit(_lits43_awka); awka_strcpy(_lits43_awka, "%s:%d: propeller pragma specifies conflicting memory management\n");
  awka_varinit(_lits44_awka); awka_strcpy(_lits44_awka, "if");
  awka_varinit(_lits45_awka); awka_strcpy(_lits45_awka, "ticks");
  awka_varinit(_lits46_awka); awka_strcpy(_lits46_awka, "factory");
  awka_varinit(_lits47_awka); awka_strcpy(_lits47_awka, "foreman");
  awka_varinit(_lits48_awka); awka_strcpy(_lits48_awka, "local");
  awka_varinit(_lits49_awka); awka_strcpy(_lits49_awka, "output");
  awka_varinit(_lits50_awka); awka_strcpy(_lits50_awka, "worker");
  awka_varinit(_lits51_awka); awka_strcpy(_lits51_awka, "void");
  awka_varinit(_lits52_awka); awka_strcpy(_lits52_awka, "stack");
  awka_varinit(_lits53_awka); awka_strcpy(_lits53_awka, "cogs");
  awka_varinit(_lits54_awka); awka_strcpy(_lits54_awka, ")");
  awka_varinit(_lits55_awka); awka_strcpy(_lits55_awka, "%s:%d: propeller pragma contains malformed option '%s'\n");
  awka_varinit(_lits56_awka); awka_strcpy(_lits56_awka, "	");
  awka_varinit(_litr0_awka); awka_strcpy(_litr0_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+worker[[:blank:]]*$/"); awka_getre(_litr0_awka);
  awka_varinit(_litr1_awka); awka_strcpy(_litr1_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+worker[[:blank:]]*\\(/"); awka_getre(_litr1_awka);
  awka_varinit(_litr2_awka); awka_strcpy(_litr2_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+worker[[:blank:]]*[^\\(]/"); awka_getre(_litr2_awka);
  awka_varinit(_litr3_awka); awka_strcpy(_litr3_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+factory/"); awka_getre(_litr3_awka);
  awka_varinit(_litr4_awka); awka_strcpy(_litr4_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+begin/"); awka_getre(_litr4_awka);
  awka_varinit(_litr5_awka); awka_strcpy(_litr5_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+end/"); awka_getre(_litr5_awka);
  awka_varinit(_litr6_awka); awka_strcpy(_litr6_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+exclusive/"); awka_getre(_litr6_awka);
  awka_varinit(_litr7_awka); awka_strcpy(_litr7_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+shared/"); awka_getre(_litr7_awka);
  awka_varinit(_litr8_awka); awka_strcpy(_litr8_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+wait/"); awka_getre(_litr8_awka);
  awka_varinit(_litr9_awka); awka_strcpy(_litr9_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+start/"); awka_getre(_litr9_awka);
  awka_varinit(_litr10_awka); awka_strcpy(_litr10_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+stop/"); awka_getre(_litr10_awka);
  awka_varinit(_litr11_awka); awka_strcpy(_litr11_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+lock/"); awka_getre(_litr11_awka);
  awka_varinit(_litr12_awka); awka_strcpy(_litr12_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+extern/"); awka_getre(_litr12_awka);
  awka_varinit(_litr13_awka); awka_strcpy(_litr13_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller[[:blank:]]+kernel/"); awka_getre(_litr13_awka);
  awka_varinit(_litr14_awka); awka_strcpy(_litr14_awka, "/^[[:blank:]]*#pragma[[:blank:]]+propeller/"); awka_getre(_litr14_awka);
  awka_varinit(_litr15_awka); awka_strcpy(_litr15_awka, "/^[[:blank:]]*#pragma/"); awka_getre(_litr15_awka);
  awka_varinit(_litr16_awka); awka_strcpy(_litr16_awka, ","); awka_getre(_litr16_awka);

  if (!_lvar) {
    malloc( &_lvar, 82 * sizeof(a_VAR *) );
    _lvar[0] = _litd0_awka;
    _lvar[1] = _litd1_awka;
    _lvar[2] = _litd2_awka;
    _lvar[3] = _litd3_awka;
    _lvar[4] = _litd4_awka;
    _lvar[5] = _litd5_awka;
    _lvar[6] = _litd6_awka;
    _lvar[7] = _lits0_awka;
    _lvar[8] = _lits1_awka;
    _lvar[9] = _lits2_awka;
    _lvar[10] = _lits3_awka;
    _lvar[11] = _lits4_awka;
    _lvar[12] = _lits5_awka;
    _lvar[13] = _lits6_awka;
    _lvar[14] = _lits7_awka;
    _lvar[15] = _lits8_awka;
    _lvar[16] = _lits9_awka;
    _lvar[17] = _lits10_awka;
    _lvar[18] = _lits11_awka;
    _lvar[19] = _lits12_awka;
    _lvar[20] = _lits13_awka;
    _lvar[21] = _lits14_awka;
    _lvar[22] = _lits15_awka;
    _lvar[23] = _lits16_awka;
    _lvar[24] = _lits17_awka;
    _lvar[25] = _lits18_awka;
    _lvar[26] = _lits19_awka;
    _lvar[27] = _lits20_awka;
    _lvar[28] = _lits21_awka;
    _lvar[29] = _lits22_awka;
    _lvar[30] = _lits23_awka;
    _lvar[31] = _lits24_awka;
    _lvar[32] = _lits25_awka;
    _lvar[33] = _lits26_awka;
    _lvar[34] = _lits27_awka;
    _lvar[35] = _lits28_awka;
    _lvar[36] = _lits29_awka;
    _lvar[37] = _lits30_awka;
    _lvar[38] = _lits31_awka;
    _lvar[39] = _lits32_awka;
    _lvar[40] = _lits33_awka;
    _lvar[41] = _lits34_awka;
    _lvar[42] = _lits35_awka;
    _lvar[43] = _lits36_awka;
    _lvar[44] = _lits37_awka;
    _lvar[45] = _lits38_awka;
    _lvar[46] = _lits39_awka;
    _lvar[47] = _lits40_awka;
    _lvar[48] = _lits41_awka;
    _lvar[49] = _lits42_awka;
    _lvar[50] = _lits43_awka;
    _lvar[51] = _lits44_awka;
    _lvar[52] = _lits45_awka;
    _lvar[53] = _lits46_awka;
    _lvar[54] = _lits47_awka;
    _lvar[55] = _lits48_awka;
    _lvar[56] = _lits49_awka;
    _lvar[57] = _lits50_awka;
    _lvar[58] = _lits51_awka;
    _lvar[59] = _lits52_awka;
    _lvar[60] = _lits53_awka;
    _lvar[61] = _lits54_awka;
    _lvar[62] = _lits55_awka;
    _lvar[63] = _lits56_awka;
    _lvar[64] = _litr0_awka;
    _lvar[65] = _litr1_awka;
    _lvar[66] = _litr2_awka;
    _lvar[67] = _litr3_awka;
    _lvar[68] = _litr4_awka;
    _lvar[69] = _litr5_awka;
    _lvar[70] = _litr6_awka;
    _lvar[71] = _litr7_awka;
    _lvar[72] = _litr8_awka;
    _lvar[73] = _litr9_awka;
    _lvar[74] = _litr10_awka;
    _lvar[75] = _litr11_awka;
    _lvar[76] = _litr12_awka;
    _lvar[77] = _litr13_awka;
    _lvar[78] = _litr14_awka;
    _lvar[79] = _litr15_awka;
    _lvar[80] = _litr16_awka;
    _lvar[81] = NULL;
  }

  malloc( &_gvar, 27 * sizeof(struct gvar_struct) );
  awka_initgvar(0, "line_no_awk", line_no_awk);
  awka_initgvar(1, "pragma_awk", pragma_awk);
  awka_initgvar(2, "n_awk", n_awk);
  awka_initgvar(3, "name_awk", name_awk);
  awka_initgvar(4, "worker_awk", worker_awk);
  awka_initgvar(5, "factory_awk", factory_awk);
  awka_initgvar(6, "foreman_awk", foreman_awk);
  awka_initgvar(7, "stack_awk", stack_awk);
  awka_initgvar(8, "lock_awk", lock_awk);
  awka_initgvar(9, "cogs_awk", cogs_awk);
  awka_initgvar(10, "threads_awk", threads_awk);
  awka_initgvar(11, "ticks_awk", ticks_awk);
  awka_initgvar(12, "local_awk", local_awk);
  awka_initgvar(13, "output_awk", output_awk);
  awka_initgvar(14, "when_awk", when_awk);
  awka_initgvar(15, "w_awk", w_awk);
  awka_initgvar(16, "vars_awk", vars_awk);
  awka_initgvar(17, "collecting_awk", collecting_awk);
  awka_initgvar(18, "collecting_name_awk", collecting_name_awk);
  awka_initgvar(19, "exclusive_awk", exclusive_awk);
  awka_initgvar(20, "excl_opt_awk", excl_opt_awk);
  awka_initgvar(21, "management_awk", management_awk);
  awka_initgvar(22, "reported_awk", reported_awk);
  awka_initgvar(23, "new_mgmt_awk", new_mgmt_awk);
  awka_initgvar(24, "j_awk", j_awk);
  awka_initgvar(25, "k_awk", k_awk);
  _gvar[26].name = NULL;
  _gvar[26].var  = NULL;

  malloc( &_awkafn, 9 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = "memory_management";
  _awkafn[0].fn   = memory_management_fn;
  _awkafn[1].name = "get_pragma_options";
  _awkafn[1].fn   = get_pragma_options_fn;
  _awkafn[2].name = "match_paren";
  _awkafn[2].fn   = match_paren_fn;
  _awkafn[3].name = "my_right";
  _awkafn[3].fn   = my_right_fn;
  _awkafn[4].name = "trim_parentheses";
  _awkafn[4].fn   = trim_parentheses_fn;
  _awkafn[5].name = "malformed_option";
  _awkafn[5].fn   = malformed_option_fn;
  _awkafn[6].name = "remove_chars";
  _awkafn[6].fn   = remove_chars_fn;
  _awkafn[7].name = "token";
  _awkafn[7].fn   = token_fn;
  _awkafn[8].name = NULL;
  _awkafn[8].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _split_max = 2147483647;
  _split_req = 1;
  _dol0_used = 1;

  BEGIN();
  MAIN();
  END();

  free(_litd0_awka);
  free(_litd1_awka);
  free(_litd2_awka);
  free(_litd3_awka);
  free(_litd4_awka);
  free(_litd5_awka);
  free(_litd6_awka);
  free(_lits0_awka->ptr); free(_lits0_awka);
  free(_lits1_awka->ptr); free(_lits1_awka);
  free(_lits2_awka->ptr); free(_lits2_awka);
  free(_lits3_awka->ptr); free(_lits3_awka);
  free(_lits4_awka->ptr); free(_lits4_awka);
  free(_lits5_awka->ptr); free(_lits5_awka);
  free(_lits6_awka->ptr); free(_lits6_awka);
  free(_lits7_awka->ptr); free(_lits7_awka);
  free(_lits8_awka->ptr); free(_lits8_awka);
  free(_lits9_awka->ptr); free(_lits9_awka);
  free(_lits10_awka->ptr); free(_lits10_awka);
  free(_lits11_awka->ptr); free(_lits11_awka);
  free(_lits12_awka->ptr); free(_lits12_awka);
  free(_lits13_awka->ptr); free(_lits13_awka);
  free(_lits14_awka->ptr); free(_lits14_awka);
  free(_lits15_awka->ptr); free(_lits15_awka);
  free(_lits16_awka->ptr); free(_lits16_awka);
  free(_lits17_awka->ptr); free(_lits17_awka);
  free(_lits18_awka->ptr); free(_lits18_awka);
  free(_lits19_awka->ptr); free(_lits19_awka);
  free(_lits20_awka->ptr); free(_lits20_awka);
  free(_lits21_awka->ptr); free(_lits21_awka);
  free(_lits22_awka->ptr); free(_lits22_awka);
  free(_lits23_awka->ptr); free(_lits23_awka);
  free(_lits24_awka->ptr); free(_lits24_awka);
  free(_lits25_awka->ptr); free(_lits25_awka);
  free(_lits26_awka->ptr); free(_lits26_awka);
  free(_lits27_awka->ptr); free(_lits27_awka);
  free(_lits28_awka->ptr); free(_lits28_awka);
  free(_lits29_awka->ptr); free(_lits29_awka);
  free(_lits30_awka->ptr); free(_lits30_awka);
  free(_lits31_awka->ptr); free(_lits31_awka);
  free(_lits32_awka->ptr); free(_lits32_awka);
  free(_lits33_awka->ptr); free(_lits33_awka);
  free(_lits34_awka->ptr); free(_lits34_awka);
  free(_lits35_awka->ptr); free(_lits35_awka);
  free(_lits36_awka->ptr); free(_lits36_awka);
  free(_lits37_awka->ptr); free(_lits37_awka);
  free(_lits38_awka->ptr); free(_lits38_awka);
  free(_lits39_awka->ptr); free(_lits39_awka);
  free(_lits40_awka->ptr); free(_lits40_awka);
  free(_lits41_awka->ptr); free(_lits41_awka);
  free(_lits42_awka->ptr); free(_lits42_awka);
  free(_lits43_awka->ptr); free(_lits43_awka);
  free(_lits44_awka->ptr); free(_lits44_awka);
  free(_lits45_awka->ptr); free(_lits45_awka);
  free(_lits46_awka->ptr); free(_lits46_awka);
  free(_lits47_awka->ptr); free(_lits47_awka);
  free(_lits48_awka->ptr); free(_lits48_awka);
  free(_lits49_awka->ptr); free(_lits49_awka);
  free(_lits50_awka->ptr); free(_lits50_awka);
  free(_lits51_awka->ptr); free(_lits51_awka);
  free(_lits52_awka->ptr); free(_lits52_awka);
  free(_lits53_awka->ptr); free(_lits53_awka);
  free(_lits54_awka->ptr); free(_lits54_awka);
  free(_lits55_awka->ptr); free(_lits55_awka);
  free(_lits56_awka->ptr); free(_lits56_awka);
  awka_killvar(_litr0_awka); free(_litr0_awka);
  awka_killvar(_litr1_awka); free(_litr1_awka);
  awka_killvar(_litr2_awka); free(_litr2_awka);
  awka_killvar(_litr3_awka); free(_litr3_awka);
  awka_killvar(_litr4_awka); free(_litr4_awka);
  awka_killvar(_litr5_awka); free(_litr5_awka);
  awka_killvar(_litr6_awka); free(_litr6_awka);
  awka_killvar(_litr7_awka); free(_litr7_awka);
  awka_killvar(_litr8_awka); free(_litr8_awka);
  awka_killvar(_litr9_awka); free(_litr9_awka);
  awka_killvar(_litr10_awka); free(_litr10_awka);
  awka_killvar(_litr11_awka); free(_litr11_awka);
  awka_killvar(_litr12_awka); free(_litr12_awka);
  awka_killvar(_litr13_awka); free(_litr13_awka);
  awka_killvar(_litr14_awka); free(_litr14_awka);
  awka_killvar(_litr15_awka); free(_litr15_awka);
  awka_killvar(_litr16_awka); free(_litr16_awka);

  awka_exit(0);
}
