#!/bin/bash
echo "" 
if [[ "$1" != "" ]]; then
   echo ""
   echo "Parameters not allowed when compiling for MORPHEUS"
   echo ""
elif [[ "$CATALINA_DEFINE" != "" ]]; then
   echo ""
   echo "NOTE: Environment variable CATALINA_DEFINE is set to $CATALINA_DEFINE"
   echo ""
   echo "CATALINA_DEFINE must not be set when compiling for MORPHEUS"
   echo ""
else
   TMP_LCCDIR=$LCCDIR
   if [[ "$TMP_LCCDIR" == "" ]]; then
      TMP_LCCDIR=/opt/catalina	
   fi
   #
   if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
      echo ""
      echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
      echo "";
      echo "Set the environment variable LCCDIR to where Catalina is installed.";
      echo "";
      exit
   fi   
   #
   # dummy program to stop one CPU interfering while we load the other
   catalina null.c -C NO_HMI
   #
   # example running on CPU #1
   catalina debug_main.c debug_functions_1.c debug_functions_2.c -lci -g3 -o example_client_1 -C MORPHEUS -C CPU_1 -C PROXY_SCREEN
   #
   # proxy running on CPU #2 providing access to screen
   spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o example_server_2 -b -D MORPHEUS -D CPU_2 -D NO_KEYBOARD -D NO_MOUSE
   echo ""
fi
