include ../Makefile.inc

all: memchr.s memcmp.s memcpy.s memmove.s memset.s strcat.s \
	strchr.s strcmp.s strcoll.s strcpy.s strcspn.s strerror.s \
	strncat.s strncpy.s strrchr.s strstr.s strlen.s strtok.s \
	strpbrk.s strspn.s strncmp.s strxfrm.s 

clean:
	-rm -f memchr.s memcmp.s memcpy.s memmove.s memset.s strcat.s \
		strchr.s strcmp.s strcoll.s strcpy.s strcspn.s strerror.s \
		strncat.s strncpy.s strrchr.s strstr.s strlen.s strtok.s \
		strpbrk.s strspn.s strncmp.s strxfrm.s OLIST
