//This was generated by running cake -autoconfig 
//This file was generated reading the variable LCCDIR inside a Catalina command line window.
#pragma dir "C:/Users/rossh/Catalina_Work_64/include/"
#define __CATALINA__
