#!/bin/bash
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: Environment variable CATALINA_DEFINE is set (to $CATALINA_DEFINE)"
   echo ""
   echo "You must undefine this environment variable before using this batch"
   echo "file, and instead specify the target and options on the command line."
   echo "";
   exit
elif [[ "$1" ==  "" ]] ; then
   echo ""
   echo "ERROR: no PLATFORM specified !"
   echo ""
   echo "usage: build_all PLATFORM"
   echo ""
   echo "   where  PLATFORM is HYDRA, HYBRID, RAMBLADE, TRIBLADEPROP, DRACBLADE,"
   echo "                      DEMO CUSTOM, or P2_EVAL (P2 only)"
   echo "   and    OPTIONS are other Catalina options (e.g. CPU_1, HIRES_TV, NTSC)"
   echo ""
   exit
else
   echo ""
   echo "   =================="
   echo "   Building Pascal P5"
   echo "   =================="
   echo ""

   CATALINA_DEFINE="$1 $2 $3 $4 $5 $6 $7 $8 $9"; export CATALINA_DEFINE

   platform=$1
   if [ "${platform:0:2}" == "P2" ]; then 

      catalina -p2 catalina_pcom.c -lcx -I../ptoc ../ptoc/paslib.c ../ptoc/set.c ../ptoc/io.c -C NATIVE -lma -o pcom
      catalina -p2 catalina_pint.c -lcx -I../ptoc ../ptoc/paslib.c ../ptoc/set.c ../ptoc/io.c -C NATIVE -lma -o pint
   
   else

      catalina catalina_pcom.c -lcx -I../ptoc ../ptoc/paslib.c ../ptoc/set.c ../ptoc/io.c -C LARGE -lma -o pcom
      catalina catalina_pint.c -lcx -I../ptoc ../ptoc/paslib.c ../ptoc/set.c ../ptoc/io.c -C LARGE -lma -o pint
   
   fi

   unset CATALINA_DEFINE

fi
