#!/bin/bash

if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: Environment variable CATALINA_DEFINE is set (to $CATALINA_DEFINE)"
   echo ""
   echo "You must undefine this environment variable before using this"
   echo "batch file."
   echo "";
   exit
elif [[ "$1" !=  "" ]] ; then
   echo ""
   echo "ERROR: Command line parameters are not supported."
   echo ""
   echo "usage: build_triblade_utilities"
   echo ""
   exit
else
   #
   TMP_LCCDIR=$LCCDIR
   if [[ "$TMP_LCCDIR" == "" ]]; then
      TMP_LCCDIR=/opt/catalina	
   fi
   #
   if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
      echo ""
      echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
      echo "";
      echo "Set the environment variable LCCDIR to where Catalina is installed.";
      echo "";
      exit
   fi   
   echo ""
   echo "   =================="
   echo "   Building Utilities"
   echo "   =================="
   echo ""
fi

# delete old utilities
rm -f *.binary

# build utilities for specific platform

# build programs intended to run on CPU #1
# NOTE: this proxy will support the keyboard, mouse or screen
#       (for programs executed on another CPU)
source build_pasm_tmp_var TRIBLADEPROP CPU_1 NO_SD
spinnaker -p -a Generic_Proxy_Server.spin -I "$TMP_LCCDIR/target/p1" -o Generic_Proxy_Server_1 -b $TMP_VAR
echo ""
spinnaker -p -a Generic_SIO_Loader_1.spin -I "$TMP_LCCDIR/target/p1" -b $TMP_VAR 
echo ""
spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target/p1" -b -o XMM_1 $TMP_VAR
echo ""
spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target/p1" -b -o EEPROM_1 $TMP_VAR
echo ""
# build programs intended to run on CPU #3
source build_pasm_tmp_var TRIBLADEPROP CPU_3
spinnaker -p -a Generic_SIO_Loader_3.spin -I "$TMP_LCCDIR/target/p1" -b $TMP_VAR
echo ""
# build programs intended to run on CPU #2 (do these last)
# NOTE: this proxy will support the SD card 
#       (for programs running on another CPU), but we also
#       specify a PC HMI device, which allows us to proxy
#       programs running on any other CPU to the PC.
source build_pasm_tmp_var TRIBLADEPROP CPU_2 PC
spinnaker -p -a Generic_Proxy_Server.spin -I "$TMP_LCCDIR/target/p1" -o Generic_Proxy_Server_2 -b $TMP_VAR
echo ""
spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target/p1" -b -o XMM_2 $TMP_VAR
echo ""
spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target/p1" -b -o EEPROM_2 $TMP_VAR
echo ""
spinnaker -p -a CPU_1_Boot.spin -o CPU_1_Boot_2 -I "$TMP_LCCDIR/target/p1" -b $TMP_VAR
spinnaker -p -a CPU_3_Boot.spin -o CPU_3_Boot_2 -I "$TMP_LCCDIR/target/p1" -b $TMP_VAR
echo ""
spinnaker -p -a CPU_1_Reset.spin -o CPU_1_Reset_2 -I "$TMP_LCCDIR/target/p1" -b $TMP_VAR
spinnaker -p -a CPU_3_Reset.spin -o CPU_3_Reset_2 -I "$TMP_LCCDIR/target/p1" -b $TMP_VAR

cp *.binary "$TMP_LCCDIR/bin"
