#!/bin/bash

if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: Environment variable CATALINA_DEFINE is set (to $CATALINA_DEFINE)"
   echo ""
   echo "You must undefine this environment variable before using this"
   echo "batch file."
   echo "";
   exit
elif [[ "$1" !=  "" ]] ; then
   echo ""
   echo "ERROR: Command line parameters are not supported."
   echo ""
   echo "usage: build_morpheus_utilities"
   echo ""
   exit
else
   #
   TMP_LCCDIR=$LCCDIR
   if [[ "$TMP_LCCDIR" == "" ]]; then
      TMP_LCCDIR=/opt/catalina	
   fi
   #
   if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
      echo ""
      echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
      echo "";
      echo "Set the environment variable LCCDIR to where Catalina is installed.";
      echo "";
      exit
   fi   
   echo ""
   echo "   =================="
   echo "   Building Utilities"
   echo "   =================="
   echo ""
fi

# delete old utilities
rm -f *.binary

# build utilities for specific platformx

# build programs intended to run on CPU #2
# NOTE: this proxy support the screen (for programs executed on CPU #1)
source build_pasm_tmp_var MORPHEUS CPU_2 NO_KEYBOARD NO_MOUSE NO_SD
spinnaker -p -a Generic_Proxy_Server.spin -I "$TMP_LCCDIR/target" -o Generic_Proxy_2 -b $TMP_VAR
echo ""
spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM_2 $TMP_VAR
echo ""
spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM_2 $TMP_VAR
echo ""
spinnaker -p -a Generic_SIO_Loader_2.spin -I "$TMP_LCCDIR/target" -b $TMP_VAR 
# build programs intended to run on CPU #1 (do these last)
# NOTE: this proxy will support the keyboard, mouse or SD card
#       (for programs executed on CPU #2)
source build_pasm_tmp_var MORPHEUS CPU_1 NO_SCREEN 
spinnaker -p -a Generic_Proxy_Server.spin -I "$TMP_LCCDIR/target" -o Generic_Proxy_1 -b $TMP_VAR
echo ""
spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM_1 $TMP_VAR
echo ""
spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM_1 $TMP_VAR
echo ""
spinnaker -p -a CPU_2_Boot.spin -o CPU_2_Boot_1 -I "$TMP_LCCDIR/target" -b $TMP_VAR
echo ""
spinnaker -p -a CPU_2_Reset.spin -o CPU_2_Reset_1 -I "$TMP_LCCDIR/target" -b $TMP_VAR
source build_pasm_tmp_var MORPHEUS PC CPU_1 SMALL
spinnaker -p -a "$TMP_LCCDIR/target/xmm_default.spin" -I "$TMP_LCCDIR/target" -b $TMP_VAR -o Flash_Boot

cp *.binary "$TMP_LCCDIR/bin"
