#!/bin/bash
echo ""
echo "  NOTE: The use of this batch file is deprecated, and may be removed"
echo "        from a subsequent release - use 'build_utilities' instead!"
echo ""

if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: Environment variable CATALINA_DEFINE is set (to $CATALINA_DEFINE)"
   echo ""
   echo "You must undefine this environment variable before using this"
   echo "batch file, and instead specify the target on the command line."
   echo "";
   exit
elif [[ "$1" ==  "" ]] ; then
   echo ""
   echo "ERROR: no PLATFORM specified !"
   echo ""
   echo "usage: build_all PLATFORM [ OPTIONS ]"
   echo ""
   echo "  where PLATFORM is:"
   echo ""
   echo "                 HYDRA, HYBRID, MORPHEUS, TRIBLADEPROP, SUPERQUAD,"
   echo "                 RAMPAGE, DRACBLADE, RAMBLADE, DEMO, C3, CUSTOM"
   echo ""
   echo "  and OPTIONS can include:"
   echo ""
   echo "                 Any Catalina target options (e.g. TV, SD, CLOCK) needed"
   echo "                 to configure which plugins will be loaded by Flash_Boot"
   echo "                 utility, as well as options to configure the various "
   echo "                 load utilities, such as:"
   echo ""
   echo "                 FLASH, WRITE_CHECK, ERASE_CHECK, CHIP_ERASE"
   echo "                 CACHED, CACHED_1K, CACHED_2K, CACHED_4K, CACHED_8K"
   echo ""
   exit
else
   #
   TMP_LCCDIR=$LCCDIR
   if [[ "$TMP_LCCDIR" == "" ]]; then
      TMP_LCCDIR=/opt/catalina	
   fi
   #
   if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
      echo ""
      echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
      echo "";
      echo "Set the environment variable LCCDIR to where Catalina is installed.";
      echo "";
      exit
   fi   
   echo ""
   echo "   =================="
   echo "   Building Utilities"
   echo "   =================="
   echo ""
fi

# delete old utilities
rm -f *.binary

# build utilities for specific platforms (if any)
if [[ "$1" ==  "C3" ]] ; then
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 $8 SMALL
   spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM $TMP_VAR
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM $TMP_VAR
   spinnaker -p -a "$TMP_LCCDIR/target/xmm_default.spin" -I "$TMP_LCCDIR/target" -b $TMP_VAR -o Flash_Boot

elif [[ "$1" ==  "SUPERQUAD" ]] ; then
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 $8 SMALL
   spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM $TMP_VAR
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM $TMP_VAR
   spinnaker -p -a "$TMP_LCCDIR/target/xmm_default.spin" -I "$TMP_LCCDIR/target" -b $TMP_VAR -o Flash_Boot

elif [[ "$1" ==  "RAMPAGE" ]] ; then
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 $8 SMALL
   spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM $TMP_VAR
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM $TMP_VAR
   spinnaker -p -a "$TMP_LCCDIR/target/xmm_default.spin" -I "$TMP_LCCDIR/target" -b $TMP_VAR -o Flash_Boot

elif [[ "$1" ==  "MORPHEUS" ]] ; then
   # build programs intended to run on CPU #2
   # NOTE: this proxy support the screen (for programs executed on CPU #1)
   source build_pasm_tmp_var $1 $2 $3 $4 $5 CPU_2 NO_KEYBOARD NO_MOUSE NO_SD
   spinnaker -p -a Generic_Proxy_Server.spin -I "$TMP_LCCDIR/target" -o Generic_Proxy_2 -b $TMP_VAR
   echo ""
   spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM_2 $TMP_VAR
   echo ""
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM_2 $TMP_VAR
   echo ""
   spinnaker -p -a Generic_SIO_Loader_2.spin -I "$TMP_LCCDIR/target" -b $TMP_VAR 
   # build programs intended to run on CPU #1 (do these last)
   # NOTE: this proxy will support the keyboard, mouse or SD card
   #       (for programs executed on CPU #2)
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 CPU_1 NO_SCREEN 
   spinnaker -p -a Generic_Proxy_Server.spin -I "$TMP_LCCDIR/target" -o Generic_Proxy_1 -b $TMP_VAR
   echo ""
   spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM_1 $TMP_VAR
   echo ""
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM_1 $TMP_VAR
   echo ""
   spinnaker -p -a CPU_2_Boot.spin -o CPU_2_Boot_1 -I "$TMP_LCCDIR/target" -b $TMP_VAR
   echo ""
   spinnaker -p -a CPU_2_Reset.spin -o CPU_2_Reset_1 -I "$TMP_LCCDIR/target" -b $TMP_VAR
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 PC CPU_1 SMALL
   spinnaker -p -a "$TMP_LCCDIR/target/xmm_default.spin" -I "$TMP_LCCDIR/target" -b $TMP_VAR -o Flash_Boot

elif [[ "$1" ==  "TRIBLADEPROP" ]] ; then
   # build programs intended to run on CPU #1
   # NOTE: this proxy will support the keyboard, mouse or screen
   #       (for programs executed on another CPU)
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 CPU_1 NO_SD
   spinnaker -p -a Generic_Proxy_Server.spin -I "$TMP_LCCDIR/target" -o Generic_Proxy_Server_1 -b $TMP_VAR
   echo ""
   spinnaker -p -a Generic_SIO_Loader_1.spin -I "$TMP_LCCDIR/target" -b $TMP_VAR 
   echo ""
   spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM_1 $TMP_VAR
   echo ""
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM_1 $TMP_VAR
   echo ""
   # build programs intended to run on CPU #3
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 $8 CPU_3
   spinnaker -p -a Generic_SIO_Loader_3.spin -I "$TMP_LCCDIR/target" -b $TMP_VAR
   echo ""
   # build programs intended to run on CPU #2 (do these last)
   # NOTE: this proxy will support the SD card 
   #       (for programs running on another CPU), but we also
   #       specify a PC HMI device, which allows us to proxy
   #       programs running on any other CPU to the PC.
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 CPU_2 PC
   spinnaker -p -a Generic_Proxy_Server.spin -I "$TMP_LCCDIR/target" -o Generic_Proxy_Server_2 -b $TMP_VAR
   echo ""
   spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM_2 $TMP_VAR
   echo ""
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM_2 $TMP_VAR
   echo ""
   spinnaker -p -a CPU_1_Boot.spin -o CPU_1_Boot_2 -I "$TMP_LCCDIR/target" -b $TMP_VAR
   spinnaker -p -a CPU_3_Boot.spin -o CPU_3_Boot_2 -I "$TMP_LCCDIR/target" -b $TMP_VAR
   echo ""
   spinnaker -p -a CPU_1_Reset.spin -o CPU_1_Reset_2 -I "$TMP_LCCDIR/target" -b $TMP_VAR
   spinnaker -p -a CPU_3_Reset.spin -o CPU_3_Reset_2 -I "$TMP_LCCDIR/target" -b $TMP_VAR

elif [[ "$1" ==  "HYBRID" ]] ; then
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 $8 $9
   spinnaker -p -a Mouse_Port_Loader.spin -I "$TMP_LCCDIR/target" -b -o Hybrid_Mouse $TMP_VAR
   cp Hybrid_Mouse.binary XMM.binary
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM $TMP_VAR

elif [[ "$1" ==  "HYDRA" ]] ; then
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 $8 $9
   spinnaker -p -a Mouse_Port_Loader.spin -I "$TMP_LCCDIR/target" -b -o Hydra_Mouse $TMP_VAR
   cp Hydra_Mouse.binary XMM.binary
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM $TMP_VAR
else
   source build_pasm_tmp_var $1 $2 $3 $4 $5 $6 $7 $8 $9
   spinnaker -p -a Payload_XMM_Loader.spin -I "$TMP_LCCDIR/target" -b -o XMM $TMP_VAR
   spinnaker -p -a Payload_EEPROM_Loader.spin -I "$TMP_LCCDIR/target" -b -o EEPROM $TMP_VAR
fi

cp *.binary "$TMP_LCCDIR/bin"
