/* config.h -- generated by configure */
#ifndef CONFIG_H
#define CONFIG_H

#define HAVE_UNISTD_H
#define HAVE_FCNTL_H

#define awka_MATHLIB "-lm"
#define INLINE __inline__
#define SIZE_T_STDDEF_H 1
#define NO_NETDB_H 1
#define NO_MATHERR 1
#define NO_FPRINTF_IN_STDIO 1
#define NO_SPRINTF_IN_STDIO 1
#define awka_SOCKET_LIBS ""
#define awka_CC "gcc"
#define awka_CFLAGS "-g -O2"
#define awka_shell "ash"

#define HAVE_FORK 0
#define HAVE_REAL_PIPES 0
/* #define NO_BIN_CHARS */
/* #define MEM_DEBUG */
#endif /* CONFIG_H */
