#!//bin/bash
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: Environment variable CATALINA_DEFINE is set (to $CATALINA_DEFINE)"
   echo ""
   echo "You must undefine this environment variable before using this"
   echo "batch file, and instead specify the target on the command line."
   echo "";
elif [[ "$1" ==  "" ]] ; then
   echo ""
   echo "ERROR: no PLATFORM specified !"
   echo ""
   echo "usage: build_all PLATFORM"
   echo ""
   echo "   where  PLATFORM is HYDRA, HYBRID, RAMBLADE, TRIBLADEPROP, DRACBLADE,"
   echo "                      DEMO, CUSTOM or P2_EVAL (P2 only)"
   echo "   and    OPTIONS are other Catalina options (e.g. CPU_1, HIRES_TV, NTSC)"
   echo "   (Remember to specify both PC and VT100 if you want to use the PC HMI!)"
   echo ""
   exit
else
   echo ""
   echo "   ========================"
   echo "   Building Super Star Trek"
   echo "   ========================"
   echo ""

   CATALINA_DEFINE="$1 $2 $3 $4 $5 $6 $7 $8 $9"; export CATALINA_DEFINE

   platform=$1

   if [ "${platform:0:2}" != "P2" ]; then 

      rm -fr *.binary
      catalina sst.c ai.c battle.c catalina.c events.c finish.c moving.c planets.c reports.c setup.c -lcx -C LARGE -lma
      unset CATALINA_DEFINE

   else

      rm -fr *.bin
      catalina -p2 -C NATIVE sst.c ai.c battle.c catalina.c events.c finish.c moving.c planets.c reports.c setup.c -lcx -lma
      unset CATALINA_DEFINE

   fi

fi
