#!/bin/bash
#set -x
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]] ; then
   TMP_LCCDIR=/opt/catalina
fi
#
if [[ ! -e "$TMP_LCCDIR/bin/catalina_env" ]] ; then
   clear
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi
#
if [[ "$1" != "" ]]; then

   if [[ "$CATALINA_DEFINE" != "" ]]; then

      if [[ "$CATALINA_DEFINE" != "$1 $2 $3 $4 $5 $6 $7 $8 $9" ]]; then

         echo ""
         echo "ERROR: Command line options conflict with CATALINA_DEFINE"
         echo ""
         echo "   The Environment variable CATALINA_DEFINE is set to $CATALINA_DEFINE"
         echo "   The Command line options specified are $1 $2 $3 $4 $5 $6 $7 $8 $9"
         echo ""
         echo "   Either set CATALINA_DEFINE to null using the following command:"
         echo ""
         echo "      unset CATALINA_DEFINE"
         echo ""
         echo "   or do not specify any command line parameters"
         echo ""

      else

         echo ""
         echo "NOTE: Environment variable CATALINA_DEFINE is set to $CATALINA_DEFINE"
         echo ""
         echo "All programs will be built using these options. If these options conflict" 
         echo "with any options specified in this file, the results may be unexpected." 
         
      fi

   else

      echo ""
      echo "NOTE: Environment variable CATALINA_DEFINE will be set to $1 $2 $3 $4 $5 $6 $7 $8 $9"
      echo ""
      echo "All programs will be built using these options. If these options conflict"
      echo "with any options specified in this file, the results may be unexpected."
      CATALINA_DEFINE="$1 $2 $3 $4 $5 $6 $7 $8 $9"; export CATALINA_DEFINE

   fi

else

   if [[ "$CATALINA_DEFINE" != "" ]]; then

      echo ""
      echo "NOTE: Environment variable CATALINA_DEFINE is set to $CATALINA_DEFINE"
      echo ""
      echo "All programs will be built using these options. If these options conflict" 
      echo "with any options specified in this file, the results may be unexpected." 
  
   else     

      echo ""
      echo "NOTE: Environment variable CATALINA_DEFINE is not set"
      echo ""
      echo "All programs will be built for the default target (CUSTOM)" 

   fi

fi

echo "";

platform=$1
if [ "${platform:0:2}" != "P2" ]; then 

   #
   # Demo 1 : Run "Hello World" at a fixed address
   # =============================================
   #
   # Compile the primary program to run the subsidiary programs
   # at a fixed Hub Address (0x4000).
   # 
   # Compile CMM, LMM, XMM SMALL and XMM LARGE versions of this program.
   #
   catalina hello_world.c -lci -R 0x4000 -C NO_ARGS
   spinc -B2 -n LMM -c -l hello_world.binary >hello_world_lmm.inc
   catalina hello_world.c -lci -R 0x4000 -C NO_ARGS -C COMPACT
   spinc -B2 -n CMM -c -l hello_world.binary >hello_world_cmm.inc
   catalina run_hello_world.c -lci -o hello_lmm
   catalina run_hello_world.c -lci -C COMPACT -o hello_cmm
   catalina run_hello_world.c -lci -C SMALL -C CACHED_1K -o hello_small
   catalina run_hello_world.c -lci -C LARGE -C CACHED_1K -o hello_large
   #
   # Demo 2 : Run "Hello World" at a reserved address
   # ================================================
   #
   # Compile a primary program that runs the subsidiary programs in
   # an area of Hub RAM reserved in the main function.
   #
   # Only compile an LMM version of the primary program.
   #
   # Edit the -R values if instructed to do so by the program.
   #
   catalina hello_world.c -lci -R 0x7BAC -M64k -C NO_ARGS 
   spinc -B2 -n LMM -c -l hello_world.binary >hello_world_lmm.inc
   catalina hello_world.c -lci -R 0x7BAC -M64k -C NO_ARGS -C COMPACT
   spinc -B2 -n CMM -c -l hello_world.binary >hello_world_cmm.inc
   catalina run_reserved.c -o hello_reserved -lci
   #
   # Demo 3 : Run two subsidiary programs at different reserved addresses
   # ====================================================================
   #
   # Compile a primary program that runs two subsidiary programs in
   # areas of Hub RAM reserved in the main function.
   #
   # We compile CMM, LMM, XMM SMALL & XNM LARGE versions of the primary program.
   #
   # Edit the -R values if instructed to do so by the primary program.
   #
   catalina subsidiary_1.c -lc -lmb -R 0x71DC -M64k -C NO_ARGS -C COMPACT
   spinc -B2 -n SUB1 -s 200 -c -l subsidiary_1.binary >subsidiary_1.inc
   catalina subsidiary_2.c -lc -lmb -R 0x5C44 -M64k -C NO_ARGS 
   spinc -B2 -n SUB2 -s 200 -c -l subsidiary_2.binary >subsidiary_2.inc
   catalina primary.c -lc -lmb -o primary_lmm
   catalina primary.c -lc -lmb -C COMPACT -o primary_cmm
   #
   catalina subsidiary_1.c -lc -lmb -R 0x68A0 -M64k -C NO_ARGS -C COMPACT
   spinc -B2 -n SUB1 -s 200 -c -l subsidiary_1.binary >subsidiary_1.inc
   catalina subsidiary_2.c -lc -lmb -R 0x5308 -M64k -C NO_ARGS 
   spinc -B2 -n SUB2 -s 200 -c -l subsidiary_2.binary >subsidiary_2.inc
   catalina primary.c -lc -lmb -C SMALL -C CACHED_1K -o primary_small
   catalina primary.c -lc -lmb -C LARGE -C CACHED_1K -o primary_large
   #
   # Demo 4 : Run "Dining Philosophers" at a fixed address
   # =====================================================
   #
   # Compile the primary program to run the subsidiary programs
   # at a fixed Hub Address (0x3000).
   # 
   # Compile only an XMM LARGE version of the primary program.
   #
   catalina dining_philosophers.c -lci -lthreads -R 0x3000 -C NO_ARGS
   spinc -B2 -n LMM -s 8000 -c -f _threaded_cogstart_LMM_cog -l dining_philosophers.binary >dining_philosophers_lmm.inc
   catalina dining_philosophers.c -lci -lthreads -R 0x3000 -C NO_ARGS -C COMPACT
   spinc -B2 -n CMM -s 8000 -c -l dining_philosophers.binary >dining_philosophers_cmm.inc
   catalina run_dining_philosophers.c -lci -C LARGE -C CACHED_1K -o run_diners_xmm
   #
   # Demo 5 : Run "Dining Philosophers" from an overlay file
   # =======================================================
   #
   # Compile the primary program to run the subsidiary programs
   # from an overlay file at a fixed Hub Address (0x3000).
   # 
   # Compile only an XMM LARGE version of the primary program.
   #
   catalina dining_philosophers.c -lci -lthreads -R 0x3000 -C NO_ARGS
   spinc -B2 -n LMM -s 8000 -c -l dining_philosophers.binary -o diners.lmm >dining_philosophers_lmm.inc
   catalina dining_philosophers.c -lci -lthreads -R 0x3000 -C NO_ARGS -C COMPACT
   spinc -B2 -n CMM -s 8000 -c -l dining_philosophers.binary -o diners.cmm >dining_philosophers_cmm.inc
   catalina run_dining_philosophers.c -lcix -C LARGE -C CACHED_1K -o run_xmm

else

   #
   #   =================
   #   BUILDING P2 DEMOS
   #   =================
   #
   # Demo 1 : Run "Hello World" at a fixed address
   # =============================================
   #
   # Compile the primary program to run the subsidiary programs
   # at a fixed Hub Address (0x40000).
   # 
   # Compile CMM, LMM and NMM versions of the primary program.
   #
   catalina -p2 hello_world.c -lci -R 0x40000 -C NO_ARGS
   spinc -p2 -B2 -n LMM -c -l hello_world.bin >hello_world_lmm.inc
   catalina -p2 hello_world.c -lci -R 0x40000 -C NO_ARGS -C COMPACT
   spinc -p2 -B2 -n CMM -c -l hello_world.bin >hello_world_cmm.inc
   catalina -p2 hello_world.c -lci -R 0x40000 -C NO_ARGS -C NATIVE
   spinc -p2 -B2 -n NMM -c -l hello_world.bin >hello_world_nmm.inc
   catalina -p2 run_hello_world.c -lci -o hello_lmm
   catalina -p2 run_hello_world.c -lci -C COMPACT -o hello_cmm
   catalina -p2 run_hello_world.c -lci -C NATIVE -o hello_nmm
   #
   # Demo 2 : Run "Hello World" at a reserved address
   # ================================================
   #
   # Compile a primary program that runs the subsidiary programs in
   # an area of Hub RAM reserved in the main function.
   #
   # Only compile a Native (NMM) version of the primary program.
   #
   # Edit the -R values if instructed to do so by the program.
   #
   catalina -p2 hello_world.c -lci -R 0x7BB5C -C NO_ARGS 
   spinc -p2 -B2 -n LMM -c -l hello_world.bin >hello_world_lmm.inc
   catalina -p2 hello_world.c -lci -R 0x7BB5C -C NO_ARGS -C COMPACT
   spinc -p2 -B2 -n CMM -c -l hello_world.bin >hello_world_cmm.inc
   catalina -p2 run_reserved.c -o hello_reserved -lci -C NATIVE 
   #
   # Demo 3 : Run two subsidiary programs at different reserved addresses
   # ====================================================================
   #
   # Compile a primary program that runs two subsidiary programs in
   # areas of Hub RAM reserved in the main function.
   #
   # We compile CMM, LMM and NMM versions of the primary program.
   #
   # Edit the -R values if instructed to do so by the primary program.
   #
   catalina -p2 subsidiary_1.c -lc -lmb -R 0x78184 -C NO_ARGS -C COMPACT
   spinc -p2 -B2 -n SUB1 -s 200 -c -l subsidiary_1.bin >subsidiary_1.inc
   catalina -p2 subsidiary_2.c -lc -lmb -R 0x73BD8 -C NO_ARGS 
   spinc -p2 -B2 -n SUB2 -s 200 -c -l subsidiary_2.bin >subsidiary_2.inc
   catalina -p2 primary.c -lc -lmb -C COMPACT -o primary_cmm
   #
   catalina -p2 subsidiary_1.c -lc -lmb -R 0x7818C -C NO_ARGS -C COMPACT
   spinc -p2 -B2 -n SUB1 -s 200 -c -l subsidiary_1.bin >subsidiary_1.inc
   catalina -p2 subsidiary_2.c -lc -lmb -R 0x73BE0 -C NO_ARGS 
   spinc -p2 -B2 -n SUB2 -s 200 -c -l subsidiary_2.bin >subsidiary_2.inc
   catalina -p2 primary.c -lc -lmb -o primary_lmm
   catalina -p2 primary.c -lc -lmb -C NATIVE -o primary_nmm
   #
   # Demo 4 : Run "Dining Philosophers" at a fixed address
   # =====================================================
   #
   # Compile the primary program to run the subsidiary programs
   # at a fixed Hub Address (0x40000).
   # 
   # Compile CMM, LMM and NMM versions of the primary program.
   #
   catalina -p2 dining_philosophers.c -lci -lthreads -R 0x40000 -C NO_ARGS
   spinc -p2 -B2 -n LMM -s 8000 -f _threaded_cogstart_LMM_cog -c -l dining_philosophers.bin >dining_philosophers_lmm.inc
   catalina -p2 dining_philosophers.c -lci -lthreads -R 0x40000 -C NO_ARGS -C COMPACT
   spinc -p2 -B2 -n CMM -s 8000 -c -l dining_philosophers.bin >dining_philosophers_cmm.inc
   catalina -p2 dining_philosophers.c -lci -lthreads -R 0x40000 -C NO_ARGS -C NATIVE
   spinc -p2 -B2 -n NMM -s 8000 -c -l dining_philosophers.bin >dining_philosophers_nmm.inc
   catalina -p2 run_dining_philosophers.c -lci -o run_diners_lmm
   catalina -p2 run_dining_philosophers.c -lci -C COMPACT -o run_diners_cmm
   catalina -p2 run_dining_philosophers.c -lci -C NATIVE -o run_diners_nmm
   #
   # Demo 5 : Run "Dining Philosophers" from an overlay file
   # =======================================================
   #
   # Compile the primary program to run the subsidiary programs
   # from an overlay file at a fixed Hub Address (0x40000).
   # 
   # Compile CMM, LMM and NMM versions of the primary program.
   #
   catalina -p2 dining_philosophers.c -lci -lthreads -R 0x40000 -C NO_ARGS
   spinc -p2 -B2 -n LMM -s 8000 -c -l dining_philosophers.bin -o diners.lmm >dining_philosophers_lmm.inc
   catalina -p2 dining_philosophers.c -lci -lthreads -R 0x40000 -C NO_ARGS -C COMPACT
   spinc -p2 -B2 -n CMM -s 8000 -c -l dining_philosophers.bin -o diners.cmm >dining_philosophers_cmm.inc
   catalina -p2 dining_philosophers.c -lci -lthreads -R 0x40000 -C NO_ARGS -C NATIVE
   spinc -p2 -B2 -n NMM -s 8000 -c -l dining_philosophers.bin -o diners.nmm >dining_philosophers_nmm.inc
   catalina -p2 run_dining_philosophers.c -lcix -o run_lmm
   catalina -p2 run_dining_philosophers.c -lcix -o run_cmm -C COMPACT 
   catalina -p2 run_dining_philosophers.c -lcix -o run_nmm -C NATIVE

fi

unset CATALINA_DEFINE
echo ""
echo "   ===="
echo "   Done"
echo "   ===="
echo ""

