#!/bin/bash
#set -x
#
if [[ "$1" == "P2_EDGE" ]]; then
   if [[ "$2" == "" ]]; then
     TMP_RAM=PSRAM
   elif [[ "$2" == "HYPER" ]]; then
     TMP_RAM=HYPER
   elif [[ "$2" == "PSRAM" ]]; then
     TMP_RAM=PSRAM
   else
     TMP_RAM=ERROR
   fi
fi

if [[ "$1" == "P2_EVAL" ]]; then
   if [[ "$2" == "" ]]; then
     TMP_RAM=HYPER
   elif [[ "$2" == "HYPER" ]]; then
     TMP_RAM=HYPER
   else
     TMP_RAM=ERROR     
   fi
fi

if [[ "$1" != "P2_EVAL" ]] && [[ "$1" != "P2_EDGE" ]]; then
  echo "ERROR: ONLY P2_EDGE AND P2_EVAL ARE SUPPORTED"
  exit
fi

if [[ "$TMP_RAM" != "PSRAM" ]] && [[ "$TMP_RAM" != "HYPER" ]]; then
  echo "ERROR: XMM TYPE NOT SUPPORTED"
  exit
fi

if [[ ! -e "/usr/bin/zip" ]] ; then
   echo "ZIP ARCHIVE MANAGER NOT FOUND - INSTALL IT AND TRY AGAIN!"
   exit
fi

if [[ "$CATALINA_DEFINE" != "" ]]; then
   echo "CATALINA_DEFINE MUST NOT BE SET - UNSET IT AND TRY AGAIN!"
   exit
fi

./build_p2_serial $*

./build_p2_vga $*

