#!/bin/bash
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: Environment variable CATALINA_DEFINE is set (to $CATALINA_DEFINE)"
   echo ""
   echo "You must undefine this environment variable before using this batch"
   echo "file, and instead specify the target and options on the command line."
   echo "";
   exit
fi
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]]; then
   TMP_LCCDIR=/opt/catalina	
fi
#
if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi   

echo ""
echo "   ================================"
echo "   Building all Catalyst components"
echo "   ================================"
echo ""

rm -fr bin/*
cp CATALYST.TXT bin/

cd core
build_all MORPHEUS CPU_1 PC VT100 $1 $2 $3 $4
copy_all ../bin/
cd ..

cd xvi-2.47
build_morpheus $1 $2 $3 $4 $5
copy_all ../bin/
cd ..

cd pascal/p5_c
build_morpheus $1 $2 $3 $4 $5
copy_all ../../bin/
cd ../..

cd jzip
build_morpheus $1 $2 $3 $4 $5
copy_all ../bin/
cd ..

cd dumbo_basic
build_morpheus $1 $2 $3 $4 $5
copy_all ../bin/
cd ..

cd sst
build_morpheus $1 $2 $3 $4 $5
copy_all ../bin/
cd ..

cd lua-5.1.4
build_morpheus $1 $2 $3 $4 $5
copy_all ../bin/
cd ..

# restore TMP_LCCDIR here
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]]; then
   TMP_LCCDIR=/opt/catalina	
fi
#

echo ""
echo "   ===="
echo "   Done"
echo "   ===="
echo ""

