#!/bin/bash
#set -x
#
if [[ "$1" != "" ]]; then
   echo "THIS SCRIPT ACCEPTS NO PARAMETERS!"
   exit
fi

if [[ ! -e "/usr/bin/zip" ]] ; then
   echo "ZIP ARCHIVE MANAGER NOT FOUND - INSTALL IT AND TRY AGAIN!"
   exit
fi

if [[ "$CATALINA_DEFINE" != "" ]]; then
   echo "CATALINA_DEFINE MUST NOT BE SET - UNSET IT AND TRY AGAIN!"
   exit
fi

echo "building P2_DEMO.ZIP ..."

./build_all P2_CUSTOM SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_200
cat catalina/CATALYST.ENV catalina/P2_EDGE.ENV > image/CATALYST.ENV

rm -f P2_DEMO.ZIP
cd image
zip -r -q ../P2_DEMO.ZIP *
cd ..

./build_p2 P2_EVAL HYPER

./build_p2 P2_EDGE PSRAM

echo "Done!"
