#!/bin/bash
#set -x
#
if [[ "$1" != "" ]]; then
   echo "THIS SCRIPT ACCEPTS NO PARAMETERS!"
   exit
fi

if [[ ! -e "/usr/bin/zip" ]] ; then
   echo "ZIP ARCHIVE MANAGER NOT FOUND - INSTALL IT AND TRY AGAIN!"
   exit
fi

if [[ "$CATALINA_DEFINE" != "" ]]; then
   echo "CATALINA_DEFINE MUST NOT BE SET - UNSET IT AND TRY AGAIN!"
   exit
fi

echo "building P2_DEMO.ZIP ..."

./build_all P2_EVAL SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200
cat catalina/CATALYST.ENV catalina/P2_EVAL.ENV > image/CATALYST.ENV

rm -f P2_DEMO.ZIP
cd image
mkdir bin
mv -f *.bin bin/
mv -f if.lua bin/
mv -f exec.lua bin/
mv -f freq.lua bin/
mv -f find.lua bin/
mv -f wild.lua bin/
mv -f attrib.lua bin/
zip -r -q ../P2_DEMO.ZIP *
cd ..

echo "building P2_EVAL.ZIP ..."

./build_all P2_EVAL SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200 RTC

cd catalina
./build_all P2_EVAL SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200
cat CATALYST.ENV P2_EVAL.ENV > ../image/CATALYST.ENV
cd ..

cd xvi-2.51
./build_all P2_EVAL SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200 LARGE
cp src/xvi.bin ../image/xl_vi.bin
cd ..

cd lua-5.4.4
./build_all P2_EVAL SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200 SMALL
cp src/lua.bin ../image/xs_lua.bin
cp src/luac.bin ../image/xs_luac.bin
cp src/luax.bin ../image/xs_luax.bin
cd ..

cd lua-5.4.4
./build_all P2_EVAL SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200 LARGE
cp src/lua.bin ../image/xl_lua.bin
cp src/luac.bin ../image/xl_luac.bin
cp src/luax.bin ../image/xl_luax.bin
cd ..

rm -f P2_EVAL.ZIP
cd image
mv -f *.bin bin/
mv -f if.lua bin/
mv -f exec.lua bin/
zip -r -q ../P2_EVAL.ZIP *
cd ..

echo "building P2_EVAL_VGA.ZIP ..."

./build_all P2_EVAL VGA COLOR_4 OPTIMIZE MHZ_200 RTC

cd catalina
./build_all P2_EVAL VGA COLOR_4 OPTIMIZE MHZ_200
cat CATALYST.ENV P2_EVAL_VGA.ENV > ../image/CATALYST.ENV
cd ..

cd xvi-2.51
./build_all P2_EVAL VGA COLOR_4 OPTIMIZE MHZ_200 LARGE
cp src/xvi.bin ../image/xl_vi.bin
cd ..

cd lua-5.4.4
./build_all P2_EVAL VGA COLOR_4 OPTIMIZE MHZ_200 SMALL
cp src/lua.bin ../image/xs_lua.bin
cp src/luac.bin ../image/xs_luac.bin
cp src/luax.bin ../image/xs_luax.bin
cd ..

cd lua-5.4.4
./build_all P2_EVAL VGA COLOR_4 OPTIMIZE MHZ_200 LARGE
cp src/lua.bin ../image/xl_lua.bin
cp src/luac.bin ../image/xl_luac.bin
cp src/luax.bin ../image/xl_luax.bin
cd ..

rm -f P2_EVAL_VGA.ZIP
cd image
mv -f *.bin bin/
mv -f if.lua bin/
mv -f exec.lua bin/
zip -r -q ../P2_EVAL_VGA.ZIP *
cd ..

echo "building P2_EDGE.ZIP ..."

./build_all P2_EDGE SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200 RTC

cd catalina
./build_all P2_EDGE SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200
cat CATALYST.ENV P2_EDGE.ENV >../image/CATALYST.ENV
cd ..

cd xvi-2.51
./build_all P2_EDGE SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200 LARGE
cp src/xvi.bin ../image/xl_vi.bin
cd ..

cd lua-5.4.4
./build_all P2_EDGE SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200 SMALL
cp src/lua.bin ../image/xs_lua.bin
cp src/luac.bin ../image/xs_luac.bin
cp src/luax.bin ../image/xs_luax.bin
cd ..

cd lua-5.4.4
./build_all P2_EDGE SIMPLE VT100 CR_ON_LF USE_COLOR OPTIMIZE MHZ_200 LARGE
cp src/lua.bin ../image/xl_lua.bin
cp src/luac.bin ../image/xl_luac.bin
cp src/luax.bin ../image/xl_luax.bin
cd ..

rm -f P2_EDGE.ZIP
cd image
mv -f *.bin bin/
mv -f if.lua bin/
mv -f exec.lua bin/
zip -r -q ../P2_EDGE.ZIP *
cd ..

echo "building P2_EDGE_VGA.ZIP ..."

./build_all P2_EDGE VGA COLOR_4 OPTIMIZE MHZ_200 RTC

cd catalina
./build_all P2_EDGE VGA COLOR_4 OPTIMIZE MHZ_200
cat CATALYST.ENV P2_EDGE_VGA.ENV > ../image/CATALYST.ENV
cd ..

cd xvi-2.51
./build_all P2_EDGE VGA COLOR_4 OPTIMIZE MHZ_200 LARGE
cp src/xvi.bin ../image/xl_vi.bin
cd ..

cd lua-5.4.4
./build_all P2_EDGE VGA COLOR_4 OPTIMIZE MHZ_200 SMALL
cp src/lua.bin ../image/xs_lua.bin
cp src/luac.bin ../image/xs_luac.bin
cp src/luax.bin ../image/xs_luax.bin
cd ..

cd lua-5.4.4
./build_all P2_EDGE VGA COLOR_4 OPTIMIZE MHZ_200 LARGE
cp src/lua.bin ../image/xl_lua.bin
cp src/luac.bin ../image/xl_luac.bin
cp src/luax.bin ../image/xl_luax.bin
cd ..

rm -f P2_EDGE_VGA.ZIP
cd image
mv -f *.bin bin/
mv -f if.lua bin/
mv -f exec.lua bin/
zip -r -q ../P2_EDGE_VGA.ZIP *
cd ..

echo "Done!"
