#!/bin/bash
#set -x
#
if [[ "$1" == "P2_EDGE" ]]; then
   if [[ "$2" == "" ]]; then
     TMP_RAM=PSRAM
   elif [[ "$2" == "HYPER" ]]; then
     TMP_RAM=HYPER
   elif [[ "$2" == "PSRAM" ]]; then
     TMP_RAM=PSRAM
   else
     TMP_RAM=ERROR
   fi
fi

if [[ "$1" == "P2_EVAL" ]]; then
   if [[ "$2" == "" ]]; then
     TMP_RAM=HYPER
   elif [[ "$2" == "HYPER" ]]; then
     TMP_RAM=HYPER
   else
     TMP_RAM=ERROR     
   fi
fi

if [[ "$1" != "P2_EVAL" ]] && [[ "$1" != "P2_EDGE" ]]; then
  echo "ERROR: ONLY P2_EDGE AND P2_EVAL ARE SUPPORTED"
  exit
fi

if [[ "$TMP_RAM" != "PSRAM" ]] && [[ "$TMP_RAM" != "HYPER" ]]; then
  echo "ERROR: XMM TYPE NOT SUPPORTED"
  exit
fi

if [[ ! -e "/usr/bin/zip" ]] ; then
   echo "ZIP ARCHIVE MANAGER NOT FOUND - INSTALL IT AND TRY AGAIN!"
   exit
fi

if [[ "$CATALINA_DEFINE" != "" ]]; then
   echo "CATALINA_DEFINE MUST NOT BE SET - UNSET IT AND TRY AGAIN!"
   exit
fi

echo ""
echo "building $1_300.ZIP ..."
echo ""

./build_all $1 $2 $3 SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_300 RTC

# create the directory structure expected by catalina 
mk_cat_dirs image

cd catalina
./build_all  $1 $2 $3 SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_300
cat CATALYST.ENV $1.ENV > ../image/CATALYST.ENV
cd ..

cd cake
# NOTE: we cannot use OPTIMIZE with Cake ...
./build_all  $1 $2 $3 SIMPLE VT100 USE_COLOR MHZ_300
cp $LCCDIR/source/cake/src/catalina/cake.bin ../image/bin/cake.bin
cp CAKECONF.H ../image/CAKECONF.H
cp hello_99.c ../image/hello_99.c
cd ..

cd xvi-2.51
./build_all  $1 $2 $3 SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_300 LARGE
cp src/xvi.bin ../image/bin/xl_vi.bin
cd ..

cd lua-5.4.4
./build_all  $1 $2 $3 SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_300 SMALL
cp src/lua.bin ../image/bin/xs_lua.bin
cp src/luac.bin ../image/bin/xs_luac.bin
cp src/luax.bin ../image/bin/xs_luax.bin
cd ..

cd lua-5.4.4
./build_all  $1 $2 $3 SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_300 LARGE
cp src/lua.bin ../image/bin/xl_lua.bin
cp src/luac.bin ../image/bin/xl_luac.bin
cp src/luax.bin ../image/bin/xl_luax.bin
cd ..

rm -f $1_300.ZIP
cd image
zip -r -q ../$1_300.ZIP *
cd ..

echo ""
echo "building $1_VGA_300.ZIP ..."
echo ""

./build_all  $1 $2 $3 VGA COLOR_4 OPTIMIZE MHZ_300 RTC NO_LINENOISE

# create the directory structure expected by catalina
mk_cat_dirs image

cd catalina
./build_all  $1 $2 $3 VGA COLOR_4 OPTIMIZE MHZ_300
cat CATALYST.ENV $1_VGA.ENV > ../image/CATALYST.ENV
cd ..

cd cake
# NOTE: we cannot use OPTIMIZE with Cake ...
./build_all  $1 $2 $3 SIMPLE VT100 USE_COLOR MHZ_300
cp $LCCDIR/source/cake/src/catalina/cake.bin ../image/bin/cake.bin
cp CAKECONF.H ../image/CAKECONF.H
cp hello_99.c ../image/hello_99.c
cd ..

cd xvi-2.51
./build_all  $1 $2 $3 VGA COLOR_4 OPTIMIZE MHZ_300 LARGE
cp src/xvi.bin ../image/bin/xl_vi.bin
cd ..

cd lua-5.4.4
./build_all  $1 $2 $3 VGA COLOR_4 OPTIMIZE MHZ_300 SMALL
cp src/lua.bin ../image/bin/xs_lua.bin
cp src/luac.bin ../image/bin/xs_luac.bin
cp src/luax.bin ../image/bin/xs_luax.bin
cd ..

cd lua-5.4.4
./build_all  $1 $2 $3 VGA COLOR_4 OPTIMIZE MHZ_300 LARGE
cp src/lua.bin ../image/bin/xl_lua.bin
cp src/luac.bin ../image/bin/xl_luac.bin
cp src/luax.bin ../image/bin/xl_luax.bin
cd ..

rm -f $1_VGA_300.ZIP
cd image
zip -r -q ../$1_VGA_300.ZIP *
cd ..

