#!/bin/bash
#set -x
#
if [[ ! -e $1 ]]; then
   echo ""
   echo "ERROR: invalid destination specified!"
   echo ""
   echo "usage: mk_p2_dirs X:"
   echo ""
   echo "   where X: is the drive you use to read/write SD cards"
   echo ""
   echo "or:    mk_p2_dirs dir/"
   echo ""        
   echo "   where dir is the directory you want to make the directories"
   echo ""
   exit
fi

rm -fr "$1/tmp"
mkdir "$1/tmp"
rm -fr "$1/include"
mkdir "$1/include"
rm -fr "$1/lib/"
mkdir "$1/lib/"
rm -fr "$1/lib/p2"
mkdir "$1/lib/p2"
rm -fr "$1/lib/p2/lmm"
mkdir "$1/lib/p2/lmm"
rm -fr "$1/lib/p2/cmm"
mkdir "$1/lib/p2/cmm"
rm -fr "$1/lib/p2/nmm"
mkdir "$1/lib/p2/nmm"
rm -fr "$1/lib/p2/xmm"
mkdir "$1/lib/p2/xmm"
rm -fr "$1/target"
mkdir "$1/target"
rm -fr "$1/target/p2"
mkdir "$1/target/p2"

