#!/bin/bash
#set -x
#
if [[ "$1" != "" ]]; then
   echo "THIS SCRIPT ACCEPTS NO PARAMETERS!"
   exit
fi

if [[ ! -e "/usr/bin/zip" ]] ; then
   echo "ZIP ARCHIVE MANAGER NOT FOUND - INSTALL IT AND TRY AGAIN!"
   exit
fi

if [[ "$CATALINA_DEFINE" != "" ]]; then
   echo "CATALINA_DEFINE MUST NOT BE SET - UNSET IT AND TRY AGAIN!"
   exit
fi

echo "building P2_EDGE.ZIP ..."

./build_all P2_EDGE SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_200 RTC

cd catalina
./build_all P2_EDGE SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_200
cat CATALYST.ENV P2_EDGE.ENV >../image/CATALYST.ENV
cd ..

cd xvi-2.51
./build_all P2_EDGE SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_200 LARGE
cp src/xvi.bin ../image/xl_vi.bin
cd ..

cd lua-5.4.4
./build_all P2_EDGE SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_200 SMALL
cp src/lua.bin ../image/xs_lua.bin
cp src/luac.bin ../image/xs_luac.bin
cp src/luax.bin ../image/xs_luax.bin
cd ..

cd lua-5.4.4
./build_all P2_EDGE SIMPLE VT100 USE_COLOR OPTIMIZE MHZ_200 LARGE
cp src/lua.bin ../image/xl_lua.bin
cp src/luac.bin ../image/xl_luac.bin
cp src/luax.bin ../image/xl_luax.bin
cd ..

rm -f P2_EDGE.ZIP
cd image
mv -f *.bin bin/
mv -f if.lua bin/
mv -f exec.lua bin/
mv -f call.lua bin/
mv -f echo.lua bin/
mv -f _save.lua bin/
mv -f _restore.lua bin/
zip -r -q ../P2_EDGE.ZIP *
cd ..

echo "Done!"
