#!/bin/bash
#set -x
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]] ; then
   TMP_LCCDIR=/opt/catalina
fi
#
if [[ ! -e "$TMP_LCCDIR/bin/catalina_env" ]] ; then
   clear
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "  Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi
#
if [[ "$CATALINA_DEFINE" != "" ]]; then

   echo ""
   echo "ERROR: CATALINA_DEFINE options may conflict with catapult options"
   echo ""
   echo "   CATALINA_DEFINE is set to $CATALINA_DEFINE"
   echo ""
   echo "   Set CATALINA_DEFINE to null using the following command:"
   echo ""
   echo "      unset CATALINA_DEFINE"
   echo ""
   exit
fi
#
if [[ "$1" != "" ]]; then
   echo "ERROR: This script does not support command line parameters"
   echo ""
   exit
fi
#
export CATALINA_DEFINE=P2_WIFI_MASTER
catapult rlua.c
mv rlua.bin rmaster.bin
catapult rluax.c
mv rluax.bin rmasterx.bin
#
export CATALINA_DEFINE=P2_WIFI_SLAVE
catapult rlua.c
mv rlua.bin rslave.bin
catapult rluax.c
mv rluax.bin rslavex.bin
#
export CATALINA_DEFINE=P2_WIFI
catapult rlua.c
catapult rluax.c
catapult rlua2.c
catapult rlua2x.c
catapult rluasx.c
catapult rluafx.c
catapult sluarfx.c
#
export CATALINA_DEFINE=

