#!/bin/bash
#set -x
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]] ; then
   TMP_LCCDIR=/opt/catalina
fi
#
if [[ ! -e "$TMP_LCCDIR/bin/catalina_env" ]] ; then
   clear
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "  Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi
#
export CATALINA_DEFINE=P2_MASTER
catapult elua.c
mv elua.bin master.bin
catapult eluax.c
mv eluax.bin masterx.bin
export CATALINA_DEFINE=P2_SLAVE
catapult elua.c
mv elua.bin slave.bin
catapult eluax.c
mv eluax.bin slavex.bin
export CATALINA_DEFINE=

