include ../Makefile.inc

all:	lapi.s lctype.s ldebug.s ldo.s ldump.s lfunc.s lgc.s lmem.s lobject.s \
	lopcodes.s lstate.s lstring.s ltable.s ltm.s lundump.s lvm.s lzio.s \
	lauxlib.s lbaselib.s lcorolib.s ldblib.s liolib.s \
	lmathlib.s loadlib.s loslib.s lstrlib.s ltablib.s lutf8lib.s \
	lthreads.s lthrsch.s lprop.s lhmi.s lservice.s lserial2.s storage.s glob.s cfgets.s \
	lcode.s llex.s lparser.s

clean:
	-rm -f *.s
