include ../Makefile.inc

all:	cfgets.s glob.s lapi.s lauxlib.s lbaselib.s lcode.s lcorolib.s lctype.s \
	ldblib.s ldebug.s ldo.s ldump.s lfunc.s lgc.s lhmi.s linenoise.s \
	liolib.s llex.s lmathlib.s lmem.s loadlib.s lobject.s lopcodes.s loslib.s \
	lparser.s lprop.s lserial.s lservice.s lstate.s lstring.s lstrlib.s \
	ltable.s ltablib.s lthreads.s lthrsch.s ltm.s lundump.s \
	lutf8lib.s lvm.s lwifi.s lzio.s storage.s

clean:
	-rm -f *.s




