#!/bin/bash
#set -x
#
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: Environment variable CATALINA_DEFINE is set (to $CATALINA_DEFINE)"
   echo ""
   echo "You must undefine this environment variable before using this batch"
   echo "file, and instead specify the target and options on the command line."
   echo "";
   exit
elif [[ "$1" ==  "" ]] ; then
   echo ""
   echo "ERROR: no PLATFORM specified !"
   echo ""
   echo "usage: build_all PLATFORM"
   echo ""
   echo "   where  PLATFORM is HYDRA, HYBRID, RAMBLADE, TRIBLADEPROP, DRACBLADE"
   echo "                      DEMO, CUSTOM or P2_EVAL (P2 only)"
   echo "   and    OPTIONS are other Catalina options (e.g. CPU_1, HIRES_TV, NTSC)"
   echo ""
   echo "   NOTE: Options CLOCK and NO_MOUSE are automatically included"
   echo ""
   exit
else
   echo ""
   echo "   ============"
   echo "   Building Lua"
   echo "   ============"
   echo ""

   CATALINA_DEFINE="$1 $2 $3 $4 $5 $6 $7 $8 $9"; export CATALINA_DEFINE

   platform=$1
   if [ "${platform:0:2}" == "P2" ]; then 

      cd src
      make -f Makefile.Catalina_p2 clean
      make -f Makefile.Catalina_p2
      cd ..

   else

      cd src
      make -f Makefile.Catalina clean
      make -f Makefile.Catalina
      cd ..

   fi

   unset CATALINA_DEFINE

fi
