#!/bin/bash
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]]; then
   TMP_LCCDIR=/opt/catalina	
fi
#
if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
elif [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: Environment variable CATALINA_DEFINE is set (to $CATALINA_DEFINE)"
   echo ""
   echo "You must undefine this environment variable before using this"
   echo "batch file, and instead specify the target on the command line."
   echo "";
elif [[ "$1" == "MORPHEUS" ]]; then
   # 
   # MORPHEUS CANNOT RUN THIS VERSION OF STARTREK USING LOCAL DEVICES UNTIL A 
   # VGA DRIVER IS DEVELOPED THAT USES LESS COGS - BUT HERE ARE THE COMMANDS 
   # THAT WOULD BE REQUIRED TO BUILD IT ...
   #
   # - build the VGA game client
   #source build_tmp_var $2 $3 $4 $5
   # catalina sst.c ai.c battle.c catalina.c events.c finish.c moving.c planets.c reports.c setup.c -lcx -C LARGE -lma -M512k -o sst -C MORPHEUS -C CPU_2 -C PROXY_SD -C PROXY_KEYBOARD -C NO_MOUSE -C CLOCK $TMP_VAR
   # echo ""
   # rem - build a VGA proxy server
   #source build_pasm_tmp_var $2 $3 $4 $5
   #spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o test_1_server_1 -b -D MORPHEUS -D CPU_1 -D NO_SCREEN -D NO_MOUSE $TMP_VAR
   #
   # SO INSTEAD, WE BUILD A VERSION THAT USES A PC TERMINAL EMULATOR IN PLACE 
   # OF THE LOCAL VGA:
   #
   # - build the PC game client
   rm -fr *.binary
   source build_tmp_var $2 $3 $4 $5
   catalina sst.c ai.c battle.c catalina.c events.c finish.c moving.c planets.c reports.c setup.c -lcx -C LARGE -lma -M512k -o sst -C MORPHEUS -C CPU_2 -C PROXY_SD -C PROXY_SCREEN -C PROXY_KEYBOARD -C NO_MOUSE -C PC -C CLOCK $TMP_VAR
   echo ""
   # - build a PC proxy server
   source build_pasm_tmp_var $2 $3 $4 $5
   spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o proxy -b -D MORPHEUS -D CPU_1 -D NO_MOUSE -D PC $TMP_VAR
   #
elif [[ "$1" == "TRIBLADEPROP" ]]; then
   #
   # - build the game client
   rm -fr *.binary
   source build_tmp_var $2 $3 $4 $5
   catalina sst.c ai.c battle.c catalina.c events.c finish.c moving.c planets.c reports.c setup.c -lcx -C LARGE -lma -M512k -o sst -C TRIBLADEPROP -C CPU_1 -C PROXY_SD -C CLOCK -C NO_MOUSE $TMP_VAR
   echo ""
   # - build a proxy server
   source build_pasm_tmp_var $2 $3 $4 $5
   spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o proxy -b -D TRIBLADEPROP -D CPU_2 -D NO_SCREEN -D NO_MOUSE -D NO_KEYBOARD $TMP_VAR
   #
else
   echo ""
   echo "ERROR: Unknown target (or no target) specified."
   echo ""
   echo "Usage: build_sst_proxy TRIBLADEPROP"
   echo "   or: build_sst_proxy MORPHEUS"
   echo ""
fi

