#!/bin/bash
if [[ ! -e $1 ]]; then
   echo ""
   echo "ERROR: invalid destination specified !"
   echo ""
   echo "usage: copy_all X:"
   echo ""
   echo "   where X: is the drive you use to read/write SD cards"
   echo ""
   echo "or:    copy_all dir/"
   echo ""        
   echo "   where dir is the directory you want to copy to"
   echo ""
   exit
fi

cp sst.doc $1

if [ -f sst.bin ]; then

   cp sst.bin $1sst.bin

else

   cp sst.binary $1sst.bin
   if [[ -e proxy.binary ]]; then
      cp proxy.binary $1proxy.bin  
   fi

fi
