include ../Makefile.inc

all:
	cp ../catalina_math/catalina_float_a.s .
	cp ../catalina_math/catalina_float_plugin.s .
	cp ../math/fmod.s .
	cp ../math/isnan.s .
	cp ../math/ldexp.s .
	cp ../math/frexp.s .
	cp ../math/hugeval.s .
	cp ../math/fabs.s .
	cp ../math/sinh.s .
	cp ../math/tanh.s .
	cp ../math/asin.s .
	cp ../math/atan.s .
	cp ../math/atan2.s .
	cp ../math/ceil.s .
	cp ../math/floor.s .
	build_index

clean:
	rm -f *.s catalina.index

