include ../Makefile.inc

all:	 \
	doprintf.s \
	doprintf_s.s \
	doscanf.s \
	fgetc.s \
	fputc.s \
	getdec.s \
	getfnum.s \
	gethex.s \
	getldec.s \
	getlfnum.s \
	getlhex.s \
	getludec.s \
	gets.s \
	getudec.s \
	printf.s \
	printf_pad.s \
	printf_putc.s \
	printf_putl.s \
	printf_putll.s \
	printf_putls.s \
	printf_putn.s \
	printf_puts.s \
	printf_s.s \
	putdec.s \
	putfnum.s \
	puthex.s \
	putldec.s \
	putlfnum.s \
	putlhex.s \
	putludec.s \
	putstr.s \
	putudec.s \
	safe_gets.s \
	scanf.s \
	scanf_getl.s \
	scanf_getll.s \
	siodev.h \
	sprintf.s \
	Makefile \
	sscanf.s

clean:
	rm -f *.s
