include ../Makefile.inc

all:	float_a.s float_b.s float_c.s \
	fplugin.s sinh.s tanh.s fservice.s \
	fround.s ftrunc.s lround.s ltrunc.s

clean:
	-rm -f float_a.s float_b.s float_c.s \
	fplugin.s sinh.s tanh.s fservice.s \
	fround.s ftrunc.s lround.s ltrunc.s OLIST
