// include some standard header files
#include <stdlib.h>

// include some useful utilities
#include "utilities.h"

// include the Spin program (as generated by the SpinC utility)
#include "demo.c"

#ifdef __CATALINA_P2
#error THIS PROGRAM REQUIRES A PROPELLER 1
#endif

int main(void) {

   // to be accessible to the Spin interpreter the program, var and stack must
   // all be in Hub RAM - so we declare them locally in case this program is 
   // running as an XMM program with the actual Spin program in XMM RAM:
   char prog[DEMO_PROG_SIZE];
   char var[DEMO_VAR_SIZE];
   char stack[DEMO_STACK_SIZE];

   // start the Spin program (using the function built by the SpinC utility):
   start_DEMO(prog, var, stack);

   // now just do something to show we are still alive:
   while (1) {
      wait(1000);
      t_string(1, "This is Catalina C!\n\r");
   }

   return 0;
}
