// include some standard header files
#include <stdlib.h>

// include some useful utilities
#include "utilities.h"

// include the Spin program (this file is generated by the SpinC utility)
#include "flash.h"

#ifdef __CATALINA_P2
#error THIS PROGRAM REQUIRES A PROPELLER 1
#endif

int main(void) {

   // to be accessible to the Spin interpreter the program, var and stack
   // space must all be in Hub RAM - so we declare them locally here
   char stack[FLASH_STACK_SIZE];
   char prog[FLASH_PROG_SIZE];
   char var[FLASH_VAR_SIZE];

   // zero the memory we will use as var and stack space
   memset(var, 0, FLASH_VAR_SIZE);
   memset(stack, 0, FLASH_STACK_SIZE);

   // copy the Spin program from XMM RAM to Hub RAM
   memcpy(prog, FLASH_array, FLASH_PROG_SIZE);

   // initiate a Spin program using the _coginit_Spin library funtion - this 
   // program simply turns a LED on or off
   _coginit_Spin(prog, var, stack, FLASH_PROG_OFF, FLASH_STACK_OFF);

   // to interact with the Spin program, we use the var array - for example, 
   // the following code prints out whether the Spin program currently has
   // the LED turned off or on. It relies on knowing that the long variable
   // the Spin program calls "bit" is stored at offset 0 of the var array:

   #define bit SPIN_LONG(var,0)

   while (1) {
      if (bit == 0) {
         t_printf("on! ");
         while (bit == 0) ;
      }
      if (bit != 0) {
         t_printf("off! ");
         while (bit != 0) ;
      }
   }

   return 0;
}
