// include some standard header files
#include <stdlib.h>

// include some useful utilities
#include "utilities.h"

// include the Spin program (this file is generated by the SpinC utility)
#include "hello.h"

#ifdef __CATALINA_P2
#error THIS PROGRAM REQUIRES A PROPELLER 1
#endif

int main(void) {

   // to be accessible to the Spin interpreter the program, var and stack
   // space must all be in Hub RAM - so we declare them locally here
   char stack[HELLO_STACK_SIZE];
   char prog[HELLO_PROG_SIZE];
   char var[HELLO_VAR_SIZE];

   // zero the memory we will use as var and stack space
   memset(var, 0, HELLO_VAR_SIZE);
   memset(stack, 0, HELLO_STACK_SIZE);

   // copy the Spin program from XMM RAM to Hub RAM
   memcpy(prog, HELLO_array, HELLO_PROG_SIZE);

   //t_printf("Press a key to start\n");
   //k_wait();

   // initiate a Spin program using the _coginit_Spin library funtion
   _coginit_Spin(prog, var, stack, HELLO_PROG_OFF, HELLO_STACK_OFF);

   while (1) ; // loop forever

   return 0;
}
