#!/bin/bash
if [[ ! -e $1 ]]; then
   echo ""
   echo "ERROR: invalid destination specified !"
   echo ""
   echo "usage: copy_all X:"
   echo ""
   echo "   where X: is the drive you use to read/write SD cards"
   echo ""
   echo "or:    copy_all dir/"
   echo ""        
   echo "   where dir is the directory you want to copy to"
   echo ""
   exit
fi

cp ZORK1.DAT $1
cp ZORK2.DAT $1
cp ZORK3.DAT $1

if [ -f jzip.bin ]; then

   cp jzip.bin $1jzip.bin

else

   cp jzip.binary $1jzip.bin

   if [[ -e proxy.binary ]]; then
      cp proxy.binary $1proxy.bin  
   fi

fi
