#!/bin/bash
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: please unset CATALINA_DEFINE before running this script."
   echo "";
   echo "";
   exit
fi
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]]; then
   TMP_LCCDIR=/opt/catalina	
fi
#
if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi   
#
# TEST 1 : test_suite runnning on CPU #2
#          proxy running on CPU #1 providing access to keyboard 
#
catalina ..\test_suite\test_suite.c -o test_1_client_2 -lc -C MORPHEUS -C CPU_2 -C PROXY_KEYBOARD -C NO_MOUSE
echo ""
spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o test_1_server_1 -b -D MORPHEUS -D CPU_1 -D NO_SCREEN -D NO_MOUSE
#
# TEST 2 : test_terminal runnning on CPU #2
#          proxy running on CPU #1 providing access to keyboard & mouse 
#
echo ""
catalina ..\examples\ex_terminal.c -o test_2_client_2 -lc -C MORPHEUS -C CPU_2 -C PROXY_KEYBOARD -C PROXY_MOUSE
echo ""
spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o test_2_server_1 -b -D MORPHEUS -D CPU_1 -D NO_SCREEN 
#
# TEST 3 : test_fs runnning on CPU #2
#          proxy running on CPU #1 providing access to 
#          sd card, keyboard & mouse
#
# NOTE: We run out of cogs unless the NO_FP and NO_ARGS options are set on the client !!!
echo ""
catalina ..\test_suite\test_stdio_fs.c -lcx -C SMALL -o test_3_client_2 -C MORPHEUS -C CPU_2 -C PROXY_KEYBOARD -C PROXY_MOUSE -C PROXY_SD -C NO_FP -C NO_ARGS
echo ""
spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o test_3_server_1 -b -D MORPHEUS -D CPU_1 -D NO_SCREEN 
#
# TEST 4 : test_suite runnning on CPU #1
#          proxy running on CPU #2 providing access to screen
#          (not all screen functions supported when proxying)
#
echo ""
catalina ..\test_suite\test_suite.c -o test_4_client_1 -lc -C MORPHEUS -C CPU_1 -C PROXY_SCREEN
echo ""
spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o test_4_server_2 -b -D MORPHEUS -D CPU_2 -D NO_KEYBOARD -D NO_MOUSE
#
