#!/bin/bash
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: please unset CATALINA_DEFINE before running this script."
   echo "";
   echo "";
   exit
fi
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]]; then
   TMP_LCCDIR=/opt/catalina	
fi
#
if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi   
#
# TEST 1 : test_suite runnning on CPU #2
#          proxy running on CPU #1 providing access to screen and
#          keyboard 
#
echo ""
catalina ..\test_suite\test_suite.c -o test_1_client_2 -lc -C TRIBLADEPROP -C CPU_2 -C PROXY_KEYBOARD -C PROXY_SCREEN -C NO_MOUSE
echo ""
spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target/p1" -o test_1_server_1 -b -D TRIBLADEPROP -D CPU_1 -D NO_SD
rm -f $TMP_LCCDIR/target/p1/Generic_Proxy_Server.spin 
#
# TEST 2 : test_fs runnning on CPU #1
#          proxy running on CPU #2 providing access to sd card
#
echo ""
catalina ..\file_systems\test_stdio_fs.c -lcx -C SMALL -o test_2_client_1 -C TRIBLADEPROP -C CPU_1 -C PROXY_SD -C NO_MOUSE -C NO_FP
echo ""
spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target/p1" -o test_2_server_2 -b -D TRIBLADEPROP -D CPU_2 -D NO_SCREEN -D NO_KEYBOARD -D NO_MOUSE
rm -f $TMP_LCCDIR/target/p1/Generic_Proxy_Server.spin 
#
