#!/bin/bash
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: please unset CATALINA_DEFINE before running this script."
   echo "";
   echo "";
   exit
fi   
#
#
#  =====================
#  BUILDING CPU #1 DEMOS
#  =====================
#
#
catalina ..\games\othello.c -lc -o othello_pc_1 -C MORPHEUS -C CPU_1 -C PC
catalina ..\file_systems\test_catalina_fs.c -lcix -o test_fs_pc_1 -C MORPHEUS -C PC -C CPU_1 -C NO_MOUSE -C COMPACT -C NO_FLOAT
#
#
#  =====================
#  BUILDING CPU #2 DEMOS
#  =====================
#
#
catalina ..\test_suite\test_suite.c -lc -o test_suite_pc_2 -C MORPHEUS -C PC -C CPU_2
catalina ..\games\startrek.c -lc -lma -C SMALL -o startrek_pc_2 -C MORPHEUS -C PC -C CPU_2

