@echo off
rem
rem Script to run a pcom self compile
rem
rem First, change elide patterns to remove prr file statements.
rem The modified file goes in pcomm.pas (pcom modified).
rem
sed -e 's/{elide}/{/g' -e 's/{noelide}/}/g' pcom.pas > pcomm.pas
rem
rem Compile pcom to intermediate code using its binary version.
rem
pcom pcomm.p5 < pcomm.pas
rem
rem Now run that code on the interpreter and have it compile itself
rem to intermediate again.
rem
pint pcomm.p5 pcomm.out < pcomm.pas
rem
rem Now we have the original intermediate from the binary version
rem of pcom, and the intermediate generated by the interpreted
rem pcom. Compare them for equality. Put the result in pcomm.dif.
rem
diff pcomm.p5 pcomm.out > pcomm.dif
rem
rem Show the file, so if the length is zero, it compared ok.
rem
dir pcomm.dif
