include ../Makefile.inc

all:	ddebug.s dgptn.s dgvol.s\
	dgfat.s	dsfat.s dcanond.s\
	dgfreef.s dopend.s dgnext.s\
	dgfreed.s dopenf.s dreadf.s\
	dseek.s drenamef.s dunlinkf.s\
	dunlinkd.s dwritef.s dtime.s\
	_common.s _mount.s _read.s\
	_unmount.s _open.s _close.s\
	_write.s _lseek.s _create.s\
	_creat.s _rename.s _unlink.s\
	cat_getc.s cat_putc.s _openu.s\
	_closeu.s _createu.s _mkdir.s\
	_created.s dwrite.s dread.s cache_sd.s

clean:
	-rm -f *.s *.lst *.bin *.binary OLIST
