10 PRINT "JUST PRESS ENTER WHEN PROMPTED FOR NAME TO END INPUT"
20 OPEN "O",#1,"EMPLOYEE.DAT"
30 INPUT "NAME";N$
40 IF N$="" THEN END
50 INPUT "DEPARTMENT";D$
60 INPUT "DATE HIRED";H$
70 PRINT#1,N$;","D$",";H$
80 PRINT:GOTO 30
