include ../Makefile.inc

all:	dosfs_debug.s dosfs_getptnstart.s dosfs_getvolinfo.s\
	dosfs_getfat.s	dosfs_setfat.s dosfs_canonicaltodir.s\
  	dosfs_getfreefat.s dosfs_opendir.s dosfs_getnext.s\
  	dosfs_getfreedirent.s dosfs_openfile.s dosfs_readfile.s\
  	dosfs_seek.s dosfs_renamefile.s dosfs_unlinkfile.s\
	dosfs_unlinkdir.s dosfs_writefile.s\
  	catalina_fs_common.s catalina_fs_mount.s catalina_fs_read.s\
	catalina_fs_unmount.s catalina_fs_open.s catalina_fs_close.s\
	catalina_fs_write.s catalina_fs_lseek.s catalina_fs_create.s\
	catalina_fs_creat.s catalina_fs_rename.s catalina_fs_unlink.s\
	catalina_getc.s catalina_putc.s catalina_fs_open_unmanaged.s\
	catalina_fs_close_unmanaged.s catalina_fs_create_unmanaged.s\
	catalina_fs_create_directory.s dosfs_write.s dosfs_read.s

clean:
	rm -f dosfs_debug.s dosfs_getptnstart.s dosfs_getvolinfo.s\
		dosfs_getfat.s	dosfs_setfat.s dosfs_canonicaltodir.s\
		dosfs_getfreefat.s dosfs_opendir.s dosfs_getnext.s\
	  	dosfs_getfreedirent.s dosfs_openfile.s dosfs_readfile.s\
	  	dosfs_seek.s dosfs_renamefile.s dosfs_unlinkfile.s dosfs_unlinkdir.s\
		dosfs_writefile.s	catalina_fs_common.s catalina_fs_mount.s\
	  	catalina_fs_read.s catalina_fs_unmount.s catalina_fs_open.s\
		catalina_fs_close.s catalina_fs_write.s catalina_fs_lseek.s\
	  	catalina_fs_create.s catalina_fs_creat.s catalina_fs_rename.s\
		catalina_fs_unlink.s catalina_getc.s catalina_putc.s\
	  	catalina_fs_open_unmanaged.s catalina_fs_create_unmanaged.s\
		catalina_fs_close_unmanaged.s catalina_fs_create_directory.s\
		dosfs_write.s dosfs_read.s OLIST
