#!/bin/bash
if [[ ! -e $1 ]]; then
   echo ""
   echo "ERROR: invalid destination specified !"
   echo ""
   echo "usage: copy_all X:"
   echo ""
   echo "   where X: is the drive you use to read/write SD cards"
   echo ""
   echo "or:    copy_all dir/"
   echo ""        
   echo "   where dir is the directory you want to copy to"
   echo ""
   exit
fi

if [ -f send.bin ]; then

   cp send.bin $1send.bin
   cp receive.bin $1receive.bin

else

   cp send.binary $1send.bin
   cp receive.binary $1receive.bin

fi
