#!/bin/bash
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: please unset CATALINA_DEFINE before running this script."
   echo "";
   echo "";
   exit
fi
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]]; then
   TMP_LCCDIR=/opt/catalina	
fi
#
if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi   
#
rm -fr *.binary
source build_tmp_var $1 $2 $3 $4 $5
catalina -C LARGE -M512k -C CLOCK -C MORPHEUS -C CPU_2 -C PC -C VT100 -C NO_MOUSE -C PROXY_SD -C PROXY_SCREEN -C PROXY_KEYBOARD -lcx -lma -o dbasic dumbo_basic.c tokenizer.c basic.c $TMP_VAR
#
echo ""
source build_pasm_tmp_var $1 $2 $3 $4 $5
spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o proxy -b -D MORPHEUS -D PC -D CPU_1 -D NO_MOUSE $TMP_VAR

