#!/bin/bash -login
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]] ; then
   TMP_LCCDIR=/opt/catalina
fi
#
if [[ ! -e "$TMP_LCCDIR/bin/catalina_env" ]] ; then
   clear
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi
# 
cd srecord-1.55
./configure
make
cp bin/srec_cat $TMP_LCCDIR/bin
cp bin/srec_cmp $TMP_LCCDIR/bin
cp bin/srec_info $TMP_LCCDIR/bin
