include ../Makefile.inc

all:	catalina_float_a.s catalina_float_b.s catalina_float_c.s \
	catalina_float_plugin.s sinh.s tanh.s catalina_float_service.s 

clean:
	rm -f catalina_float_a.s catalina_float_b.s catalina_float_b.s \
	catalina_float_plugin.s sinh.s tanh.s catalina_float_service.s OLIST
