#!/bin/bash
#set -x
#
if [[ "$1" != "" ]]; then

   if [[ "$CATALINA_DEFINE" != "" ]]; then

      if [[ "$CATALINA_DEFINE" != "$1 $2 $3 $4 $5 $6 $7 $8 $9" ]]; then

         echo ""
         echo "ERROR: Command line options conflict with CATALINA_DEFINE"
         echo ""
         echo "   The Environment variable CATALINA_DEFINE is set to $CATALINA_DEFINE"
         echo "   The Command line options specified are $1 $2 $3 $4 $5 $6 $7 $8 $9"
         echo ""
         echo "   Either set CATALINA_DEFINE to null using the following command:"
         echo ""
         echo "      unset CATALINA_DEFINE"
         echo ""
         echo "   or do not specify any command line parameters"
         echo ""

      else

         echo ""
         echo "NOTE: Environment variable CATALINA_DEFINE is set to $CATALINA_DEFINE"
         echo ""
         echo "All programs will be built using these options. If these options conflict" 
         echo "with any options specified in this file, the results may be unexpected." 
         
      fi

   else

      CATALINA_DEFINE="$1 $2 $3 $4 $5 $6 $7 $8 $9"; export CATALINA_DEFINE

   fi

else

   if [[ "$CATALINA_DEFINE" != "" ]]; then

      echo ""
      echo "NOTE: Environment variable CATALINA_DEFINE is set to $CATALINA_DEFINE"
      echo ""
      echo "All programs will be built using these options. If these options conflict" 
      echo "with any options specified in this file, the results may be unexpected." 
  
   else     

      echo ""
      echo "NOTE: Environment variable CATALINA_DEFINE is not set"
      echo ""
      echo "All programs will be built for the default target (CUSTOM)" 

   fi

fi

#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]]; then
   TMP_LCCDIR=/opt/catalina	
fi
#
if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi   

echo ""
echo "   ================="
echo "   BUILDING CATALYST"
echo "   ================="
echo ""

source build_pasm_tmp_var CATALYST $1 $2 $3 $4 $5 $6 $7 $8

platform=$1
if [ "${platform:0:2}" != "P2" ]; then 

   cp "$TMP_LCCDIR/target/Catalina_CogStore.spin" .
   spinnaker -q -p -a Catalina_CogStore.spin  -I "$TMP_LCCDIR/target" -b $TMP_VAR
   spinc Catalina_CogStore.binary -n COGSTORE > cogstore_array.h
   rm -f Catalina_CogStore.spin Catalina_CogStore.binary

   cp  "$TMP_LCCDIR/target/Catalina_XMM_SD_Loader.spin" .
   spinnaker -q -p -a Catalina_XMM_SD_Loader.spin  -I "$TMP_LCCDIR/target" -b $TMP_VAR
   spinc Catalina_XMM_SD_Loader.binary -n LOADER > loader_array.h
   rm -f Catalina_XMM_SD_Loader.spin Catalina_XMM_SD_Loader.binary

   cp "$TMP_LCCDIR/target/Catalina_SIO_Plugin.spin" .
   spinnaker -q -p -a Catalina_SIO_Plugin.spin  -I "$TMP_LCCDIR/target" -b $TMP_VAR
   spinc Catalina_SIO_Plugin.binary -n SIO > sio_array.h
   rm -f Catalina_SIO_Plugin.spin Catalina_SIO_Plugin.binary 

   cp "$TMP_LCCDIR/target/Catalina_SPI_Cache.spin" .
   spinnaker -q -p -a Catalina_SPI_Cache.spin  -I "$TMP_LCCDIR/target" -b $TMP_VAR
   spinc Catalina_SPI_Cache.binary -n CACHE > cache_array.h
   rm -f Catalina_SPI_Cache.spin Catalina_SPI_Cache.binary

   catalina catalyst.c cogstore.c loader.c sio.c cache.c -lcix -C CATALYST -C NO_MOUSE -C COMPACT -C NO_FLOAT -C NO_ARGS -O5

   catalina rmdir.c -lcix -C COMPACT -C NO_MOUSE -C NO_FLOAT -O5

   catalina mkdir.c -lcix -C COMPACT -C NO_MOUSE -C NO_FLOAT -O5

   catalina rm.c -lcix -C COMPACT -C NO_MOUSE -C NO_FLOAT -O5

   catalina ls.c -lcix -C COMPACT -C NO_MOUSE -C NO_FLOAT -O5

   catalina cp.c -lcix -C COMPACT -C NO_MOUSE -C NO_FLOAT -O5

   catalina mv.c -lcix -C COMPACT -C NO_MOUSE -C NO_FLOAT -O5

   catalina cat.c -lcix -C COMPACT -C NO_MOUSE -C NO_FLOAT -O5

else

   cp "$TMP_LCCDIR/target_p2/Catalina_CogStore.spin2" .
   p2_asm Catalina_CogStore.spin2  -I "$TMP_LCCDIR/target_p2" $TMP_VAR
   bindump -c -p "   0x" Catalina_CogStore.bin > cogstore_array_p2.inc
   rm -f Catalina_CogStore.spin2 Catalina_CogStore.lst Catalina_CogStore.bin 

   cp  "$TMP_LCCDIR/target_p2/Catalina_SD_Loader.spin2" .
   p2_asm Catalina_SD_Loader.spin2  -I "$TMP_LCCDIR/target_p2" $TMP_VAR
   bindump -c -p "   0x" Catalina_SD_Loader.bin > loader_array_p2.inc
   rm -f Catalina_SD_Loader.spin2 Catalina_SD_Loader.lst Catalina_SD_Loader.bin

   catalina -p2 catalyst.c cogstore.c loader.c -lcix -C CATALYST -C NO_MOUSE -C NATIVE -C NO_FLOAT -C NO_ARGS

   catalina -p2 rmdir.c -lcix -C NATIVE -C NO_MOUSE -C NO_FLOAT

   catalina -p2 mkdir.c -lcix -C NATIVE -C NO_MOUSE -C NO_FLOAT

   catalina -p2 rm.c -lcix -C NATIVE -C NO_MOUSE -C NO_FLOAT

   catalina -p2 ls.c -lcix -C NATIVE -C NO_MOUSE -C NO_FLOAT

   catalina -p2 cp.c -lcix -C NATIVE -C NO_MOUSE -C NO_FLOAT

   catalina -p2 mv.c -lcix -C NATIVE -C NO_MOUSE -C NO_FLOAT

   catalina -p2 cat.c -lcix -C NATIVE -C NO_MOUSE -C NO_FLOAT

fi

unset CATALINA_DEFINE
echo ""
echo "   ===="
echo "   Done"
echo "   ===="
echo ""

