include ../Makefile.inc

all:	ctime.s asctime.s loctime.s clock.s difftime.s gmtime.s \
	mktime.s strftime.s time.s tzset.s misc.s misc_yt.s

clean:
	-rm -f ctime.s asctime.s loctime.s clock.s difftime.s gmtime.s \
		mktime.s strftime.s time.s tzset.s misc.s misc_yt.s OLIST
