include ../Makefile.inc

all:	ctime.s asctime.s localtime.s clock.s difftime.s gmtime.s \
	mktime.s strftime.s time.s tzset.s misc.s

clean:
	rm -f ctime.s asctime.s localtime.s clock.s difftime.s gmtime.s \
		mktime.s strftime.s time.s tzset.s misc.s OLIST
