include ../Makefile.inc

all:	 \
	arg.s \
	check.s \
	close.s \
	connect.s \
	core.s \
	join.s \
	listen.s \
	path.s \
	poll.s \
	readresp.s \
	recv.s \
	reply.s \
	send.s \
	senddata.s \
	set.s \
	wifi_io.s

clean:
	-rm -f *.s
