#!/bin/bash
if [[ ! -e $1 ]]; then
   echo ""
   echo "ERROR: invalid destination specified !"
   echo ""
   echo "usage: copy_all X:"
   echo ""
   echo "   where X: is the drive you use to read/write SD cards"
   echo ""
   echo "or:    copy_all dir/"
   echo ""        
   echo "   where dir is the directory you want to copy to"
   echo ""
   exit
fi

cp time.bin $1time.bin
cp rtc_ex.bin $1rtc_x.bin
cp ex_time1.bin $1ex_time1.bin
cp ex_time2.bin $1ex_time2.bin

