#!/bin/bash
#set -x

TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]] ; then
   TMP_LCCDIR=/opt/catalina
fi

if [[ ! -e "$TMP_LCCDIR/bin/catalina_env" ]] ; then
   clear
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "  Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi

echo ""
echo "   ============="
echo "   Building eLua"
echo "   ============="
echo ""

echo ""
echo "copying source tree ..."
echo ""

cp -R $LCCDIR/demos/elua elua

cd elua
build_all $*
cd ..

