include ../Makefile.inc

all:	asin.s atan2.s atan.s ceil.s fabs.s pow.s log10.s \
	log.s sin.s sinh.s sqrt.s tan.s tanh.s exp.s ldexp.s \
	fmod.s floor.s hugeval.s frexp.s isinf.s isnan.s fpclass.s

clean:
	-rm -f asin.s atan2.s atan.s ceil.s fabs.s pow.s log10.s \
		log.s sin.s sinh.s sqrt.s tan.s tanh.s exp.s ldexp.s \
		fmod.s floor.s hugeval.s frexp.s isinf.s isnan.s fpclass.s OLIST
