#!/bin/bash
if [[ ! -e $1 ]]; then
   echo ""
   echo "ERROR: invalid destination specified !"
   echo ""
   echo "usage: copy_all X:"
   echo ""
   echo "   where X: is the drive you use to read/write SD cards"
   echo ""
   echo "or:    copy_all dir/"
   echo ""        
   echo "   where dir is the directory you want to copy to"
   echo ""
   exit
fi

cp test/hello.lua $1hello.lua
cp test/factorial.lua $1fact.lua
cp test/sort.lua $1sort.lua
cp test/fib.lua $1fib.lua


if [ -f src/lua.bin ]; then

   cp src/lua.bin $1lua.bin
   cp src/luac.bin $1luac.bin

else

   cp src/lua.binary $1lua.bin
   cp src/luac.binary $1luac.bin

   if [[ -e src/proxy.binary ]]; then
      cp src/proxy.binary $1proxy.bin  
   fi

fi
