#!/bin/bash
echo "VALIDATING: FLASH $1 $2 $3 $4 $5 $6 $7 $8 $9"
echo "VALIDATING: FLASH $1 $2 $3 $4 $5 $6 $7 $8 $9" >>results_blackbox.$1 2>&1
echo "PARAMETERS: FLASH $CATALINA_DEFINE" >>results_blackbox.$1 2>&1
echo "" >>results_blackbox.$1 2>&1
catalina -k -g3 -C FLASH -D NO_INPUT $2.c $3 $4 $5 $6 $7 $8 $9 >>results_blackbox.$1 2>&1
payload FLASH $2 -y -z >>results_blackbox.$1 2>&1
sleep 2
blackbox $2 -L $2_blackbox.lua >>results_blackbox.$1 2>&1
rm -f $2.binary
rm -f $2.debug
rm -f $2.dbg
rm -f $2.lst
