/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>
#include <cat_functions.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;
a_VAR *line1_awk = NULL;
a_VAR *s_awk = NULL;
a_VAR *d_awk = NULL;

struct gvar_struct *_gvar;

a_VAR **_lvar;
a_VAR *_litd0_awka=NULL;
a_VAR *_lits0_awka=NULL, *_lits1_awka=NULL, *_lits2_awka=NULL, *_lits3_awka=NULL, *_lits4_awka=NULL, *_lits5_awka=NULL, *_lits6_awka=NULL;
a_VAR *_litr0_awka=NULL, *_litr1_awka=NULL, *_litr2_awka=NULL, *_litr3_awka=NULL, *_litr4_awka=NULL;
void MAIN();

void
MAIN()
{
  int i, _curfile;
  if (*(awka_gets(a_bivar[a_FILENAME])) == '\0')
    awka_strcpy(a_bivar[a_FILENAME], "");
  i = setjmp(context);
  while (awka_getline(a_TEMP, awka_dol0(0), awka_gets(a_bivar[a_FILENAME]), FALSE, TRUE)->dval > 0 && awka_setNF())
  {
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd0_awka)), "}"))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL)))
    {
      awka_varcpy(line1_awk, awka_dol0(0));
      awka_varcpy(s_awk, awka_rtrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(2, 0), _lits1_awka)));
      awka_varcpy(d_awk, awka_doln(3, 0));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      if ((((!strcmp(awka_gets(awka_doln(1, 0)), "mov")) &&  !awka_varcmp(awka_rtrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(2, 0), _lits1_awka)), d_awk))) && !awka_varcmp(awka_doln(3, 0), s_awk))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, awka_dol0(0), NULL));
        goto __152;
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __152:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL)))
    {
      awka_varcpy(line1_awk, awka_dol0(0));
      awka_varcpy(d_awk, awka_rtrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(2, 0), _lits1_awka)));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      if ((((!strcmp(awka_gets(awka_doln(1, 0)), "and")) &&  !awka_varcmp(awka_rtrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(2, 0), _lits1_awka)), d_awk))) && !strcmp(awka_gets(awka_doln(3, 0)), "cviu_m1"))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, awka_dol0(0), NULL));
        goto __243;
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __243:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL)))
    {
      awka_varcpy(line1_awk, awka_dol0(0));
      awka_varcpy(d_awk, awka_rtrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(2, 0), _lits1_awka)));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      if ((((!strcmp(awka_gets(awka_doln(1, 0)), "and")) &&  !awka_varcmp(awka_rtrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(2, 0), _lits1_awka)), d_awk))) && !strcmp(awka_gets(awka_doln(3, 0)), "cviu_m2"))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, awka_dol0(0), NULL));
        goto __334;
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __334:;
      goto nextrec;
    }
    awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
    nextrec:;
  }
}

int
main(int argc, char *argv[])
{
  _max_base_gc = 3;
  _max_fn_gc = 2;

  awka_varinit(line1_awk);
  awka_varinit(s_awk);
  awka_varinit(d_awk);

  awka_varinit(_litd0_awka); awka_setd(_litd0_awka) = 1;
  awka_varinit(_lits0_awka); awka_strcpy(_lits0_awka, "}");
  awka_varinit(_lits1_awka); awka_strcpy(_lits1_awka, ",");
  awka_varinit(_lits2_awka); awka_strcpy(_lits2_awka, "mov");
  awka_varinit(_lits3_awka); awka_strcpy(_lits3_awka, "'%s ' Catalina redundant\n");
  awka_varinit(_lits4_awka); awka_strcpy(_lits4_awka, "and");
  awka_varinit(_lits5_awka); awka_strcpy(_lits5_awka, "cviu_m1");
  awka_varinit(_lits6_awka); awka_strcpy(_lits6_awka, "cviu_m2");
  awka_varinit(_litr0_awka); awka_strcpy(_litr0_awka, "/^'/"); awka_getre(_litr0_awka);
  awka_varinit(_litr1_awka); awka_strcpy(_litr1_awka, "/^{/"); awka_getre(_litr1_awka);
  awka_varinit(_litr2_awka); awka_strcpy(_litr2_awka, "/[ \t]+mov[ \t]+/"); awka_getre(_litr2_awka);
  awka_varinit(_litr3_awka); awka_strcpy(_litr3_awka, "/[ \t]+rdbyte[ \t]+/"); awka_getre(_litr3_awka);
  awka_varinit(_litr4_awka); awka_strcpy(_litr4_awka, "/[ \t]+rdword[ \t]+/"); awka_getre(_litr4_awka);

  if (!_lvar) {
    malloc( &_lvar, 14 * sizeof(a_VAR *) );
    _lvar[0] = _litd0_awka;
    _lvar[1] = _lits0_awka;
    _lvar[2] = _lits1_awka;
    _lvar[3] = _lits2_awka;
    _lvar[4] = _lits3_awka;
    _lvar[5] = _lits4_awka;
    _lvar[6] = _lits5_awka;
    _lvar[7] = _lits6_awka;
    _lvar[8] = _litr0_awka;
    _lvar[9] = _litr1_awka;
    _lvar[10] = _litr2_awka;
    _lvar[11] = _litr3_awka;
    _lvar[12] = _litr4_awka;
    _lvar[13] = NULL;
  }

  malloc( &_gvar, 4 * sizeof(struct gvar_struct) );
  awka_initgvar(0, "line1_awk", line1_awk);
  awka_initgvar(1, "s_awk", s_awk);
  awka_initgvar(2, "d_awk", d_awk);
  _gvar[3].name = NULL;
  _gvar[3].var  = NULL;

  malloc( &_awkafn, 1 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = NULL;
  _awkafn[0].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _split_max = 3;
  _split_req = 1;
  _dol0_used = 1;

  MAIN();

  free(_litd0_awka);
  free(_lits0_awka->ptr); free(_lits0_awka);
  free(_lits1_awka->ptr); free(_lits1_awka);
  free(_lits2_awka->ptr); free(_lits2_awka);
  free(_lits3_awka->ptr); free(_lits3_awka);
  free(_lits4_awka->ptr); free(_lits4_awka);
  free(_lits5_awka->ptr); free(_lits5_awka);
  free(_lits6_awka->ptr); free(_lits6_awka);
  awka_killvar(_litr0_awka); free(_litr0_awka);
  awka_killvar(_litr1_awka); free(_litr1_awka);
  awka_killvar(_litr2_awka); free(_litr2_awka);
  awka_killvar(_litr3_awka); free(_litr3_awka);
  awka_killvar(_litr4_awka); free(_litr4_awka);

  awka_exit(0);
}
