/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>
#include <cat_functions.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;
a_VAR *f_awk = NULL;
a_VAR *leaf_awk = NULL;
a_VAR *done_awk = NULL;

struct gvar_struct *_gvar;

a_VAR **_lvar;
a_VAR *_litd0_awka=NULL, *_litd1_awka=NULL, *_litd2_awka=NULL, *_litd3_awka=NULL, *_litd4_awka=NULL, *_litd5_awka=NULL, *_litd6_awka=NULL;
a_VAR *_lits0_awka=NULL, *_lits1_awka=NULL, *_lits2_awka=NULL, *_lits3_awka=NULL, *_lits4_awka=NULL, *_lits5_awka=NULL, *_lits6_awka=NULL, *_lits7_awka=NULL, *_lits8_awka=NULL, *_lits9_awka=NULL, *_lits10_awka=NULL, *_lits11_awka=NULL, *_lits12_awka=NULL, *_lits13_awka=NULL, *_lits14_awka=NULL, *_lits15_awka=NULL, *_lits16_awka=NULL, *_lits17_awka=NULL, *_lits18_awka=NULL, *_lits19_awka=NULL, *_lits20_awka=NULL, *_lits21_awka=NULL, *_lits22_awka=NULL, *_lits23_awka=NULL, *_lits24_awka=NULL, *_lits25_awka=NULL, *_lits26_awka=NULL, *_lits27_awka=NULL, *_lits28_awka=NULL, *_lits29_awka=NULL, *_lits30_awka=NULL, *_lits31_awka=NULL, *_lits32_awka=NULL;
a_VAR *_litr0_awka=NULL, *_litr1_awka=NULL, *_litr2_awka=NULL, *_litr3_awka=NULL, *_litr4_awka=NULL, *_litr5_awka=NULL, *_litr6_awka=NULL, *_litr7_awka=NULL, *_litr8_awka=NULL, *_litr9_awka=NULL, *_litr10_awka=NULL, *_litr11_awka=NULL, *_litr12_awka=NULL, *_litr13_awka=NULL, *_litr14_awka=NULL, *_litr15_awka=NULL, *_litr16_awka=NULL, *_litr17_awka=NULL;
void BEGIN();
void MAIN();
void END();

void
BEGIN()
{
  initialize_phase_2_fn(awka_arg0(a_TEMP));

}


void
END()
{
  finalize_phase_2_fn(awka_arg1(a_TEMP, _litd0_awka));

}


void
MAIN()
{
  int i, _curfile;
  if (*(awka_gets(a_bivar[a_FILENAME])) == '\0')
    awka_strcpy(a_bivar[a_FILENAME], "");
  i = setjmp(context);
  while (awka_getline(a_TEMP, awka_dol0(0), awka_gets(a_bivar[a_FILENAME]), FALSE, TRUE)->dval > 0 && awka_setNF())
  {
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL)))
    {
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL)))
    {
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd1_awka)), "}"))
      {
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL)))
    {
      awka_varcpy(f_awk, awka_doln(1, 0));
      if (!strcmp(awka_gets(f_awk), "C__exit"))
      {
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        uses_BC_fn(awka_arg1(a_TEMP, f_awk));
        goto __1710;
      }
      if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
      {
        awka_vardblset(leaf_awk, 1);
        awka_vardblset(done_awk, 0);
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd1_awka)), "{"))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd1_awka)), "}"))
          {
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          }
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        }
        if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  !strcmp(awka_gets(awka_doln(2, 0)), "#NEWF"))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#NEWF")))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        }
        if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#CALA")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALA"))))
        {
          awka_vardblset(leaf_awk, 0);
          add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd1_awka)), "{"))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd1_awka)), "}"))
            {
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            }
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        } }
        if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#RETN")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETN"))))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL);
          awka_vardblset(done_awk, 1);
        }
        if (done_awk->dval == 0)
        {
          if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " sub SP, #"))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __839;
          }
          if ((!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " jmp #LODF")) || !strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd4_awka)), " calld PA,#LODF"))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __839;
          }
          if (awka_index(awka_dol0(0), _lits18_awka) != 0)
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __839;
          }
          if (awka_index(awka_dol0(0), _lits19_awka) != 0)
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __839;
          }
          if (awka_index(awka_dol0(0), _lits20_awka) != 0)
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __839;
          }
          if (awka_index(awka_dol0(0), _lits21_awka) != 0)
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __839;
          }
          if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd5_awka)), "C_"))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __839;
          }
          if ((!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " jmp #LODL")) || !strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd4_awka)), " calld PA,#LODL"))
          {
            add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " sub SP, RI"))
            {
              awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL);
              uses_BC_fn(awka_arg1(a_TEMP, f_awk));
              awka_vardblset(done_awk, 1);
            }
            if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#CALA")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALA"))))
            {
              add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              awka_vardblset(leaf_awk, 0);
              goto __839;
            }
            if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#RETN")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETN"))))
            {
              awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL);
              awka_vardblset(done_awk, 1);
              __839:;
          } }
          if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#CALA")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALA"))))
          {
            add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            awka_vardblset(leaf_awk, 0);
            goto __987;
          }
          if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#RETN")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETN"))))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL);
            awka_vardblset(done_awk, 1);
            __987:;
        } }
        if (done_awk->dval == 0)
        {
          if ((!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " jmp #PSHM")) || !strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd4_awka)), " calld PA,#PSHM"))
          {
            add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          }
          if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#CALA")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALA"))))
          {
            awka_vardblset(leaf_awk, 0);
            add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            goto __1198;
          }
          if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#RETN")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETN"))))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL);
            awka_vardblset(done_awk, 1);
            __1198:;
        } }
        if (done_awk->dval == 0)
        {
          if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " mov RI, FP"))
          {
            add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " add RI, #8"))
            {
              add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " sub BC, #4"))
              {
                awka_match(a_TEMP, FALSE, awka_dol0(0), _litr10_awka, NULL);
                add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
                awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
                uses_BC_fn(awka_arg1(a_TEMP, f_awk));
                awka_vardblset(done_awk, 1);
        } } } }
        while (done_awk->dval == 0)
        {
          if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd1_awka)), "{"))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd1_awka)), "}"))
            {
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            }
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            goto __1674;
          }
          if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#CALA")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALI")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#CALA"))))
          {
            awka_vardblset(leaf_awk, 0);
            goto __1674;
          }
          if ((!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " jmp #LODF")) || !strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd4_awka)), " calld PA,#LODF"))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __1674;
          }
          if (awka_index(awka_dol0(0), _lits18_awka) != 0)
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __1674;
          }
          if (awka_index(awka_dol0(0), _lits19_awka) != 0)
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __1674;
          }
          if (awka_index(awka_dol0(0), _lits20_awka) != 0)
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __1674;
          }
          if (awka_index(awka_dol0(0), _lits21_awka) != 0)
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __1674;
          }
          if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd5_awka)), "C_"))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL);
            uses_BC_fn(awka_arg1(a_TEMP, f_awk));
            awka_vardblset(done_awk, 1);
            goto __1674;
          }
          if ((((!strcmp(awka_gets(awka_doln(1, 0)), "jmp")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "#RETN")))) || ((!strcmp(awka_gets(awka_doln(1, 0)), "calld")) &&  ((!strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETF")) ||  !strcmp(awka_gets(awka_doln(2, 0)), "PA,#RETN"))))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL);
            awka_vardblset(done_awk, 1);
            break;
            __1674:;
          }
          add_line_to_function_fn(awka_arg2(a_TEMP, f_awk, awka_dol0(0)));
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        }
        set_leaf_fn(awka_arg2(a_TEMP, f_awk, leaf_awk));
        awka_strcpy(f_awk, "no function");
        __1710:;
      }
      goto nextrec;
    }
    if ((awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr11_awka, NULL))) || awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr12_awka, NULL)))
    {
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr13_awka, NULL);
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr14_awka, NULL);
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr14_awka, NULL);
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr15_awka, NULL)))
    {
      awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(2, 0), _lits32_awka)));
      if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
      {
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr16_awka, NULL);
        uses_BC_fn(awka_arg1(a_TEMP, f_awk));
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr17_awka, NULL);
    } }
    nextrec:;
  }
}

int
main(int argc, char *argv[])
{
  _max_base_gc = 3;
  _max_fn_gc = 2;

  awka_varinit(f_awk);
  awka_varinit(leaf_awk);
  awka_varinit(done_awk);

  awka_varinit(_litd0_awka); awka_setd(_litd0_awka) = 6;
  awka_varinit(_litd1_awka); awka_setd(_litd1_awka) = 1;
  awka_varinit(_litd2_awka); awka_setd(_litd2_awka) = 0;
  awka_varinit(_litd3_awka); awka_setd(_litd3_awka) = 10;
  awka_varinit(_litd4_awka); awka_setd(_litd4_awka) = 15;
  awka_varinit(_litd5_awka); awka_setd(_litd5_awka) = 2;
  awka_varinit(_litd6_awka); awka_setd(_litd6_awka) = 11;
  awka_varinit(_lits0_awka); awka_strcpy(_lits0_awka, "}");
  awka_varinit(_lits1_awka); awka_strcpy(_lits1_awka, "C__exit");
  awka_varinit(_lits2_awka); awka_strcpy(_lits2_awka, "{");
  awka_varinit(_lits3_awka); awka_strcpy(_lits3_awka, "jmp");
  awka_varinit(_lits4_awka); awka_strcpy(_lits4_awka, "#NEWF");
  awka_varinit(_lits5_awka); awka_strcpy(_lits5_awka, "calld");
  awka_varinit(_lits6_awka); awka_strcpy(_lits6_awka, "PA,#NEWF");
  awka_varinit(_lits7_awka); awka_strcpy(_lits7_awka, "#CALI");
  awka_varinit(_lits8_awka); awka_strcpy(_lits8_awka, "#CALA");
  awka_varinit(_lits9_awka); awka_strcpy(_lits9_awka, "PA,#CALI");
  awka_varinit(_lits10_awka); awka_strcpy(_lits10_awka, "PA,#CALA");
  awka_varinit(_lits11_awka); awka_strcpy(_lits11_awka, "#RETF");
  awka_varinit(_lits12_awka); awka_strcpy(_lits12_awka, "#RETN");
  awka_varinit(_lits13_awka); awka_strcpy(_lits13_awka, "PA,#RETF");
  awka_varinit(_lits14_awka); awka_strcpy(_lits14_awka, "PA,#RETN");
  awka_varinit(_lits15_awka); awka_strcpy(_lits15_awka, " sub SP, #");
  awka_varinit(_lits16_awka); awka_strcpy(_lits16_awka, " jmp #LODF");
  awka_varinit(_lits17_awka); awka_strcpy(_lits17_awka, " calld PA,#LODF");
  awka_varinit(_lits18_awka); awka_strcpy(_lits18_awka, ", FP");
  awka_varinit(_lits19_awka); awka_strcpy(_lits19_awka, ",FP");
  awka_varinit(_lits20_awka); awka_strcpy(_lits20_awka, " FP,");
  awka_varinit(_lits21_awka); awka_strcpy(_lits21_awka, "	FP,");
  awka_varinit(_lits22_awka); awka_strcpy(_lits22_awka, "C_");
  awka_varinit(_lits23_awka); awka_strcpy(_lits23_awka, " jmp #LODL");
  awka_varinit(_lits24_awka); awka_strcpy(_lits24_awka, " calld PA,#LODL");
  awka_varinit(_lits25_awka); awka_strcpy(_lits25_awka, " sub SP, RI");
  awka_varinit(_lits26_awka); awka_strcpy(_lits26_awka, " jmp #PSHM");
  awka_varinit(_lits27_awka); awka_strcpy(_lits27_awka, " calld PA,#PSHM");
  awka_varinit(_lits28_awka); awka_strcpy(_lits28_awka, " mov RI, FP");
  awka_varinit(_lits29_awka); awka_strcpy(_lits29_awka, " add RI, #8");
  awka_varinit(_lits30_awka); awka_strcpy(_lits30_awka, " sub BC, #4");
  awka_varinit(_lits31_awka); awka_strcpy(_lits31_awka, "no function");
  awka_varinit(_lits32_awka); awka_strcpy(_lits32_awka, "@");
  awka_varinit(_litr0_awka); awka_strcpy(_litr0_awka, "/^'/"); awka_getre(_litr0_awka);
  awka_varinit(_litr1_awka); awka_strcpy(_litr1_awka, "/^{/"); awka_getre(_litr1_awka);
  awka_varinit(_litr2_awka); awka_strcpy(_litr2_awka, "/^C_/"); awka_getre(_litr2_awka);
  awka_varinit(_litr3_awka); awka_strcpy(_litr3_awka, "/* pretend C__exit uses BC - since we don't want it inlined */"); awka_getre(_litr3_awka);
  awka_varinit(_litr4_awka); awka_strcpy(_litr4_awka, "/* skip code that is commented out */"); awka_getre(_litr4_awka);
  awka_varinit(_litr5_awka); awka_strcpy(_litr5_awka, "/* strip the call to NEWF - we simulate it later */"); awka_getre(_litr5_awka);
  awka_varinit(_litr6_awka); awka_strcpy(_litr6_awka, "/* strip the call to RETF or RETN - we simulate it later */"); awka_getre(_litr6_awka);
  awka_varinit(_litr7_awka); awka_strcpy(_litr7_awka, "/* pretend this function uses BC - actually it has local vars */"); awka_getre(_litr7_awka);
  awka_varinit(_litr8_awka); awka_strcpy(_litr8_awka, "/* pretend this function uses BC - actually it uses FP */"); awka_getre(_litr8_awka);
  awka_varinit(_litr9_awka); awka_strcpy(_litr9_awka, "/* pretend this function uses BC - acutally it defines a label */"); awka_getre(_litr9_awka);
  awka_varinit(_litr10_awka); awka_strcpy(_litr10_awka, "/* it's probably not necessary to check so far */"); awka_getre(_litr10_awka);
  awka_varinit(_litr11_awka); awka_strcpy(_litr11_awka, "/^[ \t]+jmp[ \t]+#CALA/"); awka_getre(_litr11_awka);
  awka_varinit(_litr12_awka); awka_strcpy(_litr12_awka, "/^[ \t]+calld[ \t]PA,#CALA/"); awka_getre(_litr12_awka);
  awka_varinit(_litr13_awka); awka_strcpy(_litr13_awka, "/* ignore this line and next - this is a function call */"); awka_getre(_litr13_awka);
  awka_varinit(_litr14_awka); awka_strcpy(_litr14_awka, "/* printf(\"skip %s\n\", $0) */"); awka_getre(_litr14_awka);
  awka_varinit(_litr15_awka); awka_strcpy(_litr15_awka, "/^[ \t]+long[ \t]+@/"); awka_getre(_litr15_awka);
  awka_varinit(_litr16_awka); awka_strcpy(_litr16_awka, "/* pretend it uses BC - actually, its address is being taken for some reason (other than a function call) */"); awka_getre(_litr16_awka);
  awka_varinit(_litr17_awka); awka_strcpy(_litr17_awka, "/* printf(\"address taken %s\n\", $0) */"); awka_getre(_litr17_awka);

  if (!_lvar) {
    malloc( &_lvar, 59 * sizeof(a_VAR *) );
    _lvar[0] = _litd0_awka;
    _lvar[1] = _litd1_awka;
    _lvar[2] = _litd2_awka;
    _lvar[3] = _litd3_awka;
    _lvar[4] = _litd4_awka;
    _lvar[5] = _litd5_awka;
    _lvar[6] = _litd6_awka;
    _lvar[7] = _lits0_awka;
    _lvar[8] = _lits1_awka;
    _lvar[9] = _lits2_awka;
    _lvar[10] = _lits3_awka;
    _lvar[11] = _lits4_awka;
    _lvar[12] = _lits5_awka;
    _lvar[13] = _lits6_awka;
    _lvar[14] = _lits7_awka;
    _lvar[15] = _lits8_awka;
    _lvar[16] = _lits9_awka;
    _lvar[17] = _lits10_awka;
    _lvar[18] = _lits11_awka;
    _lvar[19] = _lits12_awka;
    _lvar[20] = _lits13_awka;
    _lvar[21] = _lits14_awka;
    _lvar[22] = _lits15_awka;
    _lvar[23] = _lits16_awka;
    _lvar[24] = _lits17_awka;
    _lvar[25] = _lits18_awka;
    _lvar[26] = _lits19_awka;
    _lvar[27] = _lits20_awka;
    _lvar[28] = _lits21_awka;
    _lvar[29] = _lits22_awka;
    _lvar[30] = _lits23_awka;
    _lvar[31] = _lits24_awka;
    _lvar[32] = _lits25_awka;
    _lvar[33] = _lits26_awka;
    _lvar[34] = _lits27_awka;
    _lvar[35] = _lits28_awka;
    _lvar[36] = _lits29_awka;
    _lvar[37] = _lits30_awka;
    _lvar[38] = _lits31_awka;
    _lvar[39] = _lits32_awka;
    _lvar[40] = _litr0_awka;
    _lvar[41] = _litr1_awka;
    _lvar[42] = _litr2_awka;
    _lvar[43] = _litr3_awka;
    _lvar[44] = _litr4_awka;
    _lvar[45] = _litr5_awka;
    _lvar[46] = _litr6_awka;
    _lvar[47] = _litr7_awka;
    _lvar[48] = _litr8_awka;
    _lvar[49] = _litr9_awka;
    _lvar[50] = _litr10_awka;
    _lvar[51] = _litr11_awka;
    _lvar[52] = _litr12_awka;
    _lvar[53] = _litr13_awka;
    _lvar[54] = _litr14_awka;
    _lvar[55] = _litr15_awka;
    _lvar[56] = _litr16_awka;
    _lvar[57] = _litr17_awka;
    _lvar[58] = NULL;
  }

  malloc( &_gvar, 4 * sizeof(struct gvar_struct) );
  awka_initgvar(0, "f_awk", f_awk);
  awka_initgvar(1, "leaf_awk", leaf_awk);
  awka_initgvar(2, "done_awk", done_awk);
  _gvar[3].name = NULL;
  _gvar[3].var  = NULL;

  malloc( &_awkafn, 1 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = NULL;
  _awkafn[0].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _split_max = 2;
  _split_req = 1;
  _dol0_used = 1;

  BEGIN();
  MAIN();
  END();

  free(_litd0_awka);
  free(_litd1_awka);
  free(_litd2_awka);
  free(_litd3_awka);
  free(_litd4_awka);
  free(_litd5_awka);
  free(_litd6_awka);
  free(_lits0_awka->ptr); free(_lits0_awka);
  free(_lits1_awka->ptr); free(_lits1_awka);
  free(_lits2_awka->ptr); free(_lits2_awka);
  free(_lits3_awka->ptr); free(_lits3_awka);
  free(_lits4_awka->ptr); free(_lits4_awka);
  free(_lits5_awka->ptr); free(_lits5_awka);
  free(_lits6_awka->ptr); free(_lits6_awka);
  free(_lits7_awka->ptr); free(_lits7_awka);
  free(_lits8_awka->ptr); free(_lits8_awka);
  free(_lits9_awka->ptr); free(_lits9_awka);
  free(_lits10_awka->ptr); free(_lits10_awka);
  free(_lits11_awka->ptr); free(_lits11_awka);
  free(_lits12_awka->ptr); free(_lits12_awka);
  free(_lits13_awka->ptr); free(_lits13_awka);
  free(_lits14_awka->ptr); free(_lits14_awka);
  free(_lits15_awka->ptr); free(_lits15_awka);
  free(_lits16_awka->ptr); free(_lits16_awka);
  free(_lits17_awka->ptr); free(_lits17_awka);
  free(_lits18_awka->ptr); free(_lits18_awka);
  free(_lits19_awka->ptr); free(_lits19_awka);
  free(_lits20_awka->ptr); free(_lits20_awka);
  free(_lits21_awka->ptr); free(_lits21_awka);
  free(_lits22_awka->ptr); free(_lits22_awka);
  free(_lits23_awka->ptr); free(_lits23_awka);
  free(_lits24_awka->ptr); free(_lits24_awka);
  free(_lits25_awka->ptr); free(_lits25_awka);
  free(_lits26_awka->ptr); free(_lits26_awka);
  free(_lits27_awka->ptr); free(_lits27_awka);
  free(_lits28_awka->ptr); free(_lits28_awka);
  free(_lits29_awka->ptr); free(_lits29_awka);
  free(_lits30_awka->ptr); free(_lits30_awka);
  free(_lits31_awka->ptr); free(_lits31_awka);
  free(_lits32_awka->ptr); free(_lits32_awka);
  awka_killvar(_litr0_awka); free(_litr0_awka);
  awka_killvar(_litr1_awka); free(_litr1_awka);
  awka_killvar(_litr2_awka); free(_litr2_awka);
  awka_killvar(_litr3_awka); free(_litr3_awka);
  awka_killvar(_litr4_awka); free(_litr4_awka);
  awka_killvar(_litr5_awka); free(_litr5_awka);
  awka_killvar(_litr6_awka); free(_litr6_awka);
  awka_killvar(_litr7_awka); free(_litr7_awka);
  awka_killvar(_litr8_awka); free(_litr8_awka);
  awka_killvar(_litr9_awka); free(_litr9_awka);
  awka_killvar(_litr10_awka); free(_litr10_awka);
  awka_killvar(_litr11_awka); free(_litr11_awka);
  awka_killvar(_litr12_awka); free(_litr12_awka);
  awka_killvar(_litr13_awka); free(_litr13_awka);
  awka_killvar(_litr14_awka); free(_litr14_awka);
  awka_killvar(_litr15_awka); free(_litr15_awka);
  awka_killvar(_litr16_awka); free(_litr16_awka);
  awka_killvar(_litr17_awka); free(_litr17_awka);

  awka_exit(0);
}
