/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>
#include <cat_functions.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;
a_VAR *paren1_awk = NULL;
a_VAR *paren2_awk = NULL;
a_VAR *n_awk = NULL;
a_VAR *addr_awk = NULL;
a_VAR *dest_awk = NULL;

struct gvar_struct *_gvar;

a_VAR **_lvar;
a_VAR *_litd0_awka=NULL, *_litd1_awka=NULL, *_litd2_awka=NULL, *_litd3_awka=NULL, *_litd4_awka=NULL, *_litd5_awka=NULL, *_litd6_awka=NULL;
a_VAR *_lits0_awka=NULL, *_lits1_awka=NULL, *_lits2_awka=NULL, *_lits3_awka=NULL, *_lits4_awka=NULL, *_lits5_awka=NULL, *_lits6_awka=NULL, *_lits7_awka=NULL, *_lits8_awka=NULL, *_lits9_awka=NULL, *_lits10_awka=NULL, *_lits11_awka=NULL, *_lits12_awka=NULL, *_lits13_awka=NULL, *_lits14_awka=NULL, *_lits15_awka=NULL, *_lits16_awka=NULL, *_lits17_awka=NULL, *_lits18_awka=NULL;
a_VAR *_litr0_awka=NULL, *_litr1_awka=NULL, *_litr2_awka=NULL, *_litr3_awka=NULL, *_litr4_awka=NULL, *_litr5_awka=NULL, *_litr6_awka=NULL, *_litr7_awka=NULL, *_litr8_awka=NULL, *_litr9_awka=NULL;
void BEGIN();
void MAIN();

void
BEGIN()
{
  awka_strcpy(a_bivar[a_FS], "[ :()]");

}


void
MAIN()
{
  int i, _curfile;
  if (*(awka_gets(a_bivar[a_FILENAME])) == '\0')
    awka_strcpy(a_bivar[a_FILENAME], "");
  i = setjmp(context);
  while (awka_getline(a_TEMP, awka_dol0(0), awka_gets(a_bivar[a_FILENAME]), FALSE, TRUE)->dval > 0 && awka_setNF())
  {
    if ((awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL))) || awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __72;
      }
      awka_vardblset(n_awk, 0);
      __72:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_vardblset(dest_awk, (awka_getd(bytes_to_hex_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits5_awka));
          goto __241;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits6_awka));
          goto __241;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __241:;
        goto __409;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_varcpy(dest_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits5_awka));
          goto __409;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits6_awka));
          goto __409;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __409:;
    } }
    if ((awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL))) || awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __480;
      }
      awka_vardblset(n_awk, 0);
      __480:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_vardblset(dest_awk, (awka_getd(bytes_to_hex_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits7_awka));
          goto __649;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits8_awka));
          goto __649;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __649:;
        goto __817;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_varcpy(dest_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits7_awka));
          goto __817;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits8_awka));
          goto __817;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __817:;
    } }
    if ((awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL))) || awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __888;
      }
      awka_vardblset(n_awk, 0);
      __888:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_vardblset(dest_awk, (awka_getd(bytes_to_hex_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits9_awka));
          goto __1057;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits10_awka));
          goto __1057;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __1057:;
        goto __1225;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_varcpy(dest_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits9_awka));
          goto __1225;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits10_awka));
          goto __1225;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __1225:;
    } }
    if ((awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL))) || awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __1296;
      }
      awka_vardblset(n_awk, 0);
      __1296:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_vardblset(dest_awk, (awka_getd(bytes_to_hex_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits11_awka));
          goto __1465;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits12_awka));
          goto __1465;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __1465:;
        goto __1633;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_varcpy(dest_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits11_awka));
          goto __1633;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits12_awka));
          goto __1633;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __1633:;
    } }
    if ((awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL))) || awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __1704;
      }
      awka_vardblset(n_awk, 0);
      __1704:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_vardblset(dest_awk, (awka_getd(bytes_to_hex_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits13_awka));
          goto __1873;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits14_awka));
          goto __1873;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __1873:;
        goto __2041;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_varcpy(dest_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits13_awka));
          goto __2041;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits14_awka));
          goto __2041;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __2041:;
    } }
    if ((awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL))) || awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __2112;
      }
      awka_vardblset(n_awk, 0);
      __2112:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_vardblset(dest_awk, (awka_getd(bytes_to_hex_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits15_awka));
          goto __2281;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits16_awka));
          goto __2281;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __2281:;
        goto __2449;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_varcpy(dest_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits15_awka));
          goto __2449;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits16_awka));
          goto __2449;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __2449:;
    } }
    if ((awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL))) || awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __2520;
      }
      awka_vardblset(n_awk, 0);
      __2520:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_vardblset(dest_awk, (awka_getd(bytes_to_hex_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits17_awka));
          goto __2689;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits18_awka));
          goto __2689;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __2689:;
        goto __2857;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        awka_varcpy(dest_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits2_awka, dest_awk, NULL));
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits3_awka, addr_awk, NULL));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((dest_awk->dval) - (awka_getd(addr_awk) + 4))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits17_awka));
          goto __2857;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL);
          awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits4_awka, awka_tmp_dbl2var(((awka_getd(addr_awk) + 4) - (dest_awk->dval))), NULL));
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits18_awka));
          goto __2857;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        __2857:;
    } }
    nextrec:;
  }
}

int
main(int argc, char *argv[])
{
  _max_base_gc = 3;
  _max_fn_gc = 2;

  awka_varinit(paren1_awk);
  awka_varinit(paren2_awk);
  awka_varinit(n_awk);
  awka_varinit(addr_awk);
  awka_varinit(dest_awk);

  awka_varinit(_litd0_awka); awka_setd(_litd0_awka) = 5;
  awka_varinit(_litd1_awka); awka_setd(_litd1_awka) = 1;
  awka_varinit(_litd2_awka); awka_setd(_litd2_awka) = 6;
  awka_varinit(_litd3_awka); awka_setd(_litd3_awka) = 0;
  awka_varinit(_litd4_awka); awka_setd(_litd4_awka) = 16;
  awka_varinit(_litd5_awka); awka_setd(_litd5_awka) = 4;
  awka_varinit(_litd6_awka); awka_setd(_litd6_awka) = 496;
  awka_varinit(_lits0_awka); awka_strcpy(_lits0_awka, "[ :()]");
  awka_varinit(_lits1_awka); awka_strcpy(_lits1_awka, "(");
  awka_varinit(_lits2_awka); awka_strcpy(_lits2_awka, "' dest = %X\n");
  awka_varinit(_lits3_awka); awka_strcpy(_lits3_awka, "' addr = %X\n");
  awka_varinit(_lits4_awka); awka_strcpy(_lits4_awka, "' offs = %d\n");
  awka_varinit(_lits5_awka); awka_strcpy(_lits5_awka, "add");
  awka_varinit(_lits6_awka); awka_strcpy(_lits6_awka, "sub");
  awka_varinit(_lits7_awka); awka_strcpy(_lits7_awka, "if_z add");
  awka_varinit(_lits8_awka); awka_strcpy(_lits8_awka, "if_z sub");
  awka_varinit(_lits9_awka); awka_strcpy(_lits9_awka, "if_nz add");
  awka_varinit(_lits10_awka); awka_strcpy(_lits10_awka, "if_nz sub");
  awka_varinit(_lits11_awka); awka_strcpy(_lits11_awka, "if_ae add");
  awka_varinit(_lits12_awka); awka_strcpy(_lits12_awka, "if_ae sub");
  awka_varinit(_lits13_awka); awka_strcpy(_lits13_awka, "if_a add");
  awka_varinit(_lits14_awka); awka_strcpy(_lits14_awka, "if_a sub");
  awka_varinit(_lits15_awka); awka_strcpy(_lits15_awka, "if_be add");
  awka_varinit(_lits16_awka); awka_strcpy(_lits16_awka, "if_be sub");
  awka_varinit(_lits17_awka); awka_strcpy(_lits17_awka, "if_b add");
  awka_varinit(_lits18_awka); awka_strcpy(_lits18_awka, "if_b sub");
  awka_varinit(_litr0_awka); awka_strcpy(_litr0_awka, "/#JMPA ' Catalina Optimizer /"); awka_getre(_litr0_awka);
  awka_varinit(_litr1_awka); awka_strcpy(_litr1_awka, "/* forward optimization possible */"); awka_getre(_litr1_awka);
  awka_varinit(_litr2_awka); awka_strcpy(_litr2_awka, "/* reverse optimization possible */"); awka_getre(_litr2_awka);
  awka_varinit(_litr3_awka); awka_strcpy(_litr3_awka, "/* printf \"no optimization possible\n\" */"); awka_getre(_litr3_awka);
  awka_varinit(_litr4_awka); awka_strcpy(_litr4_awka, "/#BR_Z ' Catalina Optimizer /"); awka_getre(_litr4_awka);
  awka_varinit(_litr5_awka); awka_strcpy(_litr5_awka, "/#BRNZ ' Catalina Optimizer /"); awka_getre(_litr5_awka);
  awka_varinit(_litr6_awka); awka_strcpy(_litr6_awka, "/#BRAE ' Catalina Optimizer /"); awka_getre(_litr6_awka);
  awka_varinit(_litr7_awka); awka_strcpy(_litr7_awka, "/#BR_A ' Catalina Optimizer /"); awka_getre(_litr7_awka);
  awka_varinit(_litr8_awka); awka_strcpy(_litr8_awka, "/#BRBE ' Catalina Optimizer /"); awka_getre(_litr8_awka);
  awka_varinit(_litr9_awka); awka_strcpy(_litr9_awka, "/#BR_B ' Catalina Optimizer /"); awka_getre(_litr9_awka);

  if (!_lvar) {
    malloc( &_lvar, 37 * sizeof(a_VAR *) );
    _lvar[0] = _litd0_awka;
    _lvar[1] = _litd1_awka;
    _lvar[2] = _litd2_awka;
    _lvar[3] = _litd3_awka;
    _lvar[4] = _litd4_awka;
    _lvar[5] = _litd5_awka;
    _lvar[6] = _litd6_awka;
    _lvar[7] = _lits0_awka;
    _lvar[8] = _lits1_awka;
    _lvar[9] = _lits2_awka;
    _lvar[10] = _lits3_awka;
    _lvar[11] = _lits4_awka;
    _lvar[12] = _lits5_awka;
    _lvar[13] = _lits6_awka;
    _lvar[14] = _lits7_awka;
    _lvar[15] = _lits8_awka;
    _lvar[16] = _lits9_awka;
    _lvar[17] = _lits10_awka;
    _lvar[18] = _lits11_awka;
    _lvar[19] = _lits12_awka;
    _lvar[20] = _lits13_awka;
    _lvar[21] = _lits14_awka;
    _lvar[22] = _lits15_awka;
    _lvar[23] = _lits16_awka;
    _lvar[24] = _lits17_awka;
    _lvar[25] = _lits18_awka;
    _lvar[26] = _litr0_awka;
    _lvar[27] = _litr1_awka;
    _lvar[28] = _litr2_awka;
    _lvar[29] = _litr3_awka;
    _lvar[30] = _litr4_awka;
    _lvar[31] = _litr5_awka;
    _lvar[32] = _litr6_awka;
    _lvar[33] = _litr7_awka;
    _lvar[34] = _litr8_awka;
    _lvar[35] = _litr9_awka;
    _lvar[36] = NULL;
  }

  malloc( &_gvar, 6 * sizeof(struct gvar_struct) );
  awka_initgvar(0, "paren1_awk", paren1_awk);
  awka_initgvar(1, "paren2_awk", paren2_awk);
  awka_initgvar(2, "n_awk", n_awk);
  awka_initgvar(3, "addr_awk", addr_awk);
  awka_initgvar(4, "dest_awk", dest_awk);
  _gvar[5].name = NULL;
  _gvar[5].var  = NULL;

  malloc( &_awkafn, 1 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = NULL;
  _awkafn[0].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _split_max = 8;
  _split_req = 1;
  _dol0_used = 1;

  BEGIN();
  MAIN();

  free(_litd0_awka);
  free(_litd1_awka);
  free(_litd2_awka);
  free(_litd3_awka);
  free(_litd4_awka);
  free(_litd5_awka);
  free(_litd6_awka);
  free(_lits0_awka->ptr); free(_lits0_awka);
  free(_lits1_awka->ptr); free(_lits1_awka);
  free(_lits2_awka->ptr); free(_lits2_awka);
  free(_lits3_awka->ptr); free(_lits3_awka);
  free(_lits4_awka->ptr); free(_lits4_awka);
  free(_lits5_awka->ptr); free(_lits5_awka);
  free(_lits6_awka->ptr); free(_lits6_awka);
  free(_lits7_awka->ptr); free(_lits7_awka);
  free(_lits8_awka->ptr); free(_lits8_awka);
  free(_lits9_awka->ptr); free(_lits9_awka);
  free(_lits10_awka->ptr); free(_lits10_awka);
  free(_lits11_awka->ptr); free(_lits11_awka);
  free(_lits12_awka->ptr); free(_lits12_awka);
  free(_lits13_awka->ptr); free(_lits13_awka);
  free(_lits14_awka->ptr); free(_lits14_awka);
  free(_lits15_awka->ptr); free(_lits15_awka);
  free(_lits16_awka->ptr); free(_lits16_awka);
  free(_lits17_awka->ptr); free(_lits17_awka);
  free(_lits18_awka->ptr); free(_lits18_awka);
  awka_killvar(_litr0_awka); free(_litr0_awka);
  awka_killvar(_litr1_awka); free(_litr1_awka);
  awka_killvar(_litr2_awka); free(_litr2_awka);
  awka_killvar(_litr3_awka); free(_litr3_awka);
  awka_killvar(_litr4_awka); free(_litr4_awka);
  awka_killvar(_litr5_awka); free(_litr5_awka);
  awka_killvar(_litr6_awka); free(_litr6_awka);
  awka_killvar(_litr7_awka); free(_litr7_awka);
  awka_killvar(_litr8_awka); free(_litr8_awka);
  awka_killvar(_litr9_awka); free(_litr9_awka);

  awka_exit(0);
}
