/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>
#include <cat_functions.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;
a_VAR *line1_awk = NULL;
a_VAR *dst_awk = NULL;
a_VAR *val_awk = NULL;
a_VAR *len_awk = NULL;
a_VAR *str_awk = NULL;
a_VAR *i_awk = NULL;
a_VAR *c_awk = NULL;

struct gvar_struct *_gvar;

a_VAR **_lvar;
a_VAR *_litd0_awka=NULL, *_litd1_awka=NULL, *_litd2_awka=NULL, *_litd3_awka=NULL, *_litd4_awka=NULL, *_litd5_awka=NULL, *_litd6_awka=NULL, *_litd7_awka=NULL, *_litd8_awka=NULL;
a_VAR *_lits0_awka=NULL, *_lits1_awka=NULL, *_lits2_awka=NULL, *_lits3_awka=NULL, *_lits4_awka=NULL, *_lits5_awka=NULL, *_lits6_awka=NULL, *_lits7_awka=NULL, *_lits8_awka=NULL, *_lits9_awka=NULL, *_lits10_awka=NULL, *_lits11_awka=NULL, *_lits12_awka=NULL, *_lits13_awka=NULL, *_lits14_awka=NULL, *_lits15_awka=NULL, *_lits16_awka=NULL, *_lits17_awka=NULL, *_lits18_awka=NULL;
a_VAR *_litr0_awka=NULL, *_litr1_awka=NULL, *_litr2_awka=NULL;
void MAIN();

void
MAIN()
{
  int i, _curfile;
  if (*(awka_gets(a_bivar[a_FILENAME])) == '\0')
    awka_strcpy(a_bivar[a_FILENAME], "");
  i = setjmp(context);
  while (awka_getline(a_TEMP, awka_dol0(0), awka_gets(a_bivar[a_FILENAME]), FALSE, TRUE)->dval > 0 && awka_setNF())
  {
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd0_awka)), "}"))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL)))
    {
      awka_varcpy(line1_awk, awka_dol0(0));
      awka_varcpy(dst_awk, awka_doln(4, 0));
      if (!strcmp(awka_gets(dst_awk), "("))
      {
        awka_varcpy(dst_awk, awka_doln(5, 0));
      }
      awka_varcpy(dst_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, dst_awk, _lits1_awka)));
      awka_varcpy(dst_awk, awka_left(a_TEMP, dst_awk, _litd1_awka));
      awka_varcpy(dst_awk, awka_rtrim(a_TEMP, awka_arg2(a_TEMP, dst_awk, _lits2_awka)));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
      {
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      if (!strcmp(awka_gets(awka_doln(1, 0)), "long"))
      {
        if (((strcmp(awka_gets(awka_left(a_TEMP, awka_doln(2, 0), _litd0_awka)), "0") >= 0)) && (strcmp(awka_gets(awka_left(a_TEMP, awka_doln(2, 0), _litd0_awka)), "9") <= 0))
        {
          awka_vardblset(val_awk, (0 + awka_getd(awka_doln(2, 0))));
          if ((val_awk->dval >= 0) && val_awk->dval <= 31)
          {
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat5(a_TEMP, _lits7_awka, dst_awk, _lits8_awka, val_awk, _lits9_awka)));
            goto __237;
          }
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
          __237:;
          goto __959;
        }
        if (!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(2, 0), _litd0_awka)), "-"))
        {
          awka_vardblset(val_awk, ((0) + awka_getd(awka_right(a_TEMP, awka_doln(2, 0), awka_tmp_dbl2var((awka_length(awka_doln(2, 0)) - (1)))))));
          if ((val_awk->dval >= 0) && val_awk->dval <= 31)
          {
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat5(a_TEMP, _lits11_awka, dst_awk, _lits8_awka, val_awk, _lits9_awka)));
            goto __323;
          }
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
          __323:;
          goto __959;
        }
        if ((!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(2, 0), _litd4_awka)), "$ffffff")) || !strcmp(awka_gets(awka_left(a_TEMP, awka_doln(2, 0), _litd4_awka)), "$FFFFFF"))
        {
          awka_vardblset(len_awk, (awka_length(awka_doln(2, 0)) - (7)));
          if (len_awk->dval > 0)
          {
            awka_varcpy(str_awk, awka_right(a_TEMP, awka_doln(2, 0), len_awk));
            awka_vardblset(len_awk, awka_length(str_awk));
            awka_vardblset(val_awk, 0);
            awka_vardblset(i_awk, 0);
            while (i_awk->dval < len_awk->dval)
            {
              awka_varcpy(c_awk, awka_left(a_TEMP, str_awk, _litd0_awka));
              if (awka_length(str_awk) > awka_getd(_litd0_awka))
              {
                awka_varcpy(str_awk, awka_right(a_TEMP, str_awk, awka_tmp_dbl2var((awka_length(str_awk) - (1)))));
              }
              if (((strcmp(awka_gets(c_awk), "0") >= 0)) && (strcmp(awka_gets(c_awk), "9") <= 0))
              {
                awka_vardblset(val_awk, ((16 * val_awk->dval) + (awka_getd(c_awk))));
                goto __566;
              }
              if (((strcmp(awka_gets(c_awk), "a") >= 0)) && (strcmp(awka_gets(c_awk), "f") <= 0))
              {
                awka_vardblset(val_awk, (((16 * val_awk->dval)) + ((((awka_getd(awka_ascii(a_TEMP, awka_arg1(a_TEMP, c_awk)))) - (awka_getd(awka_ascii(a_TEMP, awka_arg1(a_TEMP, _lits14_awka))))) + (10)))));
                goto __566;
              }
              if (((strcmp(awka_gets(c_awk), "A") >= 0)) && (strcmp(awka_gets(c_awk), "F") <= 0))
              {
                awka_vardblset(val_awk, (((16 * val_awk->dval)) + ((((awka_getd(awka_ascii(a_TEMP, awka_arg1(a_TEMP, c_awk)))) - (awka_getd(awka_ascii(a_TEMP, awka_arg1(a_TEMP, _lits16_awka))))) + (10)))));
                goto __566;
              }
              break;
              __566:;
              awka_poi(i_awk);
            }
            if ((((len_awk->dval == 2) &&  val_awk->dval >= 0)) && (256 - val_awk->dval) <= awka_getd(_litd3_awka))
            {
              awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat5(a_TEMP, _lits11_awka, dst_awk, _lits8_awka, awka_tmp_dbl2var((256 - val_awk->dval)), _lits9_awka)));
              goto __640;
            }
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
            __640:;
            goto __654;
          }
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
          __654:;
          goto __959;
        }
        if (!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(2, 0), _litd0_awka)), "$"))
        {
          awka_vardblset(len_awk, (awka_length(awka_doln(2, 0)) - (1)));
          if (len_awk->dval > 0)
          {
            awka_varcpy(str_awk, awka_right(a_TEMP, awka_doln(2, 0), len_awk));
            awka_vardblset(val_awk, 0);
            awka_vardblset(i_awk, 0);
            while (i_awk->dval < len_awk->dval)
            {
              awka_varcpy(c_awk, awka_left(a_TEMP, str_awk, _litd0_awka));
              if (awka_length(str_awk) > awka_getd(_litd0_awka))
              {
                awka_varcpy(str_awk, awka_right(a_TEMP, str_awk, awka_tmp_dbl2var((awka_length(str_awk) - (1)))));
              }
              if (((strcmp(awka_gets(c_awk), "0") >= 0)) && (strcmp(awka_gets(c_awk), "9") <= 0))
              {
                awka_vardblset(val_awk, ((16 * val_awk->dval) + (awka_getd(c_awk))));
                goto __872;
              }
              if (((strcmp(awka_gets(c_awk), "a") >= 0)) && (strcmp(awka_gets(c_awk), "f") <= 0))
              {
                awka_vardblset(val_awk, (((16 * val_awk->dval)) + ((((awka_getd(awka_ascii(a_TEMP, awka_arg1(a_TEMP, c_awk)))) - (awka_getd(awka_ascii(a_TEMP, awka_arg1(a_TEMP, _lits14_awka))))) + (10)))));
                goto __872;
              }
              if (((strcmp(awka_gets(c_awk), "A") >= 0)) && (strcmp(awka_gets(c_awk), "F") <= 0))
              {
                awka_vardblset(val_awk, (((16 * val_awk->dval)) + ((((awka_getd(awka_ascii(a_TEMP, awka_arg1(a_TEMP, c_awk)))) - (awka_getd(awka_ascii(a_TEMP, awka_arg1(a_TEMP, _lits16_awka))))) + (10)))));
                goto __872;
              }
              break;
              __872:;
              awka_poi(i_awk);
            }
            if ((val_awk->dval >= 0) && val_awk->dval <= 31)
            {
              awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat5(a_TEMP, _lits7_awka, dst_awk, _lits8_awka, val_awk, _lits9_awka)));
              goto __931;
            }
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
            __931:;
            goto __945;
          }
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
          __945:;
          goto __959;
        }
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        __959:;
        goto __973;
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, line1_awk));
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __973:;
      goto nextrec;
    }
    awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
    nextrec:;
  }
}

int
main(int argc, char *argv[])
{
  _max_base_gc = 7;
  _max_fn_gc = 2;

  awka_varinit(line1_awk);
  awka_varinit(dst_awk);
  awka_varinit(val_awk);
  awka_varinit(len_awk);
  awka_varinit(str_awk);
  awka_varinit(i_awk);
  awka_varinit(c_awk);

  awka_varinit(_litd0_awka); awka_setd(_litd0_awka) = 1;
  awka_varinit(_litd1_awka); awka_setd(_litd1_awka) = 3;
  awka_varinit(_litd2_awka); awka_setd(_litd2_awka) = 0;
  awka_varinit(_litd3_awka); awka_setd(_litd3_awka) = 31;
  awka_varinit(_litd4_awka); awka_setd(_litd4_awka) = 7;
  awka_varinit(_litd5_awka); awka_setd(_litd5_awka) = 16;
  awka_varinit(_litd6_awka); awka_setd(_litd6_awka) = 10;
  awka_varinit(_litd7_awka); awka_setd(_litd7_awka) = 2;
  awka_varinit(_litd8_awka); awka_setd(_litd8_awka) = 256;
  awka_varinit(_lits0_awka); awka_strcpy(_lits0_awka, "}");
  awka_varinit(_lits1_awka); awka_strcpy(_lits1_awka, "(");
  awka_varinit(_lits2_awka); awka_strcpy(_lits2_awka, ")<");
  awka_varinit(_lits3_awka); awka_strcpy(_lits3_awka, "alignl");
  awka_varinit(_lits4_awka); awka_strcpy(_lits4_awka, "long");
  awka_varinit(_lits5_awka); awka_strcpy(_lits5_awka, "0");
  awka_varinit(_lits6_awka); awka_strcpy(_lits6_awka, "9");
  awka_varinit(_lits7_awka); awka_strcpy(_lits7_awka, " word I16A_MOVI + (");
  awka_varinit(_lits8_awka); awka_strcpy(_lits8_awka, ")<<D16A + (");
  awka_varinit(_lits9_awka); awka_strcpy(_lits9_awka, ")<<S16A ' Catalina optimized load\n");
  awka_varinit(_lits10_awka); awka_strcpy(_lits10_awka, "-");
  awka_varinit(_lits11_awka); awka_strcpy(_lits11_awka, " word I16A_NEGI + (");
  awka_varinit(_lits12_awka); awka_strcpy(_lits12_awka, "$ffffff");
  awka_varinit(_lits13_awka); awka_strcpy(_lits13_awka, "$FFFFFF");
  awka_varinit(_lits14_awka); awka_strcpy(_lits14_awka, "a");
  awka_varinit(_lits15_awka); awka_strcpy(_lits15_awka, "f");
  awka_varinit(_lits16_awka); awka_strcpy(_lits16_awka, "A");
  awka_varinit(_lits17_awka); awka_strcpy(_lits17_awka, "F");
  awka_varinit(_lits18_awka); awka_strcpy(_lits18_awka, "$");
  awka_varinit(_litr0_awka); awka_strcpy(_litr0_awka, "/^'/"); awka_getre(_litr0_awka);
  awka_varinit(_litr1_awka); awka_strcpy(_litr1_awka, "/^{/"); awka_getre(_litr1_awka);
  awka_varinit(_litr2_awka); awka_strcpy(_litr2_awka, "/[ \t]+word[ \t]+I16B_LODL/"); awka_getre(_litr2_awka);

  if (!_lvar) {
    malloc( &_lvar, 32 * sizeof(a_VAR *) );
    _lvar[0] = _litd0_awka;
    _lvar[1] = _litd1_awka;
    _lvar[2] = _litd2_awka;
    _lvar[3] = _litd3_awka;
    _lvar[4] = _litd4_awka;
    _lvar[5] = _litd5_awka;
    _lvar[6] = _litd6_awka;
    _lvar[7] = _litd7_awka;
    _lvar[8] = _litd8_awka;
    _lvar[9] = _lits0_awka;
    _lvar[10] = _lits1_awka;
    _lvar[11] = _lits2_awka;
    _lvar[12] = _lits3_awka;
    _lvar[13] = _lits4_awka;
    _lvar[14] = _lits5_awka;
    _lvar[15] = _lits6_awka;
    _lvar[16] = _lits7_awka;
    _lvar[17] = _lits8_awka;
    _lvar[18] = _lits9_awka;
    _lvar[19] = _lits10_awka;
    _lvar[20] = _lits11_awka;
    _lvar[21] = _lits12_awka;
    _lvar[22] = _lits13_awka;
    _lvar[23] = _lits14_awka;
    _lvar[24] = _lits15_awka;
    _lvar[25] = _lits16_awka;
    _lvar[26] = _lits17_awka;
    _lvar[27] = _lits18_awka;
    _lvar[28] = _litr0_awka;
    _lvar[29] = _litr1_awka;
    _lvar[30] = _litr2_awka;
    _lvar[31] = NULL;
  }

  malloc( &_gvar, 8 * sizeof(struct gvar_struct) );
  awka_initgvar(0, "line1_awk", line1_awk);
  awka_initgvar(1, "dst_awk", dst_awk);
  awka_initgvar(2, "val_awk", val_awk);
  awka_initgvar(3, "len_awk", len_awk);
  awka_initgvar(4, "str_awk", str_awk);
  awka_initgvar(5, "i_awk", i_awk);
  awka_initgvar(6, "c_awk", c_awk);
  _gvar[7].name = NULL;
  _gvar[7].var  = NULL;

  malloc( &_awkafn, 1 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = NULL;
  _awkafn[0].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _split_max = 5;
  _split_req = 1;
  _dol0_used = 1;

  MAIN();

  free(_litd0_awka);
  free(_litd1_awka);
  free(_litd2_awka);
  free(_litd3_awka);
  free(_litd4_awka);
  free(_litd5_awka);
  free(_litd6_awka);
  free(_litd7_awka);
  free(_litd8_awka);
  free(_lits0_awka->ptr); free(_lits0_awka);
  free(_lits1_awka->ptr); free(_lits1_awka);
  free(_lits2_awka->ptr); free(_lits2_awka);
  free(_lits3_awka->ptr); free(_lits3_awka);
  free(_lits4_awka->ptr); free(_lits4_awka);
  free(_lits5_awka->ptr); free(_lits5_awka);
  free(_lits6_awka->ptr); free(_lits6_awka);
  free(_lits7_awka->ptr); free(_lits7_awka);
  free(_lits8_awka->ptr); free(_lits8_awka);
  free(_lits9_awka->ptr); free(_lits9_awka);
  free(_lits10_awka->ptr); free(_lits10_awka);
  free(_lits11_awka->ptr); free(_lits11_awka);
  free(_lits12_awka->ptr); free(_lits12_awka);
  free(_lits13_awka->ptr); free(_lits13_awka);
  free(_lits14_awka->ptr); free(_lits14_awka);
  free(_lits15_awka->ptr); free(_lits15_awka);
  free(_lits16_awka->ptr); free(_lits16_awka);
  free(_lits17_awka->ptr); free(_lits17_awka);
  free(_lits18_awka->ptr); free(_lits18_awka);
  awka_killvar(_litr0_awka); free(_litr0_awka);
  awka_killvar(_litr1_awka); free(_litr1_awka);
  awka_killvar(_litr2_awka); free(_litr2_awka);

  awka_exit(0);
}
