/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>
#include <cat_functions.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;
a_VAR *paren1_awk = NULL;
a_VAR *paren2_awk = NULL;
a_VAR *n_awk = NULL;
a_VAR *addr_awk = NULL;
a_VAR *dest_awk = NULL;

struct gvar_struct *_gvar;

a_VAR **_lvar;
a_VAR *_litd0_awka=NULL, *_litd1_awka=NULL, *_litd2_awka=NULL, *_litd3_awka=NULL, *_litd4_awka=NULL, *_litd5_awka=NULL, *_litd6_awka=NULL;
a_VAR *_lits0_awka=NULL, *_lits1_awka=NULL, *_lits2_awka=NULL, *_lits3_awka=NULL, *_lits4_awka=NULL, *_lits5_awka=NULL, *_lits6_awka=NULL, *_lits7_awka=NULL, *_lits8_awka=NULL, *_lits9_awka=NULL;
a_VAR *_litr0_awka=NULL, *_litr1_awka=NULL, *_litr2_awka=NULL, *_litr3_awka=NULL, *_litr4_awka=NULL, *_litr5_awka=NULL, *_litr6_awka=NULL, *_litr7_awka=NULL, *_litr8_awka=NULL, *_litr9_awka=NULL, *_litr10_awka=NULL, *_litr11_awka=NULL;
void BEGIN();
void MAIN();

void
BEGIN()
{
  awka_strcpy(a_bivar[a_FS], "[ :()]");

}


void
MAIN()
{
  int i, _curfile;
  if (*(awka_gets(a_bivar[a_FILENAME])) == '\0')
    awka_strcpy(a_bivar[a_FILENAME], "");
  i = setjmp(context);
  while (awka_getline(a_TEMP, awka_dol0(0), awka_gets(a_bivar[a_FILENAME]), FALSE, TRUE)->dval > 0 && awka_setNF())
  {
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL)))
    {
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL)))
    {
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd0_awka)), "}"))
      {
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __104;
      }
      awka_vardblset(n_awk, 0);
      __104:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_vardblset(dest_awk, (awka_getd(bytes_to_addr24_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits3_awka));
          goto __222;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits3_awka));
          goto __222;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __222:;
        goto __339;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_varcpy(dest_awk, str_to_addr24_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits3_awka));
          goto __339;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits3_awka));
          goto __339;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __339:;
    } }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __404;
      }
      awka_vardblset(n_awk, 0);
      __404:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_vardblset(dest_awk, (awka_getd(bytes_to_addr24_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits4_awka));
          goto __522;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits4_awka));
          goto __522;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __522:;
        goto __639;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_varcpy(dest_awk, str_to_addr24_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits4_awka));
          goto __639;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits4_awka));
          goto __639;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __639:;
    } }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __704;
      }
      awka_vardblset(n_awk, 0);
      __704:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_vardblset(dest_awk, (awka_getd(bytes_to_addr24_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits5_awka));
          goto __822;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits5_awka));
          goto __822;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __822:;
        goto __939;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_varcpy(dest_awk, str_to_addr24_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits5_awka));
          goto __939;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits5_awka));
          goto __939;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __939:;
    } }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __1004;
      }
      awka_vardblset(n_awk, 0);
      __1004:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_vardblset(dest_awk, (awka_getd(bytes_to_addr24_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits6_awka));
          goto __1122;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits6_awka));
          goto __1122;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __1122:;
        goto __1239;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_varcpy(dest_awk, str_to_addr24_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits6_awka));
          goto __1239;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits6_awka));
          goto __1239;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __1239:;
    } }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __1304;
      }
      awka_vardblset(n_awk, 0);
      __1304:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_vardblset(dest_awk, (awka_getd(bytes_to_addr24_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits7_awka));
          goto __1422;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits7_awka));
          goto __1422;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __1422:;
        goto __1539;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_varcpy(dest_awk, str_to_addr24_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits7_awka));
          goto __1539;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits7_awka));
          goto __1539;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __1539:;
    } }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr10_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __1604;
      }
      awka_vardblset(n_awk, 0);
      __1604:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_vardblset(dest_awk, (awka_getd(bytes_to_addr24_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits8_awka));
          goto __1722;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits8_awka));
          goto __1722;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __1722:;
        goto __1839;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_varcpy(dest_awk, str_to_addr24_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits8_awka));
          goto __1839;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits8_awka));
          goto __1839;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __1839:;
    } }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr11_awka, NULL)))
    {
      awka_strcpy(paren1_awk, awka_substr(a_TEMP, awka_dol0(0), 5, 1)->ptr);
      awka_strcpy(paren2_awk, awka_substr(a_TEMP, awka_dol0(0), 6, 1)->ptr);
      if ((!strcmp(paren1_awk->ptr, "(")) || !strcmp(paren2_awk->ptr, "("))
      {
        awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
        goto __1904;
      }
      awka_vardblset(n_awk, 0);
      __1904:;
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_vardblset(dest_awk, (awka_getd(bytes_to_addr24_fn(awka_vararg(a_TEMP, awka_doln(5, 0), awka_doln(6, 0), awka_doln(7, 0), awka_doln(8, 0), NULL))) + (16)));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits9_awka));
          goto __2022;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits9_awka));
          goto __2022;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __2022:;
        goto __2139;
      }
      awka_varcpy(n_awk, candidate_id_fn(awka_arg1(a_TEMP, awka_dol0(0))));
      if (n_awk->dval > 0)
      {
        awka_varcpy(addr_awk, str_to_hex_fn(awka_arg1(a_TEMP, awka_doln(1, 0))));
        awka_varcpy(dest_awk, str_to_addr24_fn(awka_arg1(a_TEMP, awka_doln(6, 0))));
        if ((dest_awk->dval > (awka_getd(addr_awk) + 4)) && ((dest_awk->dval) - (awka_getd(addr_awk) + 4)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits9_awka));
          goto __2139;
        }
        if ((dest_awk->dval < (awka_getd(addr_awk) + 4)) && ((awka_getd(addr_awk) + 4) - (dest_awk->dval)) < awka_getd(_litd6_awka))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg2(a_TEMP, n_awk, _lits9_awka));
          goto __2139;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
        __2139:;
    } }
    nextrec:;
  }
}

int
main(int argc, char *argv[])
{
  _max_base_gc = 3;
  _max_fn_gc = 2;

  awka_varinit(paren1_awk);
  awka_varinit(paren2_awk);
  awka_varinit(n_awk);
  awka_varinit(addr_awk);
  awka_varinit(dest_awk);

  awka_varinit(_litd0_awka); awka_setd(_litd0_awka) = 1;
  awka_varinit(_litd1_awka); awka_setd(_litd1_awka) = 5;
  awka_varinit(_litd2_awka); awka_setd(_litd2_awka) = 6;
  awka_varinit(_litd3_awka); awka_setd(_litd3_awka) = 0;
  awka_varinit(_litd4_awka); awka_setd(_litd4_awka) = 16;
  awka_varinit(_litd5_awka); awka_setd(_litd5_awka) = 4;
  awka_varinit(_litd6_awka); awka_setd(_litd6_awka) = 240;
  awka_varinit(_lits0_awka); awka_strcpy(_lits0_awka, "[ :()]");
  awka_varinit(_lits1_awka); awka_strcpy(_lits1_awka, "}");
  awka_varinit(_lits2_awka); awka_strcpy(_lits2_awka, "(");
  awka_varinit(_lits3_awka); awka_strcpy(_lits3_awka, "word I16B_JMPR");
  awka_varinit(_lits4_awka); awka_strcpy(_lits4_awka, "word I16B_RJ_Z");
  awka_varinit(_lits5_awka); awka_strcpy(_lits5_awka, "word I16B_RJNZ");
  awka_varinit(_lits6_awka); awka_strcpy(_lits6_awka, "word I16B_RJ_A");
  awka_varinit(_lits7_awka); awka_strcpy(_lits7_awka, "word I16B_RJAE");
  awka_varinit(_lits8_awka); awka_strcpy(_lits8_awka, "word I16B_RJ_B");
  awka_varinit(_lits9_awka); awka_strcpy(_lits9_awka, "word I16B_RJBE");
  awka_varinit(_litr0_awka); awka_strcpy(_litr0_awka, "/^'/"); awka_getre(_litr0_awka);
  awka_varinit(_litr1_awka); awka_strcpy(_litr1_awka, "/^{/"); awka_getre(_litr1_awka);
  awka_varinit(_litr2_awka); awka_strcpy(_litr2_awka, "/[ \t]+long[ \t]+I32_JMPA/"); awka_getre(_litr2_awka);
  awka_varinit(_litr3_awka); awka_strcpy(_litr3_awka, "/* forward optimization possible */"); awka_getre(_litr3_awka);
  awka_varinit(_litr4_awka); awka_strcpy(_litr4_awka, "/* reverse optimization possible */"); awka_getre(_litr4_awka);
  awka_varinit(_litr5_awka); awka_strcpy(_litr5_awka, "/* printf \"no optimization possible\n\" */"); awka_getre(_litr5_awka);
  awka_varinit(_litr6_awka); awka_strcpy(_litr6_awka, "/[ \t]+long[ \t]+I32_BR_Z/"); awka_getre(_litr6_awka);
  awka_varinit(_litr7_awka); awka_strcpy(_litr7_awka, "/[ \t]+long[ \t]+I32_BRNZ/"); awka_getre(_litr7_awka);
  awka_varinit(_litr8_awka); awka_strcpy(_litr8_awka, "/[ \t]+long[ \t]+I32_BR_A/"); awka_getre(_litr8_awka);
  awka_varinit(_litr9_awka); awka_strcpy(_litr9_awka, "/[ \t]+long[ \t]+I32_BRAE/"); awka_getre(_litr9_awka);
  awka_varinit(_litr10_awka); awka_strcpy(_litr10_awka, "/[ \t]+long[ \t]+I32_BR_B/"); awka_getre(_litr10_awka);
  awka_varinit(_litr11_awka); awka_strcpy(_litr11_awka, "/[ \t]+long[ \t]+I32_BRBE/"); awka_getre(_litr11_awka);

  if (!_lvar) {
    malloc( &_lvar, 30 * sizeof(a_VAR *) );
    _lvar[0] = _litd0_awka;
    _lvar[1] = _litd1_awka;
    _lvar[2] = _litd2_awka;
    _lvar[3] = _litd3_awka;
    _lvar[4] = _litd4_awka;
    _lvar[5] = _litd5_awka;
    _lvar[6] = _litd6_awka;
    _lvar[7] = _lits0_awka;
    _lvar[8] = _lits1_awka;
    _lvar[9] = _lits2_awka;
    _lvar[10] = _lits3_awka;
    _lvar[11] = _lits4_awka;
    _lvar[12] = _lits5_awka;
    _lvar[13] = _lits6_awka;
    _lvar[14] = _lits7_awka;
    _lvar[15] = _lits8_awka;
    _lvar[16] = _lits9_awka;
    _lvar[17] = _litr0_awka;
    _lvar[18] = _litr1_awka;
    _lvar[19] = _litr2_awka;
    _lvar[20] = _litr3_awka;
    _lvar[21] = _litr4_awka;
    _lvar[22] = _litr5_awka;
    _lvar[23] = _litr6_awka;
    _lvar[24] = _litr7_awka;
    _lvar[25] = _litr8_awka;
    _lvar[26] = _litr9_awka;
    _lvar[27] = _litr10_awka;
    _lvar[28] = _litr11_awka;
    _lvar[29] = NULL;
  }

  malloc( &_gvar, 6 * sizeof(struct gvar_struct) );
  awka_initgvar(0, "paren1_awk", paren1_awk);
  awka_initgvar(1, "paren2_awk", paren2_awk);
  awka_initgvar(2, "n_awk", n_awk);
  awka_initgvar(3, "addr_awk", addr_awk);
  awka_initgvar(4, "dest_awk", dest_awk);
  _gvar[5].name = NULL;
  _gvar[5].var  = NULL;

  malloc( &_awkafn, 1 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = NULL;
  _awkafn[0].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _split_max = 8;
  _split_req = 1;
  _dol0_used = 1;

  BEGIN();
  MAIN();

  free(_litd0_awka);
  free(_litd1_awka);
  free(_litd2_awka);
  free(_litd3_awka);
  free(_litd4_awka);
  free(_litd5_awka);
  free(_litd6_awka);
  free(_lits0_awka->ptr); free(_lits0_awka);
  free(_lits1_awka->ptr); free(_lits1_awka);
  free(_lits2_awka->ptr); free(_lits2_awka);
  free(_lits3_awka->ptr); free(_lits3_awka);
  free(_lits4_awka->ptr); free(_lits4_awka);
  free(_lits5_awka->ptr); free(_lits5_awka);
  free(_lits6_awka->ptr); free(_lits6_awka);
  free(_lits7_awka->ptr); free(_lits7_awka);
  free(_lits8_awka->ptr); free(_lits8_awka);
  free(_lits9_awka->ptr); free(_lits9_awka);
  awka_killvar(_litr0_awka); free(_litr0_awka);
  awka_killvar(_litr1_awka); free(_litr1_awka);
  awka_killvar(_litr2_awka); free(_litr2_awka);
  awka_killvar(_litr3_awka); free(_litr3_awka);
  awka_killvar(_litr4_awka); free(_litr4_awka);
  awka_killvar(_litr5_awka); free(_litr5_awka);
  awka_killvar(_litr6_awka); free(_litr6_awka);
  awka_killvar(_litr7_awka); free(_litr7_awka);
  awka_killvar(_litr8_awka); free(_litr8_awka);
  awka_killvar(_litr9_awka); free(_litr9_awka);
  awka_killvar(_litr10_awka); free(_litr10_awka);
  awka_killvar(_litr11_awka); free(_litr11_awka);

  awka_exit(0);
}
