/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>
#include <cat_functions.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;
a_VAR *code_awk = NULL;
a_VAR *long_awk = NULL;
a_VAR *alignment_awk = NULL;
a_VAR *post_align_awk = NULL;

struct gvar_struct *_gvar;

a_VAR **_lvar;
a_VAR *_litd0_awka=NULL, *_litd1_awka=NULL, *_litd2_awka=NULL, *_litd3_awka=NULL;
a_VAR *_lits0_awka=NULL, *_lits1_awka=NULL, *_lits2_awka=NULL, *_lits3_awka=NULL, *_lits4_awka=NULL, *_lits5_awka=NULL, *_lits6_awka=NULL, *_lits7_awka=NULL, *_lits8_awka=NULL, *_lits9_awka=NULL, *_lits10_awka=NULL, *_lits11_awka=NULL, *_lits12_awka=NULL;
a_VAR *_litr0_awka=NULL, *_litr1_awka=NULL;
void BEGIN();
void MAIN();

void
BEGIN()
{
  awka_vardblset(code_awk, 0);
  awka_vardblset(long_awk, 0);
  awka_vardblset(alignment_awk, 4);
  awka_vardblset(post_align_awk, 0);

}


void
MAIN()
{
  int i, _curfile;
  if (*(awka_gets(a_bivar[a_FILENAME])) == '\0')
    awka_strcpy(a_bivar[a_FILENAME], "");
  i = setjmp(context);
  while (awka_getline(a_TEMP, awka_dol0(0), awka_gets(a_bivar[a_FILENAME]), FALSE, TRUE)->dval > 0 && awka_setNF())
  {
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), "}"))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        if (awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE)->dval <= 0)
        {
          break;
        }
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
    {
      awka_vardblset(alignment_awk, 4);
      goto __257;
    }
    if (!strcmp(awka_gets(awka_doln(1, 0)), "alignw"))
    {
      awka_vardblset(alignment_awk, 2);
      goto __257;
    }
    if (!strcmp(awka_gets(awka_doln(1, 0)), "byte"))
    {
      awka_vardblset(alignment_awk, 1);
      goto __257;
    }
    if (!strcmp(awka_gets(awka_doln(1, 0)), "word"))
    {
      if ((alignment_awk->dval != 4) && alignment_awk->dval != 2)
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits5_awka));
      }
      awka_vardblset(alignment_awk, 2);
      if ((!strcmp(awka_gets(awka_doln(2, 0)), "I16B_EXEC")) || !strcmp(awka_gets(awka_doln(2, 0)), "I16B_PASM"))
      {
        awka_vardblset(post_align_awk, 1);
      }
      goto __257;
    }
    if ((!strcmp(awka_gets(awka_doln(1, 0)), "long")) || ((((((awka_length(awka_doln(1, 0)) > awka_getd(_litd0_awka)) &&  strcmp(awka_gets(awka_left(a_TEMP, awka_doln(1, 0), _litd2_awka)), " "))) &&  strcmp(awka_gets(awka_left(a_TEMP, awka_doln(1, 0), _litd2_awka)), "	"))) &&  strcmp(awka_gets(awka_left(a_TEMP, awka_doln(1, 0), _litd2_awka)), "#")))
    {
      if (alignment_awk->dval != 4)
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits12_awka));
      }
      awka_vardblset(alignment_awk, 4);
      __257:;
    }
    awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
    if (awka_vartrue(post_align_awk))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits12_awka));
      awka_vardblset(post_align_awk, 0);
    }
    nextrec:;
  }
}

int
main(int argc, char *argv[])
{
  _max_base_gc = 3;
  _max_fn_gc = 2;

  awka_varinit(code_awk);
  awka_varinit(long_awk);
  awka_varinit(alignment_awk);
  awka_varinit(post_align_awk);

  awka_varinit(_litd0_awka); awka_setd(_litd0_awka) = 0;
  awka_varinit(_litd1_awka); awka_setd(_litd1_awka) = 4;
  awka_varinit(_litd2_awka); awka_setd(_litd2_awka) = 1;
  awka_varinit(_litd3_awka); awka_setd(_litd3_awka) = 2;
  awka_varinit(_lits0_awka); awka_strcpy(_lits0_awka, "}");
  awka_varinit(_lits1_awka); awka_strcpy(_lits1_awka, "alignl");
  awka_varinit(_lits2_awka); awka_strcpy(_lits2_awka, "alignw");
  awka_varinit(_lits3_awka); awka_strcpy(_lits3_awka, "byte");
  awka_varinit(_lits4_awka); awka_strcpy(_lits4_awka, "word");
  awka_varinit(_lits5_awka); awka_strcpy(_lits5_awka, " alignw ' align word");
  awka_varinit(_lits6_awka); awka_strcpy(_lits6_awka, "I16B_EXEC");
  awka_varinit(_lits7_awka); awka_strcpy(_lits7_awka, "I16B_PASM");
  awka_varinit(_lits8_awka); awka_strcpy(_lits8_awka, "long");
  awka_varinit(_lits9_awka); awka_strcpy(_lits9_awka, " ");
  awka_varinit(_lits10_awka); awka_strcpy(_lits10_awka, "	");
  awka_varinit(_lits11_awka); awka_strcpy(_lits11_awka, "#");
  awka_varinit(_lits12_awka); awka_strcpy(_lits12_awka, " alignl ' align long");
  awka_varinit(_litr0_awka); awka_strcpy(_litr0_awka, "/^'/"); awka_getre(_litr0_awka);
  awka_varinit(_litr1_awka); awka_strcpy(_litr1_awka, "/^{/"); awka_getre(_litr1_awka);

  if (!_lvar) {
    malloc( &_lvar, 20 * sizeof(a_VAR *) );
    _lvar[0] = _litd0_awka;
    _lvar[1] = _litd1_awka;
    _lvar[2] = _litd2_awka;
    _lvar[3] = _litd3_awka;
    _lvar[4] = _lits0_awka;
    _lvar[5] = _lits1_awka;
    _lvar[6] = _lits2_awka;
    _lvar[7] = _lits3_awka;
    _lvar[8] = _lits4_awka;
    _lvar[9] = _lits5_awka;
    _lvar[10] = _lits6_awka;
    _lvar[11] = _lits7_awka;
    _lvar[12] = _lits8_awka;
    _lvar[13] = _lits9_awka;
    _lvar[14] = _lits10_awka;
    _lvar[15] = _lits11_awka;
    _lvar[16] = _lits12_awka;
    _lvar[17] = _litr0_awka;
    _lvar[18] = _litr1_awka;
    _lvar[19] = NULL;
  }

  malloc( &_gvar, 5 * sizeof(struct gvar_struct) );
  awka_initgvar(0, "code_awk", code_awk);
  awka_initgvar(1, "long_awk", long_awk);
  awka_initgvar(2, "alignment_awk", alignment_awk);
  awka_initgvar(3, "post_align_awk", post_align_awk);
  _gvar[4].name = NULL;
  _gvar[4].var  = NULL;

  malloc( &_awkafn, 1 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = NULL;
  _awkafn[0].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _split_max = 2;
  _split_req = 1;
  _dol0_used = 1;

  BEGIN();
  MAIN();

  free(_litd0_awka);
  free(_litd1_awka);
  free(_litd2_awka);
  free(_litd3_awka);
  free(_lits0_awka->ptr); free(_lits0_awka);
  free(_lits1_awka->ptr); free(_lits1_awka);
  free(_lits2_awka->ptr); free(_lits2_awka);
  free(_lits3_awka->ptr); free(_lits3_awka);
  free(_lits4_awka->ptr); free(_lits4_awka);
  free(_lits5_awka->ptr); free(_lits5_awka);
  free(_lits6_awka->ptr); free(_lits6_awka);
  free(_lits7_awka->ptr); free(_lits7_awka);
  free(_lits8_awka->ptr); free(_lits8_awka);
  free(_lits9_awka->ptr); free(_lits9_awka);
  free(_lits10_awka->ptr); free(_lits10_awka);
  free(_lits11_awka->ptr); free(_lits11_awka);
  free(_lits12_awka->ptr); free(_lits12_awka);
  awka_killvar(_litr0_awka); free(_litr0_awka);
  awka_killvar(_litr1_awka); free(_litr1_awka);

  awka_exit(0);
}
