/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>
#include <cat_functions.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;
a_VAR *i_awk = NULL;

struct gvar_struct *_gvar;

a_VAR **_lvar;
a_VAR *_litd0_awka=NULL;
a_VAR *_lits0_awka=NULL, *_lits1_awka=NULL, *_lits2_awka=NULL, *_lits3_awka=NULL;
a_VAR *_litr0_awka=NULL, *_litr1_awka=NULL, *_litr2_awka=NULL, *_litr3_awka=NULL, *_litr4_awka=NULL, *_litr5_awka=NULL, *_litr6_awka=NULL, *_litr7_awka=NULL, *_litr8_awka=NULL;
void BEGIN();
void MAIN();

void
BEGIN()
{
  awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits0_awka));

}


void
MAIN()
{
  int i, _curfile;
  if (*(awka_gets(a_bivar[a_FILENAME])) == '\0')
    awka_strcpy(a_bivar[a_FILENAME], "");
  i = setjmp(context);
  while (awka_getline(a_TEMP, awka_dol0(0), awka_gets(a_bivar[a_FILENAME]), FALSE, TRUE)->dval > 0 && awka_setNF())
  {
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd0_awka)), "}"))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat(a_TEMP, awka_vararg(a_TEMP, _lits2_awka, awka_vardup(awka_doln(1, 0)), _lits2_awka, awka_vardup(awka_doln(2, 0)), _lits2_awka, awka_vardup(awka_doln(3, 0)), _lits2_awka, awka_vardup(awka_doln(4, 0)), _lits3_awka, awka_tmp_dbl2var(++awka_setd(i_awk)), NULL))));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat(a_TEMP, awka_vararg(a_TEMP, _lits2_awka, awka_vardup(awka_doln(1, 0)), _lits2_awka, awka_vardup(awka_doln(2, 0)), _lits2_awka, awka_vardup(awka_doln(3, 0)), _lits2_awka, awka_vardup(awka_doln(4, 0)), _lits3_awka, awka_tmp_dbl2var(++awka_setd(i_awk)), NULL))));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat(a_TEMP, awka_vararg(a_TEMP, _lits2_awka, awka_vardup(awka_doln(1, 0)), _lits2_awka, awka_vardup(awka_doln(2, 0)), _lits2_awka, awka_vardup(awka_doln(3, 0)), _lits2_awka, awka_vardup(awka_doln(4, 0)), _lits3_awka, awka_tmp_dbl2var(++awka_setd(i_awk)), NULL))));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat(a_TEMP, awka_vararg(a_TEMP, _lits2_awka, awka_vardup(awka_doln(1, 0)), _lits2_awka, awka_vardup(awka_doln(2, 0)), _lits2_awka, awka_vardup(awka_doln(3, 0)), _lits2_awka, awka_vardup(awka_doln(4, 0)), _lits3_awka, awka_tmp_dbl2var(++awka_setd(i_awk)), NULL))));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat(a_TEMP, awka_vararg(a_TEMP, _lits2_awka, awka_vardup(awka_doln(1, 0)), _lits2_awka, awka_vardup(awka_doln(2, 0)), _lits2_awka, awka_vardup(awka_doln(3, 0)), _lits2_awka, awka_vardup(awka_doln(4, 0)), _lits3_awka, awka_tmp_dbl2var(++awka_setd(i_awk)), NULL))));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat(a_TEMP, awka_vararg(a_TEMP, _lits2_awka, awka_vardup(awka_doln(1, 0)), _lits2_awka, awka_vardup(awka_doln(2, 0)), _lits2_awka, awka_vardup(awka_doln(3, 0)), _lits2_awka, awka_vardup(awka_doln(4, 0)), _lits3_awka, awka_tmp_dbl2var(++awka_setd(i_awk)), NULL))));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_strconcat(a_TEMP, awka_vararg(a_TEMP, _lits2_awka, awka_vardup(awka_doln(1, 0)), _lits2_awka, awka_vardup(awka_doln(2, 0)), _lits2_awka, awka_vardup(awka_doln(3, 0)), _lits2_awka, awka_vardup(awka_doln(4, 0)), _lits3_awka, awka_tmp_dbl2var(++awka_setd(i_awk)), NULL))));
      goto nextrec;
    }
    awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
    nextrec:;
  }
}

int
main(int argc, char *argv[])
{
  _max_base_gc = 12;
  _max_fn_gc = 2;

  awka_varinit(i_awk);

  awka_varinit(_litd0_awka); awka_setd(_litd0_awka) = 1;
  awka_varinit(_lits0_awka); awka_strcpy(_lits0_awka, "' Catalina Optimized Warning : This is a temporary file used by the Catalina Optimizer\n' Catalina Optimized Warning : It is not intended to be used and will not run correctly\n");
  awka_varinit(_lits1_awka); awka_strcpy(_lits1_awka, "}");
  awka_varinit(_lits2_awka); awka_strcpy(_lits2_awka, " ");
  awka_varinit(_lits3_awka); awka_strcpy(_lits3_awka, " ' Catalina Optimizer ");
  awka_varinit(_litr0_awka); awka_strcpy(_litr0_awka, "/^'/"); awka_getre(_litr0_awka);
  awka_varinit(_litr1_awka); awka_strcpy(_litr1_awka, "/^{/"); awka_getre(_litr1_awka);
  awka_varinit(_litr2_awka); awka_strcpy(_litr2_awka, "/^[ \t]+long[ \t]+I32_JMPA/"); awka_getre(_litr2_awka);
  awka_varinit(_litr3_awka); awka_strcpy(_litr3_awka, "/^[ \t]+long[ \t]+I32_BR_Z/"); awka_getre(_litr3_awka);
  awka_varinit(_litr4_awka); awka_strcpy(_litr4_awka, "/^[ \t]+long[ \t]+I32_BRNZ/"); awka_getre(_litr4_awka);
  awka_varinit(_litr5_awka); awka_strcpy(_litr5_awka, "/^[ \t]+long[ \t]+I32_BR_A/"); awka_getre(_litr5_awka);
  awka_varinit(_litr6_awka); awka_strcpy(_litr6_awka, "/^[ \t]+long[ \t]+I32_BRAE/"); awka_getre(_litr6_awka);
  awka_varinit(_litr7_awka); awka_strcpy(_litr7_awka, "/^[ \t]+long[ \t]+I32_BR_B/"); awka_getre(_litr7_awka);
  awka_varinit(_litr8_awka); awka_strcpy(_litr8_awka, "/^[ \t]+long[ \t]+I32_BRBE/"); awka_getre(_litr8_awka);

  if (!_lvar) {
    malloc( &_lvar, 15 * sizeof(a_VAR *) );
    _lvar[0] = _litd0_awka;
    _lvar[1] = _lits0_awka;
    _lvar[2] = _lits1_awka;
    _lvar[3] = _lits2_awka;
    _lvar[4] = _lits3_awka;
    _lvar[5] = _litr0_awka;
    _lvar[6] = _litr1_awka;
    _lvar[7] = _litr2_awka;
    _lvar[8] = _litr3_awka;
    _lvar[9] = _litr4_awka;
    _lvar[10] = _litr5_awka;
    _lvar[11] = _litr6_awka;
    _lvar[12] = _litr7_awka;
    _lvar[13] = _litr8_awka;
    _lvar[14] = NULL;
  }

  malloc( &_gvar, 2 * sizeof(struct gvar_struct) );
  awka_initgvar(0, "i_awk", i_awk);
  _gvar[1].name = NULL;
  _gvar[1].var  = NULL;

  malloc( &_awkafn, 1 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = NULL;
  _awkafn[0].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _split_max = 4;
  _split_req = 1;
  _dol0_used = 1;

  BEGIN();
  MAIN();

  free(_litd0_awka);
  free(_lits0_awka->ptr); free(_lits0_awka);
  free(_lits1_awka->ptr); free(_lits1_awka);
  free(_lits2_awka->ptr); free(_lits2_awka);
  free(_lits3_awka->ptr); free(_lits3_awka);
  awka_killvar(_litr0_awka); free(_litr0_awka);
  awka_killvar(_litr1_awka); free(_litr1_awka);
  awka_killvar(_litr2_awka); free(_litr2_awka);
  awka_killvar(_litr3_awka); free(_litr3_awka);
  awka_killvar(_litr4_awka); free(_litr4_awka);
  awka_killvar(_litr5_awka); free(_litr5_awka);
  awka_killvar(_litr6_awka); free(_litr6_awka);
  awka_killvar(_litr7_awka); free(_litr7_awka);
  awka_killvar(_litr8_awka); free(_litr8_awka);

  awka_exit(0);
}
