/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>
#include <cat_functions.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;
a_VAR *f_awk = NULL;
a_VAR *bcl_awk = NULL;
a_VAR *spl_awk = NULL;
a_VAR *cal_awk = NULL;
a_VAR *cpl_awk = NULL;
a_VAR *sp1_awk = NULL;
a_VAR *sp2_awk = NULL;

struct gvar_struct *_gvar;

a_VAR **_lvar;
a_VAR *_litd0_awka=NULL, *_litd1_awka=NULL, *_litd2_awka=NULL, *_litd3_awka=NULL, *_litd4_awka=NULL, *_litd5_awka=NULL, *_litd6_awka=NULL;
a_VAR *_lits0_awka=NULL, *_lits1_awka=NULL, *_lits2_awka=NULL, *_lits3_awka=NULL, *_lits4_awka=NULL, *_lits5_awka=NULL, *_lits6_awka=NULL, *_lits7_awka=NULL, *_lits8_awka=NULL, *_lits9_awka=NULL, *_lits10_awka=NULL, *_lits11_awka=NULL, *_lits12_awka=NULL, *_lits13_awka=NULL, *_lits14_awka=NULL, *_lits15_awka=NULL, *_lits16_awka=NULL, *_lits17_awka=NULL, *_lits18_awka=NULL, *_lits19_awka=NULL, *_lits20_awka=NULL, *_lits21_awka=NULL, *_lits22_awka=NULL, *_lits23_awka=NULL;
a_VAR *_litr0_awka=NULL, *_litr1_awka=NULL, *_litr2_awka=NULL, *_litr3_awka=NULL, *_litr4_awka=NULL, *_litr5_awka=NULL, *_litr6_awka=NULL, *_litr7_awka=NULL, *_litr8_awka=NULL, *_litr9_awka=NULL, *_litr10_awka=NULL, *_litr11_awka=NULL, *_litr12_awka=NULL, *_litr13_awka=NULL, *_litr14_awka=NULL, *_litr15_awka=NULL, *_litr16_awka=NULL, *_litr17_awka=NULL;
void BEGIN();
void MAIN();

void
BEGIN()
{
  initialize_phase_3_fn(awka_arg0(a_TEMP));

}


void
MAIN()
{
  int i, _curfile;
  if (*(awka_gets(a_bivar[a_FILENAME])) == '\0')
    awka_strcpy(a_bivar[a_FILENAME], "");
  i = setjmp(context);
  while (awka_getline(a_TEMP, awka_dol0(0), awka_gets(a_bivar[a_FILENAME]), FALSE, TRUE)->dval > 0 && awka_setNF())
  {
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr0_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr1_awka, NULL)))
    {
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd0_awka)), "}"))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr2_awka, NULL)))
    {
      awka_varcpy(f_awk, awka_doln(1, 0));
      if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
      {
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr3_awka, NULL);
        awka_printf(NULL, 0, 0, awka_vararg(a_TEMP, _lits1_awka, f_awk, NULL));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
        {
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        }
        while (1)
        {
          if ((!strcmp(awka_gets(awka_doln(1, 0)), "long")) && !strcmp(awka_gets(awka_doln(2, 0)), "I32_RETF"))
          {
            break;
          }
          if ((!strcmp(awka_gets(awka_doln(1, 0)), "word")) && !strcmp(awka_gets(awka_doln(2, 0)), "I16B_RETF"))
          {
            break;
          }
          if ((!strcmp(awka_gets(awka_doln(1, 0)), "word")) && !strcmp(awka_gets(awka_doln(2, 0)), "I16B_RETN"))
          {
            break;
          }
          if ((((!strcmp(awka_gets(awka_doln(1, 0)), "word")) &&  !strcmp(awka_gets(awka_doln(2, 0)), "I16B_POPM"))) && strcmp(awka_gets(awka_doln(4, 0)), "$180<<S16B"))
          {
            break;
          }
          if ((((!strcmp(awka_gets(awka_doln(1, 0)), "'")) &&  !strcmp(awka_gets(awka_left(a_TEMP, awka_doln(2, 0), _litd1_awka)), "end"))) && !awka_varcmp(awka_doln(3, 0), f_awk))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr4_awka, NULL);
            break;
          }
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
          {
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          }
        }
        goto __273;
      }
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr5_awka, NULL);
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __273:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr6_awka, NULL)))
    {
      awka_varcpy(bcl_awk, awka_dol0(0));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
      {
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_ADDI + SP"))
      {
        awka_varcpy(spl_awk, awka_dol0(0));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
        {
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        }
        if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_CALA"))
        {
          awka_varcpy(cal_awk, awka_dol0(0));
          if (!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(4, 0), _litd0_awka)), "("))
          {
            awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits15_awka)));
            awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (6)))));
            goto __443;
          }
          awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits16_awka)));
          awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (5)))));
          __443:;
          if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL);
            insert_inline_fn(awka_arg1(a_TEMP, f_awk));
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits17_awka));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
            {
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            }
            if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_ADDI + SP"))
            {
              if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_LODA"))
              {
                awka_varcpy(spl_awk, awka_dol0(0));
                awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
                while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
                {
                  awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
                }
                if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " word I16A_ADD + SP"))
                {
                  awka_print(NULL, 0, 0, awka_arg1(a_TEMP, spl_awk));
                  awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
                }
                goto __575;
              }
              awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
              __575:;
            }
            goto __598;
          }
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, bcl_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, spl_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
          __598:;
          goto __621;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL);
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, bcl_awk));
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, spl_awk));
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        __621:;
        goto __882;
      }
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_CALA"))
      {
        awka_varcpy(cal_awk, awka_dol0(0));
        if (!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(4, 0), _litd0_awka)), "("))
        {
          awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits15_awka)));
          awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (6)))));
          goto __716;
        }
        awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits16_awka)));
        awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (5)))));
        __716:;
        if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL);
          insert_inline_fn(awka_arg1(a_TEMP, f_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits17_awka));
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
          {
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          }
          if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_ADDI + SP"))
          {
            if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_LODA"))
            {
              awka_varcpy(spl_awk, awka_dol0(0));
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
              {
                awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              }
              if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " word I16A_ADD + SP"))
              {
                awka_print(NULL, 0, 0, awka_arg1(a_TEMP, cal_awk));
                awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
              }
              goto __848;
            }
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
            __848:;
          }
          goto __865;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr10_awka, NULL);
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, bcl_awk));
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        __865:;
        goto __882;
      }
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL);
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, bcl_awk));
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __882:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr11_awka, NULL)))
    {
      awka_varcpy(bcl_awk, awka_dol0(0));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
      {
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_ADDI + SP"))
      {
        awka_varcpy(spl_awk, awka_dol0(0));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
        {
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        }
        if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_CALA"))
        {
          awka_varcpy(cal_awk, awka_dol0(0));
          if (!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(4, 0), _litd0_awka)), "("))
          {
            awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits15_awka)));
            awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (6)))));
            goto __1052;
          }
          awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits16_awka)));
          awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (5)))));
          __1052:;
          if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
          {
            awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL);
            insert_inline_fn(awka_arg1(a_TEMP, f_awk));
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits17_awka));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
            {
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            }
            if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_ADDI + SP"))
            {
              if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_LODA"))
              {
                awka_varcpy(spl_awk, awka_dol0(0));
                awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
                while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
                {
                  awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
                }
                if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " word I16A_ADD + SP"))
                {
                  awka_print(NULL, 0, 0, awka_arg1(a_TEMP, spl_awk));
                  awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
                }
                goto __1184;
              }
              awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
              __1184:;
            }
            goto __1207;
          }
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, bcl_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, spl_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
          __1207:;
          goto __1230;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL);
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, bcl_awk));
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, spl_awk));
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        __1230:;
        goto __1491;
      }
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_CALA"))
      {
        awka_varcpy(cal_awk, awka_dol0(0));
        if (!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(4, 0), _litd0_awka)), "("))
        {
          awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits15_awka)));
          awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (6)))));
          goto __1325;
        }
        awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits16_awka)));
        awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (5)))));
        __1325:;
        if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL);
          insert_inline_fn(awka_arg1(a_TEMP, f_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits17_awka));
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
          {
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          }
          if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_ADDI + SP"))
          {
            if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_LODA"))
            {
              awka_varcpy(spl_awk, awka_dol0(0));
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
              {
                awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              }
              if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " word I16A_ADD + SP"))
              {
                awka_print(NULL, 0, 0, awka_arg1(a_TEMP, cal_awk));
                awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
              }
              goto __1457;
            }
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
            __1457:;
          }
          goto __1474;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr10_awka, NULL);
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, bcl_awk));
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        __1474:;
        goto __1491;
      }
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL);
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, bcl_awk));
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __1491:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr12_awka, NULL)))
    {
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr13_awka, NULL);
      awka_varcpy(cpl_awk, awka_dol0(0));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
      {
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      awka_strcpy(sp1_awk, "");
      awka_strcpy(sp2_awk, "");
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_SUBI + SP"))
      {
        awka_varcpy(sp1_awk, awka_dol0(0));
        goto __1621;
      }
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_LODA"))
      {
        awka_varcpy(sp1_awk, awka_dol0(0));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
        {
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        }
        if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " word I16A_SUB + SP"))
        {
          awka_varcpy(sp2_awk, awka_dol0(0));
          __1621:;
      } }
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_CALA"))
      {
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr14_awka, NULL);
        awka_varcpy(cal_awk, awka_dol0(0));
        if (!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(4, 0), _litd0_awka)), "("))
        {
          awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits15_awka)));
          awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (6)))));
          goto __1717;
        }
        awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits16_awka)));
        awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (5)))));
        __1717:;
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr15_awka, NULL);
        if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL);
          insert_inline_fn(awka_arg1(a_TEMP, f_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits17_awka));
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
          {
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          }
          if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_ADDI + SP"))
          {
            if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_LODA"))
            {
              awka_varcpy(spl_awk, awka_dol0(0));
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
              {
                awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              }
              if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " word I16A_ADD + SP"))
              {
                awka_print(NULL, 0, 0, awka_arg1(a_TEMP, spl_awk));
                awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
              }
              goto __1852;
            }
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
            __1852:;
          }
          goto __1895;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, cpl_awk));
        if (strcmp(sp1_awk->ptr, ""))
        {
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, sp1_awk));
        }
        if (strcmp(sp2_awk->ptr, ""))
        {
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, sp2_awk));
        }
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        __1895:;
        goto __1938;
      }
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL);
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, cpl_awk));
      if (strcmp(sp1_awk->ptr, ""))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, sp1_awk));
      }
      if (strcmp(sp2_awk->ptr, ""))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, sp2_awk));
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __1938:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr16_awka, NULL)))
    {
      awka_varcpy(cpl_awk, awka_dol0(0));
      awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
      {
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
      }
      awka_strcpy(sp1_awk, "");
      awka_strcpy(sp2_awk, "");
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_SUBI + SP"))
      {
        awka_varcpy(sp1_awk, awka_dol0(0));
        goto __2065;
      }
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_LODA"))
      {
        awka_varcpy(sp1_awk, awka_dol0(0));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
        {
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        }
        if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " word I16A_SUB + SP"))
        {
          awka_varcpy(sp2_awk, awka_dol0(0));
          __2065:;
      } }
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_CALA"))
      {
        awka_varcpy(cal_awk, awka_dol0(0));
        if (!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(4, 0), _litd0_awka)), "("))
        {
          awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits15_awka)));
          awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (6)))));
          goto __2158;
        }
        awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits16_awka)));
        awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (5)))));
        __2158:;
        if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
        {
          awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL);
          insert_inline_fn(awka_arg1(a_TEMP, f_awk));
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits17_awka));
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
          {
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
          }
          if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_ADDI + SP"))
          {
            if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_LODA"))
            {
              awka_varcpy(spl_awk, awka_dol0(0));
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
              {
                awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
              }
              if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " word I16A_ADD + SP"))
              {
                awka_print(NULL, 0, 0, awka_arg1(a_TEMP, spl_awk));
                awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
              }
              goto __2290;
            }
            awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
            __2290:;
          }
          goto __2333;
        }
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr8_awka, NULL);
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, cpl_awk));
        if (strcmp(sp1_awk->ptr, ""))
        {
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, sp1_awk));
        }
        if (strcmp(sp2_awk->ptr, ""))
        {
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, sp2_awk));
        }
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
        __2333:;
        goto __2376;
      }
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL);
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, cpl_awk));
      if (strcmp(sp1_awk->ptr, ""))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, sp1_awk));
      }
      if (strcmp(sp2_awk->ptr, ""))
      {
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, sp2_awk));
      }
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __2376:;
      goto nextrec;
    }
    if (awka_vartrue(awka_match(a_TEMP, FALSE, awka_dol0(0), _litr17_awka, NULL)))
    {
      awka_varcpy(cal_awk, awka_dol0(0));
      if (!strcmp(awka_gets(awka_left(a_TEMP, awka_doln(4, 0), _litd0_awka)), "("))
      {
        awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits15_awka)));
        awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (6)))));
        goto __2462;
      }
      awka_varcpy(f_awk, awka_ltrim(a_TEMP, awka_arg2(a_TEMP, awka_doln(4, 0), _lits16_awka)));
      awka_varcpy(f_awk, awka_left(a_TEMP, f_awk, awka_tmp_dbl2var((awka_length(f_awk) - (5)))));
      __2462:;
      if (awka_vartrue(known_function_fn(awka_arg1(a_TEMP, f_awk))))
      {
        awka_match(a_TEMP, FALSE, awka_dol0(0), _litr7_awka, NULL);
        insert_inline_fn(awka_arg1(a_TEMP, f_awk));
        awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits17_awka));
        awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
        {
          awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
        }
        if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd2_awka)), " word I16A_ADDI + SP"))
        {
          if (!strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd3_awka)), " long I32_LODA"))
          {
            awka_varcpy(spl_awk, awka_dol0(0));
            awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            while (!strcmp(awka_gets(awka_doln(1, 0)), "alignl"))
            {
              awka_getline(a_TEMP, awka_dol0(2), awka_gets(a_bivar[a_FILENAME]), 0, TRUE);
            }
            if (strcmp(awka_gets(awka_left(a_TEMP, awka_dol0(0), _litd6_awka)), " word I16A_ADD + SP"))
            {
              awka_print(NULL, 0, 0, awka_arg1(a_TEMP, spl_awk));
              awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
            }
            goto __2594;
          }
          awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
          __2594:;
        }
        goto __2611;
      }
      awka_match(a_TEMP, FALSE, awka_dol0(0), _litr9_awka, NULL);
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, _lits23_awka));
      awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
      __2611:;
      goto nextrec;
    }
    awka_print(NULL, 0, 0, awka_arg1(a_TEMP, awka_dol0(0)));
    nextrec:;
  }
}

int
main(int argc, char *argv[])
{
  _max_base_gc = 4;
  _max_fn_gc = 2;

  awka_varinit(f_awk);
  awka_varinit(bcl_awk);
  awka_varinit(spl_awk);
  awka_varinit(cal_awk);
  awka_varinit(cpl_awk);
  awka_varinit(sp1_awk);
  awka_varinit(sp2_awk);

  awka_varinit(_litd0_awka); awka_setd(_litd0_awka) = 1;
  awka_varinit(_litd1_awka); awka_setd(_litd1_awka) = 3;
  awka_varinit(_litd2_awka); awka_setd(_litd2_awka) = 20;
  awka_varinit(_litd3_awka); awka_setd(_litd3_awka) = 14;
  awka_varinit(_litd4_awka); awka_setd(_litd4_awka) = 6;
  awka_varinit(_litd5_awka); awka_setd(_litd5_awka) = 5;
  awka_varinit(_litd6_awka); awka_setd(_litd6_awka) = 19;
  awka_varinit(_lits0_awka); awka_strcpy(_lits0_awka, "}");
  awka_varinit(_lits1_awka); awka_strcpy(_lits1_awka, "' Catalina Optimizer - %s removed (Inlined)\n");
  awka_varinit(_lits2_awka); awka_strcpy(_lits2_awka, "alignl");
  awka_varinit(_lits3_awka); awka_strcpy(_lits3_awka, "long");
  awka_varinit(_lits4_awka); awka_strcpy(_lits4_awka, "I32_RETF");
  awka_varinit(_lits5_awka); awka_strcpy(_lits5_awka, "word");
  awka_varinit(_lits6_awka); awka_strcpy(_lits6_awka, "I16B_RETF");
  awka_varinit(_lits7_awka); awka_strcpy(_lits7_awka, "I16B_RETN");
  awka_varinit(_lits8_awka); awka_strcpy(_lits8_awka, "I16B_POPM");
  awka_varinit(_lits9_awka); awka_strcpy(_lits9_awka, "$180<<S16B");
  awka_varinit(_lits10_awka); awka_strcpy(_lits10_awka, "'");
  awka_varinit(_lits11_awka); awka_strcpy(_lits11_awka, "end");
  awka_varinit(_lits12_awka); awka_strcpy(_lits12_awka, " word I16A_ADDI + SP");
  awka_varinit(_lits13_awka); awka_strcpy(_lits13_awka, " long I32_CALA");
  awka_varinit(_lits14_awka); awka_strcpy(_lits14_awka, "(");
  awka_varinit(_lits15_awka); awka_strcpy(_lits15_awka, "(@");
  awka_varinit(_lits16_awka); awka_strcpy(_lits16_awka, "@");
  awka_varinit(_lits17_awka); awka_strcpy(_lits17_awka, " alignl ' align long");
  awka_varinit(_lits18_awka); awka_strcpy(_lits18_awka, " long I32_LODA");
  awka_varinit(_lits19_awka); awka_strcpy(_lits19_awka, " word I16A_ADD + SP");
  awka_varinit(_lits20_awka); awka_strcpy(_lits20_awka, "");
  awka_varinit(_lits21_awka); awka_strcpy(_lits21_awka, " word I16A_SUBI + SP");
  awka_varinit(_lits22_awka); awka_strcpy(_lits22_awka, " word I16A_SUB + SP");
  awka_varinit(_lits23_awka); awka_strcpy(_lits23_awka, "' candidate for inlining rejected!");
  awka_varinit(_litr0_awka); awka_strcpy(_litr0_awka, "/^'/"); awka_getre(_litr0_awka);
  awka_varinit(_litr1_awka); awka_strcpy(_litr1_awka, "/^{/"); awka_getre(_litr1_awka);
  awka_varinit(_litr2_awka); awka_strcpy(_litr2_awka, "/^C_/"); awka_getre(_litr2_awka);
  awka_varinit(_litr3_awka); awka_strcpy(_litr3_awka, "/* remove the actual function (will be inlined at each call) */"); awka_getre(_litr3_awka);
  awka_varinit(_litr4_awka); awka_strcpy(_litr4_awka, "/* this line indicates we have reached the end, even if it is not a normal termination */"); awka_getre(_litr4_awka);
  awka_varinit(_litr5_awka); awka_strcpy(_litr5_awka, "/* not inlinable call - reconstruct original line */"); awka_getre(_litr5_awka);
  awka_varinit(_litr6_awka); awka_strcpy(_litr6_awka, "/^[ \t]+word[ \t]+I16A_MOVI[ \t]*\\+[ \t]*BC/"); awka_getre(_litr6_awka);
  awka_varinit(_litr7_awka); awka_strcpy(_litr7_awka, "/* inline it */"); awka_getre(_litr7_awka);
  awka_varinit(_litr8_awka); awka_strcpy(_litr8_awka, "/* not inlinable call - reconstruct lines */"); awka_getre(_litr8_awka);
  awka_varinit(_litr9_awka); awka_strcpy(_litr9_awka, "/* not inlinable call - reconstruct original lines */"); awka_getre(_litr9_awka);
  awka_varinit(_litr10_awka); awka_strcpy(_litr10_awka, "/* reconstruct lines */"); awka_getre(_litr10_awka);
  awka_varinit(_litr11_awka); awka_strcpy(_litr11_awka, "/^[ \t]+long[ \t]+I32_MOVI[ \t]*\\+[ \t]*BC/"); awka_getre(_litr11_awka);
  awka_varinit(_litr12_awka); awka_strcpy(_litr12_awka, "/^[ \t]+word[ \t]+I16B_CPREP/"); awka_getre(_litr12_awka);
  awka_varinit(_litr13_awka); awka_strcpy(_litr13_awka, "/* printf(\"cprep : %s\", $0) */"); awka_getre(_litr13_awka);
  awka_varinit(_litr14_awka); awka_strcpy(_litr14_awka, "/* printf(\"cala : %s\", $0) */"); awka_getre(_litr14_awka);
  awka_varinit(_litr15_awka); awka_strcpy(_litr15_awka, "/* printf(\"f : %s\", f) */"); awka_getre(_litr15_awka);
  awka_varinit(_litr16_awka); awka_strcpy(_litr16_awka, "/^[ \t]+long[ \t]+I32_CPREP/"); awka_getre(_litr16_awka);
  awka_varinit(_litr17_awka); awka_strcpy(_litr17_awka, "/^[ \t]+long[ \t]+I32_CALA/"); awka_getre(_litr17_awka);

  if (!_lvar) {
    malloc( &_lvar, 50 * sizeof(a_VAR *) );
    _lvar[0] = _litd0_awka;
    _lvar[1] = _litd1_awka;
    _lvar[2] = _litd2_awka;
    _lvar[3] = _litd3_awka;
    _lvar[4] = _litd4_awka;
    _lvar[5] = _litd5_awka;
    _lvar[6] = _litd6_awka;
    _lvar[7] = _lits0_awka;
    _lvar[8] = _lits1_awka;
    _lvar[9] = _lits2_awka;
    _lvar[10] = _lits3_awka;
    _lvar[11] = _lits4_awka;
    _lvar[12] = _lits5_awka;
    _lvar[13] = _lits6_awka;
    _lvar[14] = _lits7_awka;
    _lvar[15] = _lits8_awka;
    _lvar[16] = _lits9_awka;
    _lvar[17] = _lits10_awka;
    _lvar[18] = _lits11_awka;
    _lvar[19] = _lits12_awka;
    _lvar[20] = _lits13_awka;
    _lvar[21] = _lits14_awka;
    _lvar[22] = _lits15_awka;
    _lvar[23] = _lits16_awka;
    _lvar[24] = _lits17_awka;
    _lvar[25] = _lits18_awka;
    _lvar[26] = _lits19_awka;
    _lvar[27] = _lits20_awka;
    _lvar[28] = _lits21_awka;
    _lvar[29] = _lits22_awka;
    _lvar[30] = _lits23_awka;
    _lvar[31] = _litr0_awka;
    _lvar[32] = _litr1_awka;
    _lvar[33] = _litr2_awka;
    _lvar[34] = _litr3_awka;
    _lvar[35] = _litr4_awka;
    _lvar[36] = _litr5_awka;
    _lvar[37] = _litr6_awka;
    _lvar[38] = _litr7_awka;
    _lvar[39] = _litr8_awka;
    _lvar[40] = _litr9_awka;
    _lvar[41] = _litr10_awka;
    _lvar[42] = _litr11_awka;
    _lvar[43] = _litr12_awka;
    _lvar[44] = _litr13_awka;
    _lvar[45] = _litr14_awka;
    _lvar[46] = _litr15_awka;
    _lvar[47] = _litr16_awka;
    _lvar[48] = _litr17_awka;
    _lvar[49] = NULL;
  }

  malloc( &_gvar, 8 * sizeof(struct gvar_struct) );
  awka_initgvar(0, "f_awk", f_awk);
  awka_initgvar(1, "bcl_awk", bcl_awk);
  awka_initgvar(2, "spl_awk", spl_awk);
  awka_initgvar(3, "cal_awk", cal_awk);
  awka_initgvar(4, "cpl_awk", cpl_awk);
  awka_initgvar(5, "sp1_awk", sp1_awk);
  awka_initgvar(6, "sp2_awk", sp2_awk);
  _gvar[7].name = NULL;
  _gvar[7].var  = NULL;

  malloc( &_awkafn, 1 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = NULL;
  _awkafn[0].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _split_max = 4;
  _split_req = 1;
  _dol0_used = 1;

  BEGIN();
  MAIN();

  free(_litd0_awka);
  free(_litd1_awka);
  free(_litd2_awka);
  free(_litd3_awka);
  free(_litd4_awka);
  free(_litd5_awka);
  free(_litd6_awka);
  free(_lits0_awka->ptr); free(_lits0_awka);
  free(_lits1_awka->ptr); free(_lits1_awka);
  free(_lits2_awka->ptr); free(_lits2_awka);
  free(_lits3_awka->ptr); free(_lits3_awka);
  free(_lits4_awka->ptr); free(_lits4_awka);
  free(_lits5_awka->ptr); free(_lits5_awka);
  free(_lits6_awka->ptr); free(_lits6_awka);
  free(_lits7_awka->ptr); free(_lits7_awka);
  free(_lits8_awka->ptr); free(_lits8_awka);
  free(_lits9_awka->ptr); free(_lits9_awka);
  free(_lits10_awka->ptr); free(_lits10_awka);
  free(_lits11_awka->ptr); free(_lits11_awka);
  free(_lits12_awka->ptr); free(_lits12_awka);
  free(_lits13_awka->ptr); free(_lits13_awka);
  free(_lits14_awka->ptr); free(_lits14_awka);
  free(_lits15_awka->ptr); free(_lits15_awka);
  free(_lits16_awka->ptr); free(_lits16_awka);
  free(_lits17_awka->ptr); free(_lits17_awka);
  free(_lits18_awka->ptr); free(_lits18_awka);
  free(_lits19_awka->ptr); free(_lits19_awka);
  free(_lits20_awka->ptr); free(_lits20_awka);
  free(_lits21_awka->ptr); free(_lits21_awka);
  free(_lits22_awka->ptr); free(_lits22_awka);
  free(_lits23_awka->ptr); free(_lits23_awka);
  awka_killvar(_litr0_awka); free(_litr0_awka);
  awka_killvar(_litr1_awka); free(_litr1_awka);
  awka_killvar(_litr2_awka); free(_litr2_awka);
  awka_killvar(_litr3_awka); free(_litr3_awka);
  awka_killvar(_litr4_awka); free(_litr4_awka);
  awka_killvar(_litr5_awka); free(_litr5_awka);
  awka_killvar(_litr6_awka); free(_litr6_awka);
  awka_killvar(_litr7_awka); free(_litr7_awka);
  awka_killvar(_litr8_awka); free(_litr8_awka);
  awka_killvar(_litr9_awka); free(_litr9_awka);
  awka_killvar(_litr10_awka); free(_litr10_awka);
  awka_killvar(_litr11_awka); free(_litr11_awka);
  awka_killvar(_litr12_awka); free(_litr12_awka);
  awka_killvar(_litr13_awka); free(_litr13_awka);
  awka_killvar(_litr14_awka); free(_litr14_awka);
  awka_killvar(_litr15_awka); free(_litr15_awka);
  awka_killvar(_litr16_awka); free(_litr16_awka);
  awka_killvar(_litr17_awka); free(_litr17_awka);

  awka_exit(0);
}
