#!/bin/bash
#set -x
../catalina/awka -i cat_functions.h -f $1.awk> $1.c
gcc -m32 -I. -I../catalina -c cat_functions.c
gcc -m32 -I. -I../catalina -o $1 $1.c cat_functions.o ../catalina/awka-0.7.5/lib/libawka.a
