#!/bin/bash
if [[ ! -e $1 ]]; then
   echo ""
   echo "ERROR: invalid destination specified !"
   echo ""
   echo "usage: copy_all X:"
   echo ""
   echo "   where X: is the drive you use to read/write SD cards"
   echo ""
   echo "or:    copy_all dir/"
   echo ""        
   echo "   where dir is the directory you want to copy to"
   echo ""
   exit
fi

cp src/xvi.help $1help.xvi

if [ -f src/xvi.bin ]; then

   cp src/xvi.bin $1vi.bin

else

   cp src/xvi.binary $1vi.bin
   if [[ -e src/proxy.binary ]]; then
      cp src/proxy.binary $1proxy.bin  
   fi

fi
