#!/bin/bash
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: Environment variable CATALINA_DEFINE is set (to $CATALINA_DEFINE)"
   echo ""
   echo "You must undefine this environment variable before using this batch"
   echo "file, and instead specify the target and options on the command line."
   echo "";
   exit
elif [[ "$1" ==  "" ]] ; then
   echo ""
   echo "ERROR: no PLATFORM specified !"
   echo ""
   echo "usage: build_all [SUPERQUAD | RAMPAGE ] PLATFORM"
   echo ""
   echo "       where PLATFORM is:"
   echo ""
   echo "             HYDRA, HYBRID, RAMBLADE, RAMBLADE3, DEMO, DRACBLADE," 
   echo "             ASC, C3, DEMO, QUICKSTART, FLIP, CUSTOM,"
   echo "             TRIBLADEPROP CPU_2 or P2_EVAL (P2 only)"
   echo ""
   echo "             (use the command 'build_morheus' instead to build for MORPHEUS)"
   echo ""
   echo "       and   OPTIONS may include:"
   echo ""
   echo "                 options to configure the HMI, such as PC, VT100, TV or VGA,"
   echo "                 or options to configure the program loader, such as"
   echo "                 FLASH, CACHED, CACHED_1K, CACHED_2K, CACHED_4K, CACHED_8K"
   echo ""
   exit
fi
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]]; then
   TMP_LCCDIR=/opt/catalina	
fi
#
if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi   

catalyst_clean

platform=$1
if [ "${platform:0:2}" != "P2" ]; then 

   echo ""
   echo "   ================================"
   echo "   Building all Catalyst components"
   echo "   ================================"
   echo ""

   rm -fr bin/*
   cp CATALYST.TXT bin/

   cd core
   ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
   ./copy_all ../bin/
   cd ..

   cd xvi-2.47
   ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
   ./copy_all ../bin/
   cd ..

   if [[ "$1" != "C3" 
      && "$1" != "SUPERQUAD" ]]; then

     cd pascal/p5_c
     ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
     ./copy_all ../../bin/
     cd ../..

     cd jzip
     ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
     ./copy_all ../bin/
     cd ..

   fi

   if [[ "$1" != "SUPERQUAD" ]]; then

     cd dumbo_basic
     ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
     ./copy_all ../bin/
     cd ..

     cd sst
     ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
     ./copy_all ../bin/
     cd ..

     cd lua-5.1.4
     ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
     ./copy_all ../bin/
     cd ..

   fi

else

   echo ""
   echo "   ================================"
   echo "   Building all Catalyst components"
   echo "   ================================"
   echo ""

   rm -fr bin/*
   cp CATALYST.TXT bin/

   cd core
   ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
   ./copy_all ../bin/
   cd ..

   cd xvi-2.47
   ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
   ./copy_all ../bin/
   cd ..

   cd pascal/p5_c
   ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
   ./copy_all ../../bin/
   cd ../..

   cd jzip
   ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
   ./copy_all ../bin/
   cd ..

   cd dumbo_basic
   ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
   ./copy_all ../bin/
   cd ..

   cd sst
   ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
   ./copy_all ../bin/
   cd ..

   cd lua-5.1.4
   ./build_all $1 $2 $3 $4 $5 $6 $7 $8 $9
   ./copy_all ../bin/
   cd ..

fi

echo ""
echo "   ===="
echo "   Done"
echo "   ===="
echo ""

