#!/bin/bash
if [[ ! "$CATALINA_DEFINE" == "" ]]; then
   echo ""
   echo "ERROR: please unset CATALINA_DEFINE before running this script."
   echo "";
   echo "";
   exit
fi
#
TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]]; then
   TMP_LCCDIR=/opt/catalina	
fi
#
if [[ ! -e $TMP_LCCDIR/bin/catalina_env ]]; then
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi   
#
cd src
source build_tmp_var $1 $2 $3 $4 $5
CATALINA_DEFINE="MORPHEUS CPU_2 PC VT100 PROXY_SD PROXY_KEYBOARD PROXY_SCREEN $1 $2 $3 $4 $5"
export CATALINA_DEFINE
make -f makefile.cat clean
make -f makefile.cat
unset CATALINA_DEFINE
#
echo ""
source build_pasm_tmp_var $1 $2 $3 $4 $5
spinnaker -p -a "$TMP_LCCDIR/utilities/Generic_Proxy_Server.spin" -I "$TMP_LCCDIR/target" -o proxy -b -D MORPHEUS -D CPU_1 -D PC -D NO_MOUSE $TMP_VAR

cd ..
