include ../Makefile.inc

CCFLAGS += -C libinterrupts

all:
ifeq ($(COMPACT),TRUE)
	cp add_CT1.ce add_CT1.s    
	cp add_CT2.ce add_CT2.s
	cp add_CT3.ce add_CT3.s
	cp clr_int1.ce clr_int1.s
	cp clr_int2.ce clr_int2.s
	cp clr_int3.ce clr_int3.s
	cp cog_ATN.ce cog_ATN.s
	cp get_stat.ce get_stat.s
	cp nix_int1.ce nix_int1.s
	cp nix_int2.ce nix_int2.s
	cp nix_int3.ce nix_int3.s
	cp poll_ANY.ce poll_ANY.s
	cp poll_ATN.ce poll_ATN.s
	cp poll_CT1.ce poll_CT1.s
	cp poll_CT2.ce poll_CT2.s
	cp poll_CT3.ce poll_CT3.s
	cp poll_FBW.ce poll_FBW.s
	cp poll_PAT.ce poll_PAT.s
	cp poll_QMT.ce poll_QMT.s
	cp poll_SE1.ce poll_SE1.s
	cp poll_SE2.ce poll_SE2.s
	cp poll_SE3.ce poll_SE3.s
	cp poll_SE4.ce poll_SE4.s
	cp poll_XFI.ce poll_XFI.s
	cp poll_XMT.ce poll_XMT.s
	cp poll_XRL.ce poll_XRL.s
	cp poll_XRO.ce poll_XRO.s
	cp set_CT1.ce set_CT1.s
	cp set_CT2.ce set_CT2.s
	cp set_CT3.ce set_CT3.s
	cp set_int1.ce set_int1.s
	cp set_int2.ce set_int2.s
	cp set_int3.ce set_int3.s
	cp set_PAT.ce set_PAT.s
	cp set_SE1.ce set_SE1.s
	cp set_SE2.ce set_SE2.s
	cp set_SE3.ce set_SE3.s
	cp set_SE4.ce set_SE4.s
	cp sim_int1.ce sim_int1.s
	cp sim_int2.ce sim_int2.s
	cp sim_int3.ce sim_int3.s
	cp wait_ANY.ce wait_ANY.s
	cp wait_ATN.ce wait_ATN.s
	cp wait_CT1.ce wait_CT1.s
	cp wait_CT2.ce wait_CT2.s
	cp wait_CT3.ce wait_CT3.s
	cp wait_FBW.ce wait_FBW.s
	cp wait_PAT.ce wait_PAT.s
	cp wait_SE1.ce wait_SE1.s
	cp wait_SE2.ce wait_SE2.s
	cp wait_SE3.ce wait_SE3.s
	cp wait_SE4.ce wait_SE4.s
	cp wait_XFI.ce wait_XFI.s
	cp wait_XMT.ce wait_XMT.s
	cp wait_XRL.ce wait_XRL.s
	cp wait_XRO.ce wait_XRO.s
else
	$(SPINPP) $(SPINPPFLAGS) add_CT1.e add_CT1.s    
	$(SPINPP) $(SPINPPFLAGS) add_CT2.e add_CT2.s
	$(SPINPP) $(SPINPPFLAGS) add_CT3.e add_CT3.s
	$(SPINPP) $(SPINPPFLAGS) clr_int1.e clr_int1.s
	$(SPINPP) $(SPINPPFLAGS) clr_int2.e clr_int2.s
	$(SPINPP) $(SPINPPFLAGS) clr_int3.e clr_int3.s
	$(SPINPP) $(SPINPPFLAGS) cog_ATN.e cog_ATN.s
	$(SPINPP) $(SPINPPFLAGS) get_stat.e get_stat.s
	$(SPINPP) $(SPINPPFLAGS) nix_int1.e nix_int1.s
	$(SPINPP) $(SPINPPFLAGS) nix_int2.e nix_int2.s
	$(SPINPP) $(SPINPPFLAGS) nix_int3.e nix_int3.s
	$(SPINPP) $(SPINPPFLAGS) poll_ANY.e poll_ANY.s
	$(SPINPP) $(SPINPPFLAGS) poll_ATN.e poll_ATN.s
	$(SPINPP) $(SPINPPFLAGS) poll_CT1.e poll_CT1.s
	$(SPINPP) $(SPINPPFLAGS) poll_CT2.e poll_CT2.s
	$(SPINPP) $(SPINPPFLAGS) poll_CT3.e poll_CT3.s
	$(SPINPP) $(SPINPPFLAGS) poll_FBW.e poll_FBW.s
	$(SPINPP) $(SPINPPFLAGS) poll_PAT.e poll_PAT.s
	$(SPINPP) $(SPINPPFLAGS) poll_QMT.e poll_QMT.s
	$(SPINPP) $(SPINPPFLAGS) poll_SE1.e poll_SE1.s
	$(SPINPP) $(SPINPPFLAGS) poll_SE2.e poll_SE2.s
	$(SPINPP) $(SPINPPFLAGS) poll_SE3.e poll_SE3.s
	$(SPINPP) $(SPINPPFLAGS) poll_SE4.e poll_SE4.s
	$(SPINPP) $(SPINPPFLAGS) poll_XFI.e poll_XFI.s
	$(SPINPP) $(SPINPPFLAGS) poll_XMT.e poll_XMT.s
	$(SPINPP) $(SPINPPFLAGS) poll_XRL.e poll_XRL.s
	$(SPINPP) $(SPINPPFLAGS) poll_XRO.e poll_XRO.s
	$(SPINPP) $(SPINPPFLAGS) set_CT1.e set_CT1.s
	$(SPINPP) $(SPINPPFLAGS) set_CT2.e set_CT2.s
	$(SPINPP) $(SPINPPFLAGS) set_CT3.e set_CT3.s
	$(SPINPP) $(SPINPPFLAGS) set_int1.e set_int1.s
	$(SPINPP) $(SPINPPFLAGS) set_int2.e set_int2.s
	$(SPINPP) $(SPINPPFLAGS) set_int3.e set_int3.s
	$(SPINPP) $(SPINPPFLAGS) set_PAT.e set_PAT.s
	$(SPINPP) $(SPINPPFLAGS) set_SE1.e set_SE1.s
	$(SPINPP) $(SPINPPFLAGS) set_SE2.e set_SE2.s
	$(SPINPP) $(SPINPPFLAGS) set_SE3.e set_SE3.s
	$(SPINPP) $(SPINPPFLAGS) set_SE4.e set_SE4.s
	$(SPINPP) $(SPINPPFLAGS) sim_int1.e sim_int1.s
	$(SPINPP) $(SPINPPFLAGS) sim_int2.e sim_int2.s
	$(SPINPP) $(SPINPPFLAGS) sim_int3.e sim_int3.s
	$(SPINPP) $(SPINPPFLAGS) wait_ANY.e wait_ANY.s
	$(SPINPP) $(SPINPPFLAGS) wait_ATN.e wait_ATN.s
	$(SPINPP) $(SPINPPFLAGS) wait_CT1.e wait_CT1.s
	$(SPINPP) $(SPINPPFLAGS) wait_CT2.e wait_CT2.s
	$(SPINPP) $(SPINPPFLAGS) wait_CT3.e wait_CT3.s
	$(SPINPP) $(SPINPPFLAGS) wait_FBW.e wait_FBW.s
	$(SPINPP) $(SPINPPFLAGS) wait_PAT.e wait_PAT.s
	$(SPINPP) $(SPINPPFLAGS) wait_SE1.e wait_SE1.s
	$(SPINPP) $(SPINPPFLAGS) wait_SE2.e wait_SE2.s
	$(SPINPP) $(SPINPPFLAGS) wait_SE3.e wait_SE3.s
	$(SPINPP) $(SPINPPFLAGS) wait_SE4.e wait_SE4.s
	$(SPINPP) $(SPINPPFLAGS) wait_XFI.e wait_XFI.s
	$(SPINPP) $(SPINPPFLAGS) wait_XMT.e wait_XMT.s
	$(SPINPP) $(SPINPPFLAGS) wait_XRL.e wait_XRL.s
	$(SPINPP) $(SPINPPFLAGS) wait_XRO.e wait_XRO.s
endif

clean:
	-rm -f *.s
